Repository getdokan/dokan, pull requests merged in 2020-11, with the labels that each got.

#943 temporary disable WooCommerce payment and shipping setup step
  includes/Admin/SetupWizard.php
Labels: Needs Dev Review, Needs Testing

#942 Refactor/upgrade to pro
  includes/Assets.php
  src/admin/components/ProCta.vue
  src/admin/components/SettingsBanner.vue
  src/admin/components/UpgradeBanner.vue
  src/admin/pages/Help.vue
  src/admin/pages/Settings.vue
  src/admin/pages/Vendors.vue
  src/admin/pages/Withdraw.vue
Labels: Dev Review Done, QA approved, Ready to Merge

#944 fixed translation issue for dokan pro
  assets/js/vue-admin.js
  assets/js/vue-admin.min.js
  src/admin/main.js
Labels: Dev Review Done, QA approved, Ready to Merge

#946 fix: Product quick edit vendor not changing issue fixed
  includes/wc-template.php
Labels: Dev Review Done, Ready to Merge

#949 fix: vendor created by admin shows in search result
  includes/Vendor/Manager.php
Labels: Dev Review Done, Ready to Merge

#950 update: Apply new filter on product listing status
  templates/products/products-listing.php
Labels: Dev Review Done, Ready to Merge

#951 update: Add new filter on dokan_is_product_author
  includes/functions.php
Labels: Ready to Merge

#956 feat: limited time promotion admin notice
  dokan.php
  includes/Admin/LimitedTimePromotion.php
Labels: Needs Dev Review, QA approved

#954 fix: vendor edit admin commission on decimal separator as comma
  includes/Vendor/Manager.php
Labels: Dev Review Done, QA approved

#959 fix: timezone mismatch
  includes/Admin/LimitedTimePromotion.php
Labels: Needs Dev Review, Needs Testing

#953 fix: store reviews rest api
  includes/REST/StoreController.php
Labels: Dev Review Done, QA approved, Ready to Merge

#960 fix: search store by store name
  includes/REST/StoreController.php
Labels: Dev Review Done, Needs Author Reply, QA approved, Ready to Merge

#969 fix - fixed Order fetching issues with REST API #818 originally developed by @zamandevs
  includes/Order/functions.php
Labels: QA approved, Ready to Merge

#967 fix - fixed dokan_save_product() function sanitize issue for post_con…
  includes/Product/functions.php
Labels: Dev Review Done, Ready to Merge

#965 Update/wemail added on recommended plugins
  assets/images/wemail-logo.png
  includes/Admin/SetupWizard.php
Labels: Needs Dev Review, QA approved

#963 Feat/custom deactivation reason
  includes/Tracker.php
Labels: Dev Review Done, QA approved, Ready to Merge

#955 feat: dokan upgrade-to-pro modules page
  assets/images/dokan-upgrade-popup-bonus.svg
  assets/images/modules/ajax-live-search.png
  assets/images/modules/analytics.png
  assets/images/modules/auction.png
  assets/images/modules/booking.png
  assets/images/modules/color-scheme-customizer.png
  assets/images/modules/duplicate-product.png
  assets/images/modules/elementor.png
  assets/images/modules/follow-store.png
  assets/images/modules/geolocation.png
  assets/images/modules/import-export.png
  assets/images/modules/invoice.png
  assets/images/modules/live-chat.png
  assets/images/modules/paypal-adaptive.png
  assets/images/modules/product-addon.png
  assets/images/modules/product-enquiry.png
  assets/images/modules/report-abuse.png
  assets/images/modules/rma.png
  assets/images/modules/seller-vacation.png
  assets/images/modules/shipstation.png
  assets/images/modules/single-product-multivendor.png
  assets/images/modules/store-support.png
  assets/images/modules/stripe.png
  assets/images/modules/subscription.png
  assets/images/modules/vendor-review.png
  assets/images/modules/vendor-staff.png
  assets/images/modules/vendor-subscription-product.png
  assets/images/modules/vendor-verification.png
  assets/images/modules/wholesale.png
  assets/images/modules/wirecard-connect.png
  assets/images/modules/wpml.png
  includes/Admin/Menu.php
  includes/Assets.php
  src/admin/components/ModuleUpgradePopup.vue
  src/admin/pages/ProModules.vue
  src/admin/router/index.js
Labels: Dev Review Done, QA approved, Ready to Merge
