Repository getdokan/dokan, pull requests merged in 2020-12, with the labels that each got.

#992 Refactor/custom deactivation reasons
  includes/Tracker.php
Labels: Dev Review Done, QA approved, Ready to Merge

#990 Fix/dashboard warning and product listing cols issue
  templates/dashboard/big-counter-widget.php
  templates/products/products-listing.php
Labels: Dev Review Done, QA approved, Ready to Merge

#988 fix: missing translations for admin dashboard
  package-lock.json
  package.json
  src/admin/main.js
  src/admin/pages/Vendors.vue
  src/admin/pages/Withdraw.vue
Labels: Needs Dev Review, QA approved

#987 fix: Ordering issue on category dropdown on product listing filter area
  templates/products/listing-filter.php
Labels: Dev Review Done, QA approved, Ready to Merge

#985 fix: Store Settings page url issue when vendor dashboard use as child…
  includes/template-tags.php
Labels: Dev Review Done, QA approved, Ready to Merge

#984 fix: Store and store TOC template make high priority
  includes/Rewrites.php
Labels: Dev Review Done, Ready to Merge

#983 fix: Store listing page avatar image not showing properly
  templates/store-lists-loop.php
Labels: Dev Review Done, Ready to Merge

#979 fix: Upgrade to pro module page overlapping issue with admin notice, css & changed svg
  assets/images/dokan-upgrade-popup-bonus.svg
  src/admin/components/ModuleUpgradePopup.vue
  src/admin/pages/ProModules.vue
Labels: Dev Review Done, QA approved, Ready to Merge

#976 fix: vendor biography formatting issue
  includes/Vendor/Vendor.php
Labels: Dev Review Done, QA approved, Ready to Merge

#975 fix: store search with meta query
  includes/REST/StoreController.php
Labels: Needs Dev Review, QA approved

#974 fix: stock level wrong calculation on order note
  includes/Order/Hooks.php
  templates/orders/details.php
Labels: Needs Dev Review, QA approved

#972 fix: Vendor listing and withdraw page not loading from admin area whe…
  src/admin/pages/Vendors.vue
  src/admin/pages/Withdraw.vue
Labels: Dev Review Done, QA approved, Ready to Merge

#970 fix: added attribute slug with product api
  includes/REST/ProductController.php
Labels: Needs Dev Review, Ready to Merge

#964 Feature: store customizer and better theme support
  .editorconfig
  .prettierrc
  Gruntfile.js
  assets/css/style.css
  assets/images/customizer/2cl.png
  assets/images/customizer/2cr.png
  assets/js/customize-controls.js
  assets/js/customize-preview.js
  assets/js/dokan.js
  assets/src/js/script.js
  assets/src/less/store.less
  composer.lock
  dokan.php
  includes/Customizer.php
  includes/Customizer/HeadingControl.php
  includes/Customizer/RadioImageControl.php
  includes/ThemeSupport/Astra.php
  includes/ThemeSupport/Manager.php
  includes/ThemeSupport/Storefront.php
  includes/ThemeSupport/TwentyTwenty.php
  includes/store-functions.php
  includes/template-tags.php
  templates/store-header.php
  templates/store-sidebar.php
  templates/store.php
Labels: QA approved

#989 fix: Withdraw methods toggle options not working on dokan setup wizard
  includes/Admin/SetupWizard.php
Labels: Dev Review Done, QA approved, Ready to Merge

#998 fix: withdraw methods are not saving for some users via dokan upgrader
  includes/Upgrade/Upgrades.php
  includes/Upgrade/Upgrades/V_3_0_17.php
Labels: Dev Review Done

#999 Feat/holiday promotion
  includes/Admin/LimitedTimePromotion.php
Labels: Dev Review Done, QA approved

#1000 fix: page wrapper issue for store-toc page
  templates/store-toc.php
Labels: Dev Review Done, QA approved
