Repository getdokan/dokan, pull requests merged in 2021-04, with the labels that each got.

#1126 fix: capitalize vendor url in add new vendor
  src/admin/pages/VendorAccountFields.vue
Labels: Dev Review Done, QA approved

#1157 Fix/vendor setup page logo broken
  assets/src/less/setup.less
Labels: Needs Dev Review, QA approved

#1168 update: Store open close option disabled by default when a vendor reg…
  includes/Vendor/Vendor.php
Labels: Dev Review Done, QA approved

#1174 fix: Unable to add multiple lines to the Short Description field issu…
  assets/src/js/store-lists.js
Labels: Dev Review Done, QA approved

#1178 Update/add new hooks on admin setup wizard store step
  includes/Dashboard/Templates/Products.php
  templates/admin-setup-wizard/step-store.php
  templates/products/download-virtual.php
Labels: Needs Dev Review, QA approved

#1163 update: Order status for withdraw option added dokan lite #1139
  includes/Admin/Settings.php
  includes/Admin/SetupWizard.php
Labels: Dev Review Done, QA approved

#1158 new: New filters added on vendor product listing page
  includes/Dashboard/Templates/Products.php
  includes/functions.php
  includes/template-tags.php
  templates/products/listing-filter.php
  templates/products/listing-status-filter.php
  templates/products/products-listing.php
Labels: Dev Review Done, QA approved

#1161 fix: AZERTY keyboard restrict registration issue fixed #1129
  assets/js/vendor-registration.js
Labels: Dev Review Done, QA approved

#1169 update: Store list shortcode enhancement #1017
  includes/Shortcodes/Stores.php
Labels: Needs Dev Review, QA approved

#1171 Fix malformed store URL when the home URL contains a query parameter
  includes/functions.php
Labels: Dev Review Done, Ready to Merge

#1159 update: Sub orders set dynamic post status
  includes/wc-template.php
Labels: Dev Review Done

#1162 fix: Inconsistency template CSS class dokan-w3 issue fixed #1123
  templates/settings/address-form.php
Labels: Dev Review Done

#1165 fix: order export not filtered customer filtered data
  includes/Dashboard/Templates/Orders.php
Labels: Dev Review Done, QA approved

#1177 Fix: product count exclude booking product
  includes/functions.php
Labels: Needs Dev Review, QA approved

#1173 Fix malformed dashboard subpage URL when `page_link` is filtered to add a query parameter
  composer.json
  composer.lock
  includes/functions.php
Labels: Dev Review Done, QA approved

#1183 Fix single store page template layout
  templates/store-toc.php
Labels: Dev Review Done, Needs Testing
