Repository getdokan/dokan, pull requests merged in 2021-03, with the labels that each got.

#1097 update: Price fields showing for external product
  templates/orders/details.php
  templates/products/inventory.php
  templates/products/new-product-single.php
Labels: Dev Review Done, QA approved

#1109 update: Withdraw threshold function some more optimized
  includes/Order/functions.php
  includes/Vendor/Vendor.php
  includes/functions.php
Labels: Dev Review Done, QA approved

#1107 fix: Unable to save stock value for variation product issue fixed #1034
  templates/products/inventory.php
Labels: Needs Dev Review, QA approved

#966 feat: dokan_paypal_gateway
  Gruntfile.js
  assets/css/style.css
  assets/images/paypal-marketplace.png
  assets/js/paypal-checkout.js
  assets/src/js/paypal-checkout.js
  assets/src/less/paypal-payment-method.less
  assets/src/less/style.less
  dokan.php
  includes/Gateways/Manager.php
  includes/Gateways/PayPal/Abstracts/WebhookEventHandler.php
  includes/Gateways/PayPal/Ajax.php
  includes/Gateways/PayPal/CartHandler.php
  includes/Gateways/PayPal/Factories/EventFactory.php
  includes/Gateways/PayPal/Helper.php
  includes/Gateways/PayPal/Manager.php
  includes/Gateways/PayPal/PaymentMethod/DokanPayPal.php
  includes/Gateways/PayPal/Utilities/Processor.php
  includes/Gateways/PayPal/VendorWithdrawMethod.php
  includes/Gateways/PayPal/WebhookEvents/CheckoutOrderApproved.php
  includes/Gateways/PayPal/WebhookEvents/CheckoutOrderCompleted.php
  includes/Gateways/PayPal/WebhookEvents/MerchantPartnerConsentRevoked.php
  includes/Gateways/PayPal/WebhookHandler.php
  includes/functions.php
  includes/wc-functions.php
  package-lock.json
  templates/gateways/paypal/3DS-payment-option.php
  templates/gateways/paypal/admin-options.php
  templates/gateways/paypal/vendor-settings-payment.php
Labels: Bug, Needs Dev Review

#1115 fix: different edit url for different product status
  includes/functions.php
Labels: Dev Review Done, QA approved

#1117 update: WP kses added new allow option for image tag
  templates/orders/order-item-html.php
  templates/products/products-listing-row.php
  templates/widgets/widget-content-product.php
Labels: Need Dev Review Only

#1118 refactor: updating SKU handling for products
  includes/wc-functions.php
Labels: Needs Dev Review, Needs Testing

#1119 fix: sale price popup error modal
  assets/src/js/script.js
Labels: Needs Dev Review, Needs Testing

#1125 fix: SetupWizard: Admin setup Wizard design is broken with wordpress …
  assets/src/less/setup.less
Labels: QA approved

#1128 update: limited time promotion for wedevs birthday
  includes/Admin/LimitedTimePromotion.php
Labels: Needs Dev Review, QA approved

#1136 new: Enter key allow for vendor search on store listing page
  assets/src/js/store-lists.js
  templates/store-lists-loop.php
Labels: Dev Review Done, QA approved

#1135 fix: Select2 block the input field in dropdown
  assets/vendors/select2/select2.css
  assets/vendors/select2/select2.min.css
Labels: Dev Review Done, QA approved

#1133 fix: time format with forward slash (\) wasn't parsing correctly on store open/close time dropdown
  includes/functions.php
  templates/settings/store-form.php
Labels: Needs Dev Review, QA approved

#1068 fix: Cancel order email is sent to the vendor
  includes/wc-functions.php
Labels: Dev Review Done, QA approved

#1132 refactor: product create update redundant check
  includes/Product/Manager.php
  includes/Product/functions.php
Labels: Dev Review Done, QA approved

#1121 fix: Divi theme store single page showing warning issue fixed
  includes/ThemeSupport/Divi.php
Labels: Dev Review Done, QA approved

#1082 feat: Vendors able to edit product slug from their product edit page
  assets/src/js/product-editor.js
  assets/src/less/products.less
  includes/Assets.php
  includes/Dashboard/Templates/Products.php
  templates/products/new-product-single.php
Labels: Needs Dev Review, QA approved

#1137 fix: iban, swift code number not showing in admin withdraw requests
  src/admin/pages/Withdraw.vue
Labels: QA approved

#1127 update: Set default values withdraw methods, limit, order status, com…
  includes/Admin/SetupWizard.php
Labels: Dev Review Done, QA approved

#1138 fix: Warning showing on all widget when use on elementor
  includes/Widgets/BestSellingProducts.php
  includes/Widgets/ProductCategoryMenu.php
  includes/Widgets/StoreCategoryMenu.php
  includes/Widgets/StoreContactForm.php
  includes/Widgets/StoreLocation.php
  includes/Widgets/StoreOpenClose.php
  includes/Widgets/TopratedProducts.php
Labels: Dev Review Done, QA approved
