Repository getdokan/dokan, pull requests merged in 2021-06, with the labels that each got.

#1124 POM implementation of Front end exploratory case for menu and my account
  .gitignore
  package-lock.json
  tests/e2e/codecept.conf.js
  tests/e2e/core-tests/explore_01_frontend_menu_test.js
  tests/e2e/core-tests/explore_02_backend_menu_test.js
  tests/e2e/core-tests/explore_02_frontend_settings_test.js
  tests/e2e/core-tests/group_01_product_explore_test.js
  tests/e2e/core-tests/group_02_product_func_test.js
  tests/e2e/core-tests/login_test.js
  tests/e2e/core-tests/modules/SPMV_01_admin_configure_test.js
  tests/e2e/core-tests/modules/SPMV_02_vendor_and_customer_test.js
  tests/e2e/core-tests/modules/auction_product_01_admin_settings_test.js
  tests/e2e/core-tests/modules/auction_product_02_add_test.js
  tests/e2e/core-tests/modules/auction_product_03_order_test.js
  tests/e2e/core-tests/modules/booking_01_add_product_test.js
  tests/e2e/core-tests/modules/booking_02_customer_purchase_test.js
  tests/e2e/core-tests/modules/live_search_Product_by_customer_02_test.js
  tests/e2e/core-tests/modules/live_search_configure_01_test.js
  tests/e2e/core-tests/modules/product_addon_01_test.js
  tests/e2e/core-tests/modules/product_addon_02_order_test.js
  tests/e2e/core-tests/modules/seller_support_reply_01_test.js
  tests/e2e/core-tests/modules/stripe_01_admin_configure_test.js
  tests/e2e/core-tests/modules/stripe_02_vendor_connect_test.js
  tests/e2e/core-tests/modules/stripe_03_customer_order_test.js
  tests/e2e/core-tests/modules/vacation_01_vendor_configure_test.js
  tests/e2e/core-tests/modules/vacation_02_view_customer_test.js
  tests/e2e/core-tests/modules/vendor_subscription_01_create_test.js
  tests/e2e/core-tests/modules/vendor_subscription_02_buy_test.js
  tests/e2e/core-tests/modules/wholesale_01_admin_configur_test.js
  tests/e2e/core-tests/modules/wholesale_02_add_product_test.js
  tests/e2e/core-tests/orders_01_single_test.js
  tests/e2e/core-tests/orders_02_multiple_test.js
  tests/e2e/core-tests/orders_03_multiple_vendor_test.js
  tests/e2e/core-tests/product_group_01_explore_test.js
  tests/e2e/core-tests/product_group_02_functionality_test.js
  tests/e2e/core-tests/product_simple_01_explore_test.js
  tests/e2e/core-tests/product_simple_02_product_functionality_test.js
  tests/e2e/core-tests/registration_01_vendor_test.js
  tests/e2e/core-tests/simple_01_product_explore_test.js
  tests/e2e/core-tests/simple_02_product_func_test.js
  tests/e2e/core-tests/store_review_01_test.js
  tests/e2e/core-tests/tax_01_admin_configure_test.js
  tests/e2e/core-tests/tax_02_customer_order_test.js
  tests/e2e/package.json
  tests/e2e/pages/config.js
  tests/e2e/pages/explore.js
  tests/e2e/pages/helpers.js
  tests/e2e/pages/locator.js
  tests/e2e/pom.code-workspace
  tests/e2e/step_definitions/simpleProduct.js
  tests/e2e/steps_file.js
Labels: Needs Author Reply, Needs Dev Review

#1206 fix: Typo in Staff - Manage Menu Permissions fixed #1201
  includes/functions.php
Labels: Dev Review Done

#1210 Fixed a bug that would allow vendors to change order status even if they don't have permission to do so
  includes/Ajax.php
  templates/orders/details.php
Labels: Dev Review Done

#1216 fix: email template override for dokan vendor completed order
  includes/Emails/Manager.php
Labels: Dev Review Done, QA approved

#1217 fix: Wrong hooks used on widgets
  deprecated/deprecated-hooks.php
Labels: Dev Review Done, Need Dev Review Only

#1235 "In stock" and "Out of stock" translation fixed
  templates/products/listing-status-filter.php
Labels: Dev Review Done

#1252 new: Register button added on login popup form
  includes/functions.php
  templates/login-form/login-form.php
Labels: Dev Review Done, QA approved

#1215 New/two new options added with stores listing short-codes
  includes/Shortcodes/Stores.php
Labels: Needs Dev Review, QA approved

#1223 new: Product add/edit page category list more beatify
  includes/Walkers/CategoryDropdownSingle.php
  includes/Walkers/TaxonomyDropdown.php
  templates/products/new-product.php
  templates/products/tmpl-add-product-popup.php
Labels: Dev Review Done, QA approved

#1232 new: Popup adding product response message when try create and add ne…
  assets/src/js/product-editor.js
  assets/src/less/products.less
  includes/Assets.php
  templates/products/tmpl-add-product-popup.php
Labels: Dev Review Done, QA approved

#1234 fix: Create a tag which is existing with a different case issue fixed…
  assets/src/js/product-editor.js
  includes/Ajax.php
  templates/products/new-product-single.php
  templates/products/new-product.php
  templates/products/tmpl-add-product-popup.php
Labels: Dev Review Done, QA approved

#1256 fixed: vendor order page pagination fixed for date and customer filter
  includes/Ajax.php
  includes/Order/functions.php
  templates/orders/date-export.php
  templates/orders/listing.php
Labels: Dev Review Done, QA approved

#1203 feat(api): Add support to send objects to trash
  includes/Abstracts/DokanRESTController.php
Labels: Dev Review Done

#1264 Fix: error in dokan setting
  includes/Admin/Settings.php
  includes/functions.php
Labels: Dev Review Done, Needs Testing

#1184 Feat/delivery-time
  assets/src/js/helper.js
  includes/Assets.php
  includes/functions.php
  src/admin/components/Fields.vue
  src/admin/pages/Settings.vue
  templates/orders/details.php
Labels: Needs Dev Review, QA approved

#1219 feat: Orderby filtering for store product listing
  assets/src/js/store-lists.js
  assets/src/less/store.less
  includes/Assets.php
  includes/Product/Hooks.php
  includes/Product/functions.php
  includes/Rewrites.php
Labels: Needs Dev Review, QA approved

#1231 new: Custom ip address lookup link added
  templates/orders/details.php
Labels: Dev Review Done, QA approved
