Repository getdokan/dokan, pull requests merged in 2021-01, with the labels that each got.

#1024 Feature: added “Visit Vendor Dashboard” link to adminbar
  includes/Admin/AdminBar.php
  includes/functions.php
Labels: QA approved

#1022 fix: Text domain missing on product listing delete confirmation alert…
  includes/Product/functions.php
Labels: Needs Dev Review, QA approved

#1020 fix: dashboard charts keeps growing
  src/admin/components/Chart.vue
  src/admin/pages/Dashboard.vue
Labels: Dev Review Done, QA approved

#1021 fix: lite modules page vendor staff showing wrong thumbnail
  src/admin/pages/ProModules.vue
Labels: Needs Dev Review, QA approved

#1016 fix: vendor search for disable vendor
  includes/Vendor/Manager.php
Labels: Needs Dev Review, QA approved

#1001 fix/product discount showing wrong
  includes/wc-functions.php
Labels: Needs Dev Review, QA approved

#1004 feat: searching option in dokan admin settings
  src/admin/pages/Settings.vue
Labels: Dev Review Done, Enhancement, QA approved

#1010 new: Vendor email add on replay to customer note mail
  includes/wc-functions.php
Labels: Dev Review Done, QA approved, Review Needed

#1012 Fix/dokan vendor add modal multiselect issue
  src/admin/pages/VendorAddressFields.vue
Labels: Needs Dev Review, QA approved

#1013 fix: admin dashboard sprintf loading issue
  src/admin/pages/Dashboard.vue
Labels: Needs Dev Review, QA approved

#1015 fix: Grammatical issue fixed on store listing
  templates/store-lists-filter.php
Labels: Dev Review Done

#1018 Responsive dashboard product and order table
  .editorconfig
  assets/css/style.css
  assets/js/dokan.js
  assets/src/js/script.js
  assets/src/less/extra.less
  assets/src/less/form.less
  assets/src/less/general.less
  assets/src/less/products.less
  assets/src/less/responsive.less
  assets/src/less/settings.less
  assets/src/less/site-navigation.less
  includes/Product/functions.php
  templates/orders/listing.php
  templates/products/listing-filter.php
  templates/products/products-listing-row.php
  templates/products/products-listing.php
  templates/settings/store-form.php
Labels: QA approved

#1019 Fix/store product category not showing properly
  includes/template-tags.php
Labels: Dev Review Done, QA approved

#1032 fix: error handling in store product category not showing properly
  includes/template-tags.php
Labels: Needs Dev Review

#1011 perf: dokan admin settings fast load and optimized
  includes/Admin/Settings.php
Labels: Needs Dev Review, QA approved

#1033 fix: product function error
  includes/Product/functions.php
Labels: Needs Dev Review

#1009 Update/dokan refund database table update
  includes/Install/Installer.php
  includes/Upgrade/Upgrades.php
  includes/Upgrade/Upgrades/BackgroundProcesses/V_3_1_1_RefundTableUpdate.php
  includes/Upgrade/Upgrades/V_3_1_1.php
Labels: Needs Dev Review, Review Needed

#1036 new: added current_datetime() dokan compatibility for wp version < 5.3
  includes/functions.php
Labels: Dev Review Done

#1044 Fix/search store by store name
  includes/REST/StoreController.php
  includes/Vendor/Manager.php
Labels: QA approved

#1040 feat: dokan changes notice
  includes/Admin/LimitedTimePromotion.php
Labels: Needs Dev Review, QA approved

#1025 The vendor can not change the display name
  includes/wc-functions.php
Labels: Needs Dev Review, QA approved

#1026 Fixed pagination problem while filtering store list #743
  assets/src/js/store-lists.js
Labels: Dev Review Done, QA approved

#1039 update: Improve the mapbox address input field in store settings page
  templates/maps/mapbox-with-search.php
Labels: Needs Dev Review, QA approved

#1037 Fix: vendor withdraw balance
  includes/Vendor/Vendor.php
Labels: Dev Review Done, QA approved

#1038 fix: Keep old vendor after product duplicate issue fixed
  includes/wc-functions.php
Labels: Needs Dev Review, QA approved

#1027 Enhance/subscription image count
  includes/wc-functions.php
  templates/products/new-product-single.php
  templates/products/tmpl-add-product-popup.php
Labels: Needs Dev Review, QA approved

#1028 Fix: REST API order total value gets rounded
  includes/REST/OrderController.php
Labels: Dev Review Done, QA approved

#1042 fix: Product REST API is not returning products with "Pending" & "Dra…
  includes/REST/ProductController.php
Labels: Dev Review Done, QA approved

#1047 fix: filter for $allowed_roles in vendor registration is missing
  includes/Registration.php
Labels: Needs Dev Review, QA approved

#1048 fix: Downloadable product "Grant Access" JS error Fixes #1017
  includes/Ajax.php
Labels: Needs Dev Review, QA approved

#1045 fix: Rounded vendor balance can not be withdrawn issue fixed #1030
  includes/Withdraw/Manager.php
Labels: Dev Review Done, QA approved

#1056 Enhancement: enable downloadable and virtual for subscription product
  includes/Dashboard/Templates/Products.php
Labels: Enhancement, Needs Dev Review, QA approved

#1005 update: Blank product page UI changed on vendor dashboard
  assets/images/no-product-found.svg
  assets/src/less/products.less
  templates/products/products-listing.php
Labels: Needs Dev Review, QA approved

#1006 new: Store open and closed status add on dokan store listing page
  assets/src/less/store-lists.less
  assets/src/less/store.less
  templates/store-lists-loop.php
Labels: QA approved, Ready to Merge

#1054 fix: Reset geolocation address it not selecting default location addr…
  includes/Dashboard/Templates/Settings.php
Labels: Dev Review Done, QA approved

#1061 fix: Featured attribute of the Store List shortcode doesn't work issu…
  includes/Vendor/Manager.php
Labels: Needs Dev Review, QA approved

#1053 new: Suggestion related to Update Settings button #93
  assets/src/js/script.js
  assets/src/less/settings.less
  includes/Assets.php
  templates/settings/header.php
Labels: Dev Review Done, QA approved, Ready to Merge

#1046 fix: Vendor count messed issue fixed #996
  includes/functions.php
  src/admin/pages/Vendors.vue
Labels: Dev Review Done, QA approved, Ready to Merge

#1050 fix: Product add pop-up validation error message style fix
  assets/src/less/products.less
Labels: Dev Review Done, QA approved, Ready to Merge

#1051 fix: vendor pending tab keeps loading
  includes/REST/StoreController.php
Labels: QA approved

#1064 Feat/withdrawl request promo
  assets/images/withdraw-request-promo.svg
  includes/Admin/LimitedTimePromotion.php
  includes/Withdraw/Manager.php
Labels: Needs Dev Review, QA approved

#1059 update: Add new filter hook for store per page number
  includes/Admin/Settings.php
  includes/Rewrites.php
  includes/Vendor/SetupWizard.php
  templates/settings/store-form.php
Labels: Needs Dev Review, QA approved

#1052 Fix:Site registration as vendor ghost touch fixes #998
  assets/css/style.css
  assets/js/dokan.js
  assets/src/less/login-form-popup.less
  templates/global/seller-registration-form.php
Labels: Needs Author Reply, Needs Dev Review, QA approved

#1066 fix: Update Setting button showing all setting page issue fixed
  assets/src/less/store-lists.less
  includes/Dashboard/Templates/Settings.php
  templates/settings/header.php
Labels: Dev Review Done, Needs Testing

#1072 fix: styling issues & lite, pro check for notices
  includes/Admin/LimitedTimePromotion.php
Labels: Needs Dev Review, QA approved

#1069 fix: More product tab showing other vendors product issue fixed #1049
  includes/wc-functions.php
Labels: Needs Dev Review, QA approved

#1075 fix: Order page cancelled menu not active when visit the page issue f…
  assets/src/js/script.js
  assets/src/less/store-lists.less
  includes/template-tags.php
  templates/products/products-listing.php
Labels: Needs Dev Review, Needs Testing

#1073 fix: Vendor setup wizard logo size issue fixed
  assets/css/setup.css
  includes/Admin/SetupWizard.php
  includes/Vendor/SetupWizard.php
Labels: Needs Dev Review, Needs Testing

#1070 fix:#1051 Mistake on the writing
  includes/Admin/Settings.php
Labels: Needs Testing

#1076 Fix/elementor conflict with shortcode
  includes/Shortcodes/BestSellingProduct.php
  includes/Shortcodes/TopRatedProduct.php
Labels: Needs Dev Review, Needs Testing
