Repository getdokan/dokan, pull requests merged in 2021-12, with the labels that each got.

#1438 enhance: Dashboard API
  includes/REST/Manager.php
  includes/REST/VendorDashboardController.php
Labels: Needs Dev Review

#1451 enhance: dashboard api endpoint `/vendor-dashboard/preferences`
  includes/REST/VendorDashboardController.php
Labels: REST API

#1444 Fix Problem with Loading data when permalink sets to plain.
  src/admin/pages/Vendors.vue
  src/admin/pages/Withdraw.vue
Labels: QA approved, Dev Review Done, Dependency With Pro

#1446 fix/select2 dropdown margin issue
  assets/src/less/products.less
Labels: QA approved, Dev Review Done

#1422 enhance: recaptcha integration to store contact form
  assets/src/js/helper.js
  assets/src/js/script.js
  includes/Admin/Settings.php
  includes/Ajax.php
  includes/Assets.php
  includes/functions.php
  templates/widgets/store-contact-form.php
Labels: QA approved, Dev Review Done

#1455 update readme.txt
  readme.txt
Labels: Need Dev Review Only

#1427 New Dokan admin notice design and Grouped notices.
  Gruntfile.js
  assets/css/dokan-upgrade.css
  assets/css/dokan-upgrade.css.map
  assets/css/global-admin.css
  assets/font/sf-pro-text/SF-Pro-Text-Bold.otf
  assets/font/sf-pro-text/SF-Pro-Text-Heavy.otf
  assets/font/sf-pro-text/SF-Pro-Text-Light.otf
  assets/font/sf-pro-text/SF-Pro-Text-Medium.otf
  assets/font/sf-pro-text/SF-Pro-Text-Regular.otf
  assets/font/sf-pro-text/SF-Pro-Text-Semibold.otf
  assets/js/dokan-admin.js
  assets/js/dokan-upgrade.js
  assets/js/dokan-upgrade.min.js
  assets/src/less/admin.less
  assets/src/less/global-admin.less
  dokan.php
  includes/Admin/LimitedTimePromotion.php
  includes/Admin/Menu.php
  includes/Admin/Notices/Helper.php
  includes/Admin/Notices/LimitedTimePromotion.php
  includes/Admin/Notices/Manager.php
  includes/Admin/Notices/PluginReview.php
  includes/Admin/Notices/SetupWizard.php
  includes/Admin/Notices/WhatsNew.php
  includes/Assets.php
  includes/REST/AdminNoticeController.php
  includes/REST/ChangeLogController.php
  includes/REST/Manager.php
  includes/Upgrade/AdminNotice.php
  includes/Upgrade/Hooks.php
  src/admin/components/AdminNotice.vue
  src/admin/components/UpgradeBanner.vue
  src/admin/pages/ChangeLog.vue
  src/admin/pages/Dashboard.vue
  src/admin/pages/Help.vue
  src/admin/pages/Settings.vue
  src/admin/pages/Vendors.vue
  src/admin/pages/Withdraw.vue
  src/admin/router/index.js
  src/notice/App.vue
  src/notice/main.js
  src/promo-notice/App.vue
  src/promo-notice/main.js
  src/upgrade/App.vue
  src/utils/Bootstrap.js
  templates/admin-header.php
  templates/admin-notice-dependencies.php
  templates/admin-notice/ask-for-review.php
  templates/admin-setup-wizard/run-wizard-notice.php
  templates/upgrade-notice.php
  templates/whats-new.php
  webpack.config.js
Labels: QA approved, Dev Review Done

#1465 new: integration of date range picker
  assets/vendors/date-range-picker/daterangepicker.css
  assets/vendors/date-range-picker/daterangepicker.js
  assets/vendors/date-range-picker/daterangepicker.min.css
  assets/vendors/date-range-picker/daterangepicker.min.js
  includes/Assets.php
Labels: Dev Review Done, Need Dev Review Only

#1461 fix: Fixed WP-User related caches for lower WP versions
  includes/Vendor/VendorCache.php
Labels: QA approved, Dev Review Done

#1464 fix: conflict Dokan admin notices scripts with customizer page
  assets/src/less/admin.less
  includes/Admin/Notices/Helper.php
  includes/Admin/Notices/LimitedTimePromotion.php
  includes/Admin/Notices/Manager.php
  includes/Assets.php
  src/admin/pages/ChangeLog.vue
  src/admin/pages/Vendors.vue
  src/notice/main.js
  src/promo-notice/main.js
  templates/admin-header.php
  templates/limited-time-promo-notice.php
Labels: QA approved, Dev Review Done, urgent
