Repository getdokan/dokan, pull requests merged in 2021-07, with the labels that each got.

#1266 fix: warning in product create page
  includes/Walkers/TaxonomyDropdown.php
Labels: Needs Dev Review, Needs Testing

#1267 update: added composer 2 support
  composer.json
  composer.lock
Labels: Needs Dev Review, QA approved

#1260 fix: flush rewrite rules after plugin is activated
  dokan.php
  includes/Admin/Settings.php
  includes/Rewrites.php
  templates/admin-notice-dependencies.php
Labels: Needs Dev Review, QA approved

#1213 Feat/gernamized module
  assets/js/vue-admin.js
  assets/js/vue-bootstrap.js
  includes/Admin/UserProfile.php
  includes/Customizer.php
  includes/Vendor/Manager.php
  src/admin/pages/VendorAccountFields.vue
  src/admin/pages/VendorAddressFields.vue
  src/admin/pages/VendorPaymentFields.vue
  templates/account/vendor-registration.php
  templates/global/seller-registration-form.php
  templates/settings/store-form.php
Labels: Dev Review Done, Need Dev Review Only

#1269 fix: dokan_product_gallery_image_count action added
  templates/products/new-product.php
Labels: Needs Dev Review, QA approved

#1265 update: hide create and add new button if only one product creation allowed
  templates/products/new-product.php
  templates/products/tmpl-add-product-popup.php
Labels: Needs Dev Review, QA approved

#1271 add: dokan summer sale promotion 2021
  includes/Admin/LimitedTimePromotion.php
Labels: Needs Dev Review, Needs Testing

#1275 Order item price
  includes/Commission.php
Labels: Need Dev Review Only

#1273 fix: Product tag search not working in variable product after adding new attribute
  assets/src/js/product-editor.js
Labels: Dev Review Done, QA approved

#1274 new: Add customize for store product filter option show/hide
  includes/Customizer.php
  includes/Product/Hooks.php
Labels: Dev Review Done, QA approved

#1218 fix: display shipping widget though virtual checkbox selected
  assets/src/js/product-editor.js
Labels: Dev Review Done, QA approved

#1277 Children IDs not showed on API REST
  includes/REST/ProductController.php
Labels: Dev Review Done, QA approved
