Repository getdokan/dokan, pull requests merged in 2021-09, with the labels that each got.

#1304 Fix/js deprecated warnings
  assets/js/dokan.js
  assets/js/vendor-registration.js
  assets/src/js/orders.js
  assets/src/js/product-editor.js
  assets/src/js/script.js
  assets/src/js/store-lists.js
  includes/Admin/UserProfile.php
  includes/Vendor/SetupWizard.php
  includes/Vendor/UserSwitch.php
  includes/wc-template.php
  templates/settings/store-form.php
Labels: QA approved, Dev Review Done

#1313 fixed: dokan_store_name meta missing
  includes/Upgrade/Upgrades.php
  includes/Upgrade/Upgrades/BackgroundProcesses/V_2_9_23_StoreName.php
  includes/Upgrade/Upgrades/V_3_2_12.php
  includes/Vendor/Manager.php
Labels: QA approved, Dev Review Done

#1314 fixed: Single store page map hide based on setting
  includes/Widgets/StoreLocation.php
Labels: QA approved, Dev Review Done

#1318 update: filter added for Order status list allowed for withdrawal
  includes/Admin/Settings.php
Labels: QA approved, Dev Review Done

#1319 new: Vendor settings update REST api #1192
  includes/REST/StoreSettingController.php
Labels: QA approved, Dev Review Done

#1321 new: Withdraw details keep save as log
  includes/Install/Installer.php
  includes/REST/WithdrawController.php
  includes/Upgrade/Upgrades.php
  includes/Upgrade/Upgrades/V_3_2_12.php
  includes/Withdraw/Manager.php
  includes/Withdraw/Withdraw.php
  src/admin/pages/Withdraw.vue
Labels: QA approved, Dev Review Done

#1315 Fix: Check if pagination_base post is empty
  templates/store-lists.php
Labels: Dev Review Done, Need Dev Review Only

#1326 fix: fixed warning on product listing page due to filter data type mismatch
  includes/Assets.php
  templates/products/listing-filter.php
  templates/products/new-product-single.php
  templates/products/products-listing.php
Labels: QA approved, Needs Dev Review

#1311 Refactor/modules
  tests/e2e/core-tests/modules/SPMV_01_admin_configure_test.js
  tests/e2e/core-tests/modules/SPMV_02_vendor_and_customer_test.js
  tests/e2e/core-tests/modules/auction_product_01_admin_settings_test.js
  tests/e2e/core-tests/modules/auction_product_02_add_test.js
  tests/e2e/core-tests/modules/auction_product_03_order_test.js
  tests/e2e/core-tests/modules/booking_01_add_product_test.js
  tests/e2e/core-tests/modules/booking_02_customer_purchase_test.js
  tests/e2e/core-tests/modules/live_search_Product_by_customer_02_test.js
  tests/e2e/core-tests/modules/live_search_configure_01_test.js
  tests/e2e/core-tests/modules/product_addon_01_test.js
  tests/e2e/core-tests/modules/product_addon_02_order_test.js
  tests/e2e/core-tests/modules/seller_support_reply_01_test.js
  tests/e2e/core-tests/modules/stripe_03_customer_order_test.js
  tests/e2e/core-tests/modules/vacation_02_view_customer_test.js
  tests/e2e/core-tests/modules/vendor_subscription_01_create_test.js
  tests/e2e/core-tests/modules/wholesale_01_admin_configur_test.js
  tests/e2e/core-tests/modules/wholesale_02_add_product_test.js
  tests/e2e/core-tests/simple_01_product_explore_test.js
  tests/e2e/example.codecept.conf.js
  tests/e2e/step_definitions/simpleProduct.js
Labels: Review Needed

#1286 Feat/store location pickup
  includes/Dashboard/Templates/Settings.php
  templates/settings/store-form.php
Labels: QA approved, Needs Dev Review

#1352 fix: Export order permission for staffs
  includes/Dashboard/Templates/Orders.php
  includes/functions.php
  templates/orders/date-export.php
Labels: QA approved, Dev Review Done

#1329 feat: Set limitation for how many product tags that vendor can input
  assets/js/dokan.js
  assets/src/js/product-editor.js
  includes/Assets.php
  includes/Dashboard/Templates/Products.php
  includes/Product/functions.php
Labels: QA approved, Dev Review Done

#1351 fix: Single store product search not working for logged out users
  includes/Product/Hooks.php
Labels: Needs Testing, Dev Review Done

#1344 Fix/localization issue attribute label
  assets/src/js/product-editor.js
  includes/Assets.php
Labels: Needs Testing, Needs Dev Review
