Repository getdokan/dokan, pull requests merged in 2021-11, with the labels that each got.

#1414 fix: Added missing param on woocommerce_admin_order_item_headers
  templates/orders/details.php
Labels: Ready to Merge

#1411 add: black friday promotion 2021
  includes/Admin/LimitedTimePromotion.php
Labels: QA approved, Dev Review Done

#1409 DateRangePicker library added
  package.json
  src/utils/Bootstrap.js
Labels: Dev Review Done, Need Dev Review Only

#1408 Fix(Product): add call to filter dokan_product_cat_dropdown_args to listing-filter.php
  templates/products/listing-filter.php
Labels: QA approved, Dev Review Done

#1403 fix: WC mail template overwrite issue fixed
  includes/Emails/VendorCompletedOrder.php
  includes/Emails/VendorNewOrder.php
Labels: QA approved, Dev Review Done

#1401 Fix[Product]: allow filter to prevent adding cart-item tag
  includes/wc-template.php
Labels: Dev Review Done, Need Dev Review Only

#1393 Render vendor email setting option conditionally
  templates/settings/store-form.php
Labels: QA approved, Dev Review Done

#1396 Fix/vendor store per page placeholder
  templates/settings/store-form.php
Labels: QA approved, Dev Review Done

#1391 Fix/update refund and withdraw database table column
  includes/Upgrade/Upgrades.php
  includes/Upgrade/Upgrades/V_3_3_1.php
Labels: QA approved, Dev Review Done

#1394 Removed user switch setting from Dokan selling setting
  includes/Vendor/UserSwitch.php
Labels: QA approved, Dev Review Done

#1381 new: asking for review notice on admin dashboard pages
  dokan.php
  includes/Admin/ReviewNotice.php
  includes/Install/Installer.php
  templates/admin-notice/ask-for-review.php
Labels: In Progress, Dev Review Done

#1348 Dokan Lite Caching: Enhancement and Fix
  dokan.php
  includes/Abstracts/DokanCache.php
  includes/Cache.php
  includes/CacheInvalidate.php
  includes/Commission.php
  includes/Order/Hooks.php
  includes/Order/Manager.php
  includes/Order/OrderCache.php
  includes/Order/functions.php
  includes/PageViews.php
  includes/Product/Hooks.php
  includes/Product/Manager.php
  includes/Product/ProductCache.php
  includes/Product/functions.php
  includes/REST/WithdrawController.php
  includes/Traits/ObjectCache.php
  includes/Traits/TransientCache.php
  includes/Vendor/Hooks.php
  includes/Vendor/Manager.php
  includes/Vendor/Vendor.php
  includes/Vendor/VendorCache.php
  includes/Withdraw/Hooks.php
  includes/Withdraw/Manager.php
  includes/Withdraw/WithdrawCache.php
  includes/Withdraw/functions.php
  includes/functions.php
  includes/reports.php
  includes/wc-functions.php
  templates/orders/date-export.php
Labels: Needs Testing, Dev Review Done

#1387 Fix downloadable virtual product support for auction module
  assets/src/js/product-editor.js
Labels: QA approved, Dev Review Done

#1390 Feat: added-necessary-tooltips-for-dokan-settings
  assets/src/less/admin.less
  includes/Admin/Settings.php
  src/admin/components/Fields.vue
Labels: QA approved, Dev Review Done

#1395 new: Google map and maxbox make always visible
  includes/Admin/Settings.php
Labels: QA approved, Dev Review Done

#1415 fix/unable-selling-actions-when-vendor-is-not-enabled
  includes/REST/ProductController.php
Labels: QA approved, Dev Review Done

#1417 fix: Withdraw details field value conflicting with old version
  includes/REST/WithdrawController.php
Labels: QA approved, Dev Review Done, Needs Code Enhancement, urgent

#1432 Fixes and Improved some more caching issues
  includes/CacheInvalidate.php
  includes/Order/functions.php
  includes/Product/ProductCache.php
  includes/Vendor/VendorCache.php
  includes/functions.php
Labels: Bug, Needs Dev Review
