Repository getdokan/dokan, pull requests merged in 2021-08, with the labels that each got.

#1284 hide customer information from vendor order export based on setting
  includes/Order/Hooks.php
Labels: QA approved, Dev Review Done

#1255 Category name order by ascending
  templates/products/new-product-single.php
  templates/products/new-product.php
  templates/products/tmpl-add-product-popup.php
Labels: QA approved, Dev Review Done

#1278 Fix: After submitting the Create Product from the selected category is not selected
  includes/Walkers/TaxonomyDropdown.php
Labels: QA approved, Dev Review Done

#1268 Test/automation
  .gitignore
  package-lock.json
  package.json
  tests/e2e/README.md
  tests/e2e/codecept.conf.js
  tests/e2e/core-tests/explore_01_frontend_menu_test.js
  tests/e2e/core-tests/explore_02_backend_menu_test.js
  tests/e2e/core-tests/explore_02_frontend_settings_test.js
  tests/e2e/core-tests/group_01_product_explore_test.js
  tests/e2e/core-tests/group_02_product_func_test.js
  tests/e2e/core-tests/orders_01_single_test.js
  tests/e2e/core-tests/orders_02_multiple_test.js
  tests/e2e/core-tests/orders_03_multiple_vendor_test.js
  tests/e2e/core-tests/product_group_01_explore_test.js
  tests/e2e/core-tests/product_group_02_functionality_test.js
  tests/e2e/core-tests/product_simple_01_explore_test.js
  tests/e2e/core-tests/product_simple_02_product_functionality_test.js
  tests/e2e/core-tests/simple_01_product_explore_test.js
  tests/e2e/core-tests/simple_02_product_func_test.js
  tests/e2e/example.codecept.conf.js 
  tests/e2e/package.json
  tests/e2e/step_definitions/steps.js
  tests/e2e/steps_file.js
Labels: Review Needed

#1299 fix: jQuery shorthand deprecation error fix
  assets/src/js/product-editor.js
  assets/src/js/script.js
  assets/src/js/store-lists.js
  includes/Vendor/UserSwitch.php
Labels: Needs Testing, Needs Dev Review

#1287 new: Stores listing orderby random
  includes/Rewrites.php
Labels: QA approved, Dev Review Done

#1291 Feat/add booking
  templates/orders/listing.php
Labels: QA approved, Dev Review Done

#1305 Tests/configuration
  tests/e2e/README.md
  tests/e2e/example.codecept.conf.js
Labels: Review Needed

#1292 fix: Fatal error when vendor registration shortcode use on api
  templates/account/vendor-registration.php
Labels: QA approved, Dev Review Done

#1293 Map API selection on setup wizardadmin
  templates/admin-setup-wizard/step-store.php
Labels: QA approved, Dev Review Done

#1294 new: Texty added on dokan recommended plugins
  assets/images/texty-logo.png
  includes/Admin/SetupWizard.php
Labels: QA approved, Needs Dev Review

#1296 Vendor filter added on Withdraw page
  src/admin/pages/Withdraw.vue
Labels: QA approved, Dev Review Done

#1290 New Rest Route To Get Corresponding Vendors Product Categories Under StoreController
  includes/REST/StoreController.php
  includes/Vendor/Vendor.php
  includes/Widgets/StoreCategoryMenu.php
  includes/functions.php
  includes/template-tags.php
  includes/wc-functions.php
Labels: QA approved, Dev Review Done

#1301 Added REST API request for Withdraw Create Request - Fixed #1198
  includes/REST/WithdrawController.php
Labels: QA approved, Dev Review Done

#1303 Fix #1282 : unable to remove downloadable file
  includes/wc-functions.php
Labels: QA approved, Dev Review Done
