Repository getdokan/dokan, pull requests merged in 2021-02, with the labels that each got.

#1089 fix: fixes nonce checking for some functions
  includes/Abstracts/DokanPromotion.php
  includes/Admin/LimitedTimePromotion.php
  includes/Admin/Settings.php
  includes/Admin/UserProfile.php
  includes/Ajax.php
  includes/Dashboard/Templates/Orders.php
  includes/Dashboard/Templates/Products.php
  includes/Dashboard/Templates/Settings.php
  includes/Dashboard/Templates/Withdraw.php
  includes/Product/Hooks.php
  includes/Registration.php
  includes/Vendor/SetupWizard.php
  includes/Vendor/UserSwitch.php
  includes/functions.php
  includes/wc-functions.php
  includes/wc-template.php
Labels: Needs Dev Review, Needs Testing

#1090 Fix/some codes optimized
  includes/Admin/Settings.php
  templates/products/products-listing.php
Labels: Needs Dev Review, Needs Testing

#1057 refactor: added filter support in order status for custom order statu…
  includes/Order/functions.php
Labels: Dev Review Done, QA approved

#1060 new: Vendor individual withdraw threshold option
  includes/Dashboard/Templates/Withdraw.php
  includes/Order/functions.php
  includes/REST/WithdrawController.php
  includes/Vendor/Vendor.php
  includes/functions.php
Labels: Needs Dev Review, QA approved

#1079 fix: product tab's post per page in more products
  includes/wc-functions.php
Labels: Needs Dev Review, QA approved

#1083 fix: product discount price is set empty if regular price is lower th…
  includes/wc-functions.php
Labels: Needs Dev Review, QA approved

#1095 fix: Unable to update product vai REST API issue fixed #1092
  includes/REST/ProductController.php
Labels: Dev Review Done, QA approved

#1099 fix: PHP 8 warning fix with minimal change
  includes/Upgrade/Manager.php
  includes/Vendor/Vendor.php
  includes/reports.php
  includes/template-tags.php
  includes/wc-functions.php
Labels: Needs Dev Review, QA approved

#1100 fix: on save store settings error fix
  includes/Dashboard/Templates/Settings.php
Labels: Dev Review Done, QA approved

#1102 fix: tracking number save issue fix
  includes/Ajax.php
  templates/orders/details.php
Labels: Dev Review Done, QA approved

#1103 new: New action hook added on setup wizard after selling save
  includes/Admin/SetupWizard.php
  templates/admin-setup-wizard/step-selling.php
Labels: Needs Dev Review, QA approved

#1104 New/vendor completed order email
  includes/Emails/Manager.php
  includes/Emails/VendorCompletedOrder.php
  templates/emails/plain/vendor-completed-order.php
  templates/emails/vendor-completed-order.php
Labels: Needs Dev Review, QA approved

#1086 fix: filtered order export on vendor dashboard
  includes/Order/functions.php
Labels: Needs Dev Review, QA approved

#1108 fix: gplus cleaning
  includes/Privacy.php
  includes/Registration.php
  includes/functions.php
  src/admin/pages/AddVendor.vue
  src/admin/pages/VendorSocialFields.vue
Labels: Needs Dev Review, QA approved

#1106 fix: fixes store/product orderby parameter for query
  includes/Product/Manager.php
  includes/Rewrites.php
Labels: Needs Dev Review, QA approved

#1087 fix: fixes dokan store open time timezone mismatch
  includes/functions.php
Labels: Needs Dev Review, QA approved

#1110 new: added a action when creating a suborder
  includes/Order/Manager.php
Labels: Needs Dev Review
