Repository getdokan/dokan, pull requests merged in 2022-05, with the labels that each got.

#1612 fix payment settings page 404
  templates/settings/payment.php
Labels: QA approved, Needs Dev Review

#1567 Fix/solved vendor store settings validation error
  templates/settings/store-form.php
Labels: QA approved, Dev Review Done

#1496 New shop widgets
  includes/Product/ProductCache.php
  includes/Rewrites.php
  includes/Vendor/Vendor.php
  includes/Widgets/FilterByAttributes.php
  includes/Widgets/Manager.php
  includes/template-tags.php
Labels: Enhancement, QA approved, Dev Review Done

#1613 Fix/bank payment method settings url
  templates/settings/bank-payment-method-settings.php
Labels: Needs Testing, Needs Dev Review, urgent

#1603 Fix/variable to external product fatal error
  includes/wc-functions.php
Labels: QA approved, Dev Review Done

#1607 Enhance/determine seller and payment method connection
  includes/Dashboard/Templates/Settings.php
  includes/Withdraw/functions.php
Labels: QA approved, Dev Review Done

#1608 Enhance/payment page dorpdown and back button
  assets/src/less/dashboard.less
  assets/src/less/setup.less
  templates/settings/bank-payment-method-settings.php
  templates/settings/payment-manage.php
  templates/settings/payment.php
Labels: QA approved, Dev Review Done

#1420 Fix[Order]: Determine the vendor a product belongs to correctly
  includes/Order/Hooks.php
Labels: Dev Review Done, Need Dev Review Only

#1611 Feat/reverse withdrawal
  Gruntfile.js
  assets/js/dokan-promo-notice.js
  assets/js/dokan-wp.js
  assets/js/reverse-withdrawal.js
  assets/js/vue-admin.js
  assets/js/vue-bootstrap.js
  assets/js/vue-frontend.js
  assets/js/vue-vendor.js
  assets/src/js/helper.js
  assets/src/js/reverse-withdrawal.js
  assets/src/less/reverse-withdrawal.less
  dokan.php
  includes/Admin/Menu.php
  includes/Admin/Settings.php
  includes/Assets.php
  includes/Dashboard/Templates/Manager.php
  includes/Dashboard/Templates/ReverseWithdrawal.php
  includes/Emails/Manager.php
  includes/Emails/ReverseWithdrawalInvoice.php
  includes/Install/Installer.php
  includes/Product/functions.php
  includes/REST/Manager.php
  includes/REST/ReverseWithdrawalController.php
  includes/ReverseWithdrawal/Admin/Hooks.php
  includes/ReverseWithdrawal/Admin/Settings.php
  includes/ReverseWithdrawal/Ajax.php
  includes/ReverseWithdrawal/BackgroundProcess/AsyncRequests.php
  includes/ReverseWithdrawal/BackgroundProcess/CronActions.php
  includes/ReverseWithdrawal/Cache.php
  includes/ReverseWithdrawal/Cart.php
  includes/ReverseWithdrawal/FailedActions.php
  includes/ReverseWithdrawal/Helper.php
  includes/ReverseWithdrawal/Hooks.php
  includes/ReverseWithdrawal/InstallerHelper.php
  includes/ReverseWithdrawal/Manager.php
  includes/ReverseWithdrawal/Order.php
  includes/ReverseWithdrawal/ReverseWithdrawal.php
  includes/ReverseWithdrawal/SettingsHelper.php
  includes/Rewrites.php
  includes/Shortcodes/Dashboard.php
  includes/Upgrade/Upgrades.php
  includes/Upgrade/Upgrades/V_3_3_8.php
  includes/Upgrade/Upgrades/V_3_5_1.php
  includes/functions.php
  src/admin/components/CardFunFact.vue
  src/admin/pages/ReverseWithdrawal.vue
  src/admin/pages/ReverseWithdrawalTransactions.vue
  src/admin/router/index.js
  src/utils/Bootstrap.js
  templates/emails/plain/reverse-withdrawal-invoice.php
  templates/emails/reverse-withdrawal-invoice.php
  templates/reverse-withdrawal/filters.php
  templates/reverse-withdrawal/header.php
  templates/reverse-withdrawal/reverse-balance.php
  templates/reverse-withdrawal/reverse-withdrawal.php
  templates/reverse-withdrawal/transaction-listing.php
  templates/vendor-store-info.php
  webpack.config.js
Labels: QA approved, Needs Dev Review
