Repository getdokan/dokan, pull requests merged in 2022-06, with the labels that each got.

#1618 Enhance/bank payment validation error filter
  includes/Dashboard/Templates/Settings.php
Labels: Dev Review Done, Need Dev Review Only

#1624 fix dokan payment settings doesn't support wpml translated links
  includes/Dashboard/Templates/Settings.php
  templates/settings/bank-payment-method-settings.php
  templates/settings/payment-manage.php
  templates/settings/payment.php
Labels: QA approved, Dev Review Done, urgent

#1622 Enhance/update admin settings & color picker ui
  assets/images/admin-settings-icons/appearance.svg
  assets/images/admin-settings-icons/general.svg
  assets/images/admin-settings-icons/page.svg
  assets/images/admin-settings-icons/privacy.svg
  assets/images/admin-settings-icons/reverse-witdrawal.svg
  assets/images/admin-settings-icons/selling.svg
  assets/images/admin-settings-icons/withdraw.svg
  assets/images/chart-line.svg
  assets/images/contact-icon.svg
  assets/images/dokan-logo.svg
  assets/images/google.svg
  includes/Admin/Settings.php
  includes/Product/VendorStoreInfo.php
  includes/ReverseWithdrawal/Admin/Settings.php
  includes/ReverseWithdrawal/SettingsHelper.php
  includes/functions.php
  src/admin/components/ColorPicker.vue
  src/admin/components/Fields.vue
  src/admin/components/GoogleMaps.vue
  src/admin/components/SocialFields.vue
  src/admin/pages/Settings.vue
  templates/admin-setup-wizard/step-store-wc-fields.php
  templates/settings/store-form.php
Labels: QA approved, Dev Review Done, urgent

#1633 update: settings api v2 tab and card support
  includes/Dashboard/Templates/Settings.php
  includes/Vendor/Settings.php
Labels: REST API

#1636 fix/dokan_pro_withdraw_methods_shown_even_if_dokan_pro_is_disabled
  includes/Withdraw/functions.php
Labels: QA approved, Dev Review Done

#1550 enhance/store-times-hover-feature-for-elementor
  assets/src/less/store.less
  includes/Widgets/StoreOpenClose.php
  templates/store-header-times.php
  templates/store-header.php
Labels: QA approved, Dev Review Done

#1637 Fix/wrong url of breadcrumb on single store page
  assets/src/js/script.js
  includes/Rewrites.php
Labels: QA approved, Dev Review Done

#1626 Enhance/vendor setup wizard message input field
  includes/Admin/Settings.php
  includes/Vendor/SetupWizard.php
Labels: QA approved, Dev Review Done

#1640 fix hide disconnect button on seller setup
  assets/src/less/dashboard.less
  includes/Vendor/SetupWizard.php
  includes/Withdraw/functions.php
Labels: Needs Testing, Needs Dev Review
