Repository getdokan/dokan, pull requests merged in 2022-12, with the labels that each got.

#1763 Enhance/single store page header menu and search filter responsiveness
  assets/src/less/responsive.less
  assets/src/less/store.less
  templates/store-header.php
Labels: QA approved, Dev Review Done, [Store]

#1774 [Fix]: Big counter widget total sales value type cast
  includes/functions.php
Labels: Needs Testing, Needs Dev Review

#1776 Update/vendor dashboard UI
  includes/template-tags.php
Labels: In Progress

#1769 Update api order list filter
  includes/Dashboard/Templates/Orders.php
  includes/Order/Manager.php
  includes/REST/OrderController.php
  includes/REST/VendorDashboardController.php
Labels: In Progress
