Repository getdokan/dokan, pull requests merged in 2022-08, with the labels that each got.

#1654 style fix broken third store header template
  assets/css/style.css
  assets/src/less/store.less
Labels: QA approved, Dev Review Done

#1536 fix: store page products broken layout of elementor widgets on storefront theme
  includes/ThemeSupport/Storefront.php
Labels: QA approved, Dev Review Done, Dependency With Pro

#1659 quick edit, bulk edit and admin product category update fix
  assets/src/js/product-category-ui.js
  includes/Product/Hooks.php
  includes/ProductCategory/Helper.php
  templates/products/dokan-category-header-ui.php
  templates/products/new-product-single.php
  templates/products/new-product.php
  templates/products/tmpl-add-product-popup.php
Labels: QA approved, Dev Review Done, urgent

#1663 subscription product category fix
  assets/src/js/product-category-ui.js
  assets/src/less/dokan-product-category-ui.less
  includes/ProductCategory/Categories.php
Labels: QA approved, Dev Review Done

#1668 bulk edit quick edit category fix
  assets/src/js/product-category-ui.js
  includes/ProductCategory/Helper.php
Labels: Needs Testing, Needs Dev Review

#1670 new: Added Catalog Mode Feature
  dokan.php
  includes/CatalogMode/Admin/Settings.php
  includes/CatalogMode/Controller.php
  includes/CatalogMode/Dashboard/ProductBulkEdit.php
  includes/CatalogMode/Dashboard/Products.php
  includes/CatalogMode/Dashboard/Settings.php
  includes/CatalogMode/Helper.php
  includes/CatalogMode/Hooks.php
  templates/products/catalog-mode-content.php
Labels: QA approved, Dev Review Done

#1672 fix: Removed unfiltered_html capabilities from vendors
  includes/Install/Installer.php
  includes/Upgrade/Upgrades.php
  includes/Upgrade/Upgrades/V_2_7_6.php
  includes/Upgrade/Upgrades/V_3_6_4.php
Labels: QA approved, urgent

#1671 New dokan category integration in booking and auction product
  includes/Dashboard/Templates/MultiStepCategories.php
  templates/products/dokan-category-header-ui.php
Labels: QA approved, Dev Review Done

#1655 fix: vendor dashboard color inconsistency
  assets/src/less/dashboard.less
  assets/src/less/extra.less
  assets/src/less/general.less
  assets/src/less/notice.less
  assets/src/less/orders.less
  assets/src/less/products.less
  assets/src/less/setup-no-wc.less
  assets/src/less/setup.less
  assets/src/less/withdraw.less
  templates/orders/date-export.php
  templates/products/listing-filter.php
  templates/settings/store-form.php
Labels: QA approved, Dev Review Done

#1673 Show multistep categories as language selected by wpml
  assets/src/js/product-category-ui.js
  includes/ProductCategory/Categories.php
  includes/ProductCategory/ProductCategoryCache.php
Labels: QA approved, Dev Review Done
