Repository getdokan/dokan, pull requests merged in 2022-11, with the labels that each got.

#1746 fix: SweetAlert library is conflicting with WooCommerce Conversion Tracking plugin
  src/admin/components/AdminNotice.vue
  src/admin/pages/AddVendor.vue
  src/admin/pages/DummyData.vue
  src/admin/pages/Settings.vue
Labels: QA approved, Dev Review Done, urgent

#1747 fix: [BestSellingProductWidget] Products are being shown on the widget even when the catalog visibility is set to hidden
  includes/Product/Manager.php
Labels: QA approved, Dev Review Done, urgent

#1748 fix: [VendorDashboardProducts] Products of different statuses are not displayed in the appropriate tab from the vendor dashboard.
  includes/functions.php
  includes/template-tags.php
  templates/products/listing-filter.php
  templates/products/listing-status-filter.php
Labels: QA approved, Dev Review Done, urgent

#1751 Multiple Github Issues
  Gruntfile.js
  assets/js/dokan-frontend.js
  assets/src/js/dokan-admin-product.js
  assets/src/js/dokan-frontend.js
  assets/src/js/product-category-ui.js
  assets/src/js/script.js
  assets/src/less/general.less
  includes/Assets.php
  includes/Dashboard/Templates/Settings.php
  includes/Product/Hooks.php
  includes/ProductCategory/Helper.php
  includes/Widgets/FilterByAttributes.php
  includes/Widgets/ProductCategoryMenu.php
  includes/Widgets/StoreCategoryMenu.php
  includes/functions.php
  includes/template-tags.php
  templates/settings/store-form.php
Labels: QA approved, Dev Review Done, urgent

#1753 Fixed store category filtering
  src/admin/pages/Vendors.vue
Labels: QA approved, Dev Review Done, Dependency With Pro

#1738 Enhancement: Order REST API date filter - after/before
  includes/REST/OrderController.php
Labels: QA approved, Dev Review Done

#1760 Add filter for bank payment fields placeholders
  includes/Withdraw/functions.php
  templates/settings/bank-payment-method-settings.php
Labels: QA approved, Dev Review Done

#1712 Update: UI/UX of vendor dashboard submenu
  assets/css/rtl.css
  assets/css/style.css
  assets/js/dokan.js
  assets/src/js/script.js
  assets/src/less/rtl.less
  assets/src/less/site-navigation.less
  assets/src/less/style.less
  includes/template-tags.php
Labels: QA approved, Needs Dev Review, Dependency With Pro

#1768 Enhancement: Section, sub-section label, description added in Setting…
  src/admin/pages/Settings.vue
Labels: Enhancement, QA approved, Needs Dev Review
