Repository getdokan/dokan, pull requests merged in 2022-10, with the labels that each got.

#1697 Fix Product and variation product upload image overlap.
  assets/src/less/products.less
Labels: QA approved, Dev Review Done

#1704 fix/review bulk action fields position
  assets/src/less/extra.less
  includes/ThemeSupport/Storefront.php
Labels: QA approved, Dev Review Done

#1715 Fix product search of the product listing page.
  includes/functions.php
  templates/products/listing-filter.php
Labels: QA approved, Dev Review Done, urgent

#1716 fixed/product create popup modal color issue
  assets/src/js/product-editor.js
  includes/Assets.php
Labels: QA approved, Dev Review Done

#1717 Fix multiple emails are sent to the customer when a parent order's status is changed failed to processing
  includes/functions.php
Labels: QA approved, Dev Review Done

#1723 Fix Unwanted code remove for Sweetalert library
  assets/vendors/sweetalert2/sweetalert2.all.min.js
  package.json
Labels: QA approved, Dev Review Done

#1726 Fix product price, make default empty insted zero
  templates/products/new-product.php
Labels: QA approved, Need Dev Review Only

#1727 Remove dokan meta data in order item in vendor dashboard
  templates/orders/order-item-html.php
Labels: QA approved, Need Dev Review Only

#1641 fix/update-dokan-time-formatting-problem
  assets/src/js/helper.js
  assets/vendors/jquery-ui/timepicker/timepicker.min.js
  assets/vendors/minitoggle/minitoggle.css
  assets/vendors/minitoggle/minitoggle.js
  includes/Assets.php
  includes/Dashboard/Templates/Settings.php
  includes/functions.php
  templates/settings/store-form.php
  templates/settings/store-time.php
Labels: QA approved, Dev Review Done

#1696 Fix decimal saperator in dokan percentage commission.
  includes/Admin/Settings.php
  includes/Assets.php
Labels: QA approved, Dev Review Done

#1702 Fix variable product stock fields inconsistency and missing inputs fields.
  assets/src/js/product-editor.js
  templates/products/inventory.php
Labels: QA approved, Dev Review Done

#1714 Tax amount box takes multiple decimal places in refund
  assets/src/js/orders.js
Labels: QA approved, Dev Review Done, Dependency With Pro

#1639 Seller Badge pro dependency
  includes/REST/StoreController.php
  src/admin/pages/Vendors.vue
Labels: QA approved, Dev Review Done, Dependency With Pro

#1721 Fix produt assigned to wrong user if save by shop manager
  assets/src/js/dokan-admin-product.js
  assets/src/less/dokan-admin-product.less
  includes/Admin/Hooks.php
  includes/Assets.php
  webpack.config.js
Labels: QA approved, Dev Review Done, urgent

#1734 Fix tnc allignment fix
  templates/store-toc.php
Labels: QA approved, Dev Review Done, urgent

#1737 Add dokan-admin-product.less to grunt.js for compilation
  Gruntfile.js
  assets/src/js/dokan-admin-product.js
Labels: Needs Testing, Needs Dev Review

#1741 Fix vendor assigning in quick and bulk edit
  assets/src/js/dokan-admin-product.js
  includes/Admin/Hooks.php
Labels: Needs Testing, Needs Dev Review

#1743 Fix up grader not showing for ongoing upgrder error
  includes/Upgrade/Upgrades/V_3_6_4.php
Labels: Needs Testing, Needs Dev Review, Dependency With Pro, urgent

#1745 Update order api
  includes/REST/OrderControllerV2.php
  includes/functions.php
  includes/wc-functions.php
Labels: In Progress
