Repository getdokan/dokan, pull requests merged in 2022-07, with the labels that each got.

#1519 Enhancement: Single & multiple category select UI update when product add & edit
  .gitignore
  Gruntfile.js
  assets/src/js/product-category-ui.js
  assets/src/less/dokan-product-category-ui.less
  dokan.php
  includes/Assets.php
  includes/Dashboard/Templates/Manager.php
  includes/Dashboard/Templates/MultiStepCategories.php
  includes/Dashboard/Templates/Products.php
  includes/Product/functions.php
  includes/ProductCategory/Categories.php
  includes/ProductCategory/Helper.php
  includes/ProductCategory/Hooks.php
  includes/ProductCategory/ProductCategoryCache.php
  includes/REST/Manager.php
  includes/REST/ProductController.php
  includes/Upgrade/Upgrades.php
  includes/Upgrade/Upgrades/BackgroundProcesses/V_3_6_2_UpdateProductCategories.php
  includes/Upgrade/Upgrades/V_3_6_2.php
  templates/products/dokan-category-header-ui.php
  templates/products/dokan-category-ui.php
  templates/products/new-product-single.php
  templates/products/new-product.php
  templates/products/tmpl-add-product-popup.php
  webpack.config.js
Labels: QA approved, Dev Review Done

#1616 Feat / Dokan dummy data
  assets/dummy-data/dokan_dummy_data.csv
  dokan.php
  includes/Assets.php
  includes/DummyData/Importer.php
  includes/REST/DummyDataController.php
  includes/REST/Manager.php
  package.json
  src/admin/pages/DummyData.vue
  src/admin/router/index.js
  templates/admin-header.php
Labels: QA approved, Dev Review Done

#1566 feat: dokan knowledge base
  package.json
  src/admin/App.vue
  src/admin/components/KnowledgeBase.vue
Labels: QA approved, Dev Review Done

#1632 enhance/split-field-heading-component-&-update-settings-fields-components
  assets/images/up-arrow.svg
  assets/src/less/site-navigation.less
  includes/Admin/Settings.php
  includes/ReverseWithdrawal/Admin/Settings.php
  src/admin/components/FieldHeading.vue
  src/admin/components/Fields.vue
  src/admin/components/SocialFields.vue
  src/admin/pages/Settings.vue
Labels: QA approved, Dev Review Done

#1643 New product add category ui fix
  includes/Assets.php
  includes/Dashboard/Templates/MultiStepCategories.php
Labels: QA approved, Needs Dev Review

#1644 update: changelog and dummy data page excluded in knowledgebase
  src/admin/components/KnowledgeBase.vue
Labels: Needs Testing, Needs Dev Review, Minor

#1480 Enhance/add filters to orders list in vendor dashboard
  assets/src/js/orders.js
  assets/src/less/orders.less
  includes/Assets.php
  includes/Dashboard/Templates/Orders.php
  includes/Order/Manager.php
  includes/Order/OrderCache.php
  includes/Order/functions.php
  includes/REST/OrderController.php
  includes/template-tags.php
  templates/orders/date-export.php
  templates/orders/details.php
  templates/orders/listing.php
Labels: QA approved, Dev Review Done

#1453 added: dokan_settings_selling_options filter for catalog product
  includes/Admin/Settings.php
Labels: Dev Review Done

#1598 Enhance/prevent load of unnecessary scripts styles
  assets/src/less/store.less
  includes/Assets.php
  includes/Vendor/Vendor.php
Labels: QA approved, Dev Review Done

#1650 fix left menu not shown
  includes/template-tags.php
Labels: QA approved, Dev Review Done

#1651 Fix/account type field is missing for vendors created by admin
  includes/Dashboard/Templates/Settings.php
  includes/Vendor/Vendor.php
  src/admin/pages/AddVendor.vue
  src/admin/pages/VendorPaymentFields.vue
  templates/settings/bank-payment-method-settings.php
Labels: QA approved, Dev Review Done

#1658 Enhance/several payment enhancements
  includes/Vendor/SetupWizard.php
  includes/Withdraw/functions.php
Labels: QA approved, Dev Review Done

#1661 fix: fixed order default order by parameter
  includes/Order/Manager.php
  templates/dashboard/products-widget.php
Labels: QA approved, Dev Review Done, urgent

#1664 fix: Changing withdraw method doesn't always show Withdraw Method Changed Modal window
  src/admin/pages/Settings.vue
Labels: QA approved, Dev Review Done

#1665 fix: Single store page default order by filtering wasn't working
  includes/Product/functions.php
  includes/Rewrites.php
Labels: QA approved, Dev Review Done

#1666 update: Changed Dokan Newsletter Subscription form to weMail
  src/admin/pages/Dashboard.vue
Labels: Dev Review Done
