Repository getdokan/dokan, pull requests merged in 2022-01, with the labels that each got.

#1482 fix: date range picker broken layout issue on storefront theme
  includes/ThemeSupport/Storefront.php
Labels: Need Dev Review Only

#1468 fix/css class added for styling order details page
  assets/src/less/orders.less
  templates/orders/details.php
Labels: QA approved, Dev Review Done

#1458 Item meta is not being deleted
  includes/Commission.php
Labels: QA approved, Dev Review Done

#1456 Showing Vendor or Store Name on the order details page of WooCommerce
  includes/Order/Hooks.php
Labels: QA approved, Dev Review Done

#1474 fix/conflict with siteground optimier plugin
  includes/Vendor/SetupWizard.php
Labels: Needs Testing, Needs Dev Review

#1492 enhance: localization support to date range picker button labels
  includes/Assets.php
Labels: Dev Review Done, Need Dev Review Only, Dependency With Pro

#1473 new: added dokan_get_date_range_picker_date_format() function to the helper.js file
  assets/src/js/helper.js
Labels: Dev Review Done, Need Dev Review Only, Dependency With Pro

#1463 update/fontawesome library from V4.7 to version V5.15.4
  assets/font/flaticon.css
  assets/src/less/general.less
  assets/src/less/products.less
  assets/src/less/store-lists.less
  assets/vendors/font-awesome/font-awesome.min.css
  assets/vendors/font-awesome/webfonts/fa-brands-400.eot
  assets/vendors/font-awesome/webfonts/fa-brands-400.svg
  assets/vendors/font-awesome/webfonts/fa-brands-400.ttf
  assets/vendors/font-awesome/webfonts/fa-brands-400.woff
  assets/vendors/font-awesome/webfonts/fa-brands-400.woff2
  assets/vendors/font-awesome/webfonts/fa-regular-400.eot
  assets/vendors/font-awesome/webfonts/fa-regular-400.svg
  assets/vendors/font-awesome/webfonts/fa-regular-400.ttf
  assets/vendors/font-awesome/webfonts/fa-regular-400.woff
  assets/vendors/font-awesome/webfonts/fa-regular-400.woff2
  assets/vendors/font-awesome/webfonts/fa-solid-900.eot
  assets/vendors/font-awesome/webfonts/fa-solid-900.svg
  assets/vendors/font-awesome/webfonts/fa-solid-900.ttf
  assets/vendors/font-awesome/webfonts/fa-solid-900.woff
  assets/vendors/font-awesome/webfonts/fa-solid-900.woff2
  assets/vendors/fonts/FontAwesome.otf
  assets/vendors/fonts/fontawesome-webfont.eot
  assets/vendors/fonts/fontawesome-webfont.svg
  assets/vendors/fonts/fontawesome-webfont.ttf
  assets/vendors/fonts/fontawesome-webfont.woff
  assets/vendors/fonts/fontawesome-webfont.woff2
  includes/Product/functions.php
  includes/ThemeSupport/Storefront.php
  includes/Walkers/Category.php
  includes/Walkers/StoreCategory.php
  includes/functions.php
  includes/template-tags.php
  templates/dashboard/orders-widget.php
  templates/dashboard/products-widget.php
  templates/dashboard/sales-chart-widget.php
  templates/global/header-menu.php
  templates/login-form/login-form.php
  templates/orders/listing.php
  templates/products/download-virtual.php
  templates/products/downloadable.php
  templates/products/inventory.php
  templates/products/new-product-single.php
  templates/products/new-product.php
  templates/products/others.php
  templates/products/products-listing.php
  templates/products/tmpl-add-product-popup.php
  templates/settings/store-form.php
  templates/store-header.php
  templates/store-lists-loop.php
Labels: QA approved, Dev Review Done, urgent

#1477 new: added dokan_handle_recaptcha_validation() function to the global functions.php file
  includes/Admin/Settings.php
  includes/Ajax.php
  includes/functions.php
Labels: Dev Review Done, Need Dev Review Only, Dependency With Pro

#1472 Upgrade to PRO popup new design
  src/admin/components/ModuleUpgradePopup.vue
  src/admin/components/Switches.vue
Labels: QA approved, Dev Review Done

#1515 Make Hello text translatable.
  templates/emails/product-published.php
Labels: QA approved, Dev Review Done

#1507 Fix db error while pay by dokan stripe connect.
  includes/Upgrade/Upgrades.php
  includes/Upgrade/Upgrades/V_3_3_7.php
  includes/Withdraw/Manager.php
Labels: QA approved, Dev Review Done, urgent

#1504 Update: Compatibility with latest release of Rank Math SEO
  templates/products/new-product-single.php
Labels: QA approved, Dev Review Done, Dependency With Pro

#1499 Fix: handle store not found exception
  includes/Rewrites.php
Labels: QA approved, Dev Review Done

#1491 fix/product status becomes out of stock on variation product
  includes/functions-compatibility.php
Labels: QA approved, Dev Review Done

#1487 Added per_page and page param support on store products rest api
  includes/REST/StoreController.php
Labels: QA approved, Dev Review Done

#1484 Added custom withdraw method option
  includes/Withdraw/Manager.php
  includes/Withdraw/functions.php
  src/admin/components/Fields.vue
  src/admin/pages/Withdraw.vue
  templates/settings/payment.php
  templates/withdraw/approved-request-listing.php
  templates/withdraw/cancelled-request-listing.php
  templates/withdraw/pending-request-listing.php
Labels: QA approved, Dev Review Done, Dependency With Pro

#1479 Fix chart js conflict issue
  assets/src/less/global-admin.less
  assets/vendors/chart/Chart.min.js
  includes/Admin/Notices/Helper.php
  includes/Admin/Notices/LimitedTimePromotion.php
  includes/Admin/Notices/Manager.php
  includes/Assets.php
  src/admin/components/AdminNotice.vue
  src/admin/components/UpgradeBanner.vue
  templates/admin-notice-dependencies.php
  templates/limited-time-promo-notice.php
Labels: QA approved, Dev Review Done, urgent

#1469 fix: prevent recursion while loading template if $name param is not empty
  includes/functions.php
Labels: QA approved, Dev Review Done

#1457 variation virtual product auto checked fixed
  includes/Dashboard/Templates/Products.php
Labels: QA approved, Dev Review Done, Dependency With Pro

#1447 feat: featured, latest, best selling, top rated product sections added to the store page
  dokan.php
  includes/Customizer.php
  includes/ProductSections/AbstractProductSection.php
  includes/ProductSections/BestSelling.php
  includes/ProductSections/Featured.php
  includes/ProductSections/Latest.php
  includes/ProductSections/Manager.php
  includes/ProductSections/TopRated.php
  includes/functions.php
  templates/settings/store-form.php
  templates/store-products-section.php
Labels: QA approved, Dev Review Done, urgent

#1370 feat : automatic withdrawal disbursement
  assets/images/withdraw-methods/bank.svg
  assets/images/withdraw-methods/mangopay.svg
  assets/images/withdraw-methods/paypal.svg
  assets/images/withdraw-methods/razorpay.svg
  assets/images/withdraw-methods/skrill.svg
  assets/images/withdraw-methods/stripe.svg
  assets/images/withdraw-methods/wirecard.svg
  assets/src/js/withdraw.js
  assets/src/less/withdraw.less
  includes/Dashboard/Templates/Withdraw.php
  includes/Rewrites.php
  includes/Withdraw/Hooks.php
  includes/Withdraw/Manager.php
  includes/Withdraw/functions.php
  includes/functions.php
  src/admin/components/Fields.vue
  src/admin/pages/Settings.vue
  templates/withdraw/pending-request-listing-dashboard.php
  templates/withdraw/pending-request-listing.php
  templates/withdraw/request-form.php
  templates/withdraw/status-listing.php
  templates/withdraw/tmpl-withdraw-request-popup.php
  templates/withdraw/withdraw-dashboard.php
Labels: Feature, QA approved, Dev Review Done

#1386 fix: set & update store open close time in a specific format & store open close settings make extendable for pro.
  includes/Dashboard/Templates/Settings.php
  includes/functions.php
  templates/settings/store-form.php
  templates/settings/store-time.php
Labels: QA approved, Dev Review Done, Dependency With Pro

#1466 fix: delivery-time-box-styles-broken-in-divi-theme
  assets/src/js/helper.js
  includes/Assets.php
  includes/ThemeSupport/Divi.php
Labels: QA approved, Dev Review Done, Dependency With Pro

#1512 enhance/geocoding/reverse-geocoding-when-dragging-marker-in-map
  templates/maps/google-maps-with-search.php
Labels: Enhancement, QA approved, Dev Review Done, [Vendor Dashboard], [Geolocation]

#1485 fix select2 container, select2 section single height 33 to 33px
  assets/vendors/select2/select2.css
Labels: Dev Review Done, Need Dev Review Only

#1500 content and link update of readme.txt
  readme.txt
Labels: Dev Review Done

#1522 fix: exclude dokan razorpay mangopay from withdraw method list
  assets/images/withdraw-methods/mangopay.svg
  assets/images/withdraw-methods/razorpay.svg
  assets/images/withdraw-methods/stripe.svg
  assets/images/withdraw-methods/wirecard.svg
  includes/Withdraw/functions.php
Labels: Enhancement
