Repository getdokan/dokan, pull requests merged in 2022-03, with the labels that each got.

#1533 New modules description.
  readme.txt
Labels: Need Dev Review Only

#1450 Enhance/stop loading unnecessary styles and scripts
  includes/Assets.php
Labels: QA approved, Dev Review Done, urgent

#1545 fix/starting-day-does-not-show-correctly-in-support-ticket
  includes/Assets.php
Labels: QA approved, Dev Review Done

#1551 fix: Dokan Lite is conflicting with WP Project Manager. fixes #1546
  includes/Admin/Notices/Helper.php
  includes/Assets.php
  includes/REST/AdminNoticeController.php
  package.json
  src/admin/components/AdminNotice.vue
  src/notice/App.vue
  src/notice/main.js
  src/promo-notice/main.js
  webpack.config.js
Labels: QA approved, Dev Review Done, urgent

#1552 fix: Store Product Per Page is unable to save the value. After refresh, the value disappears from the Vendor Dashboard
  templates/settings/store-form.php
Labels: QA approved, Dev Review Done, urgent

#1553 fix: Variable product's stock is not updated by quick edit from vendor dashboard
  includes/Product/Manager.php
Labels: QA approved, Dev Review Done

#1549 fix/store-times-hover-feature-not-working-for-specific-templates
  assets/src/less/store.less
Labels: Needs Dev Review, QA In Progress

#1543 ci: added pull request guideline as template
  .github/pull_request_template.md
Labels: Need Dev Review Only

#1540 enhance/upgrade jquery form validate library
  assets/vendors/form-validate/form-validate.js
  assets/vendors/form-validate/form-validate.min.js
Labels: QA approved, Dev Review Done

#1559 enhance/delivery-time-week-starts-day-settings
  includes/Assets.php
Labels: QA approved, Needs Dev Review

#1568 fixed popup error in request withdraw popup in vendor dashboard
  includes/Assets.php
Labels: QA approved, Dev Review Done, urgent

#1572 chore: `DOKAN_SINCE` version replace command `npm run version` added
  Gruntfile.js
  bin/version-replace.js
  includes/Ajax.php
  includes/Order/Hooks.php
  package.json
Labels: Needs Testing, Needs Dev Review

#1569 fixed inconsistent UI for product with status 'pending review' between dokan pro and lite version
  assets/src/less/mixins.less
Labels: QA approved, Dev Review Done
