Repository getdokan/dokan, pull requests merged in 2022-09, with the labels that each got.

#1679 fix/css-issue-of-select-option
  assets/vendors/select2/select2.css
Labels: QA approved, Dev Review Done

#1684 fix/some css issues
  assets/font/flaticon.css
  assets/src/less/form.less
  assets/src/less/store.less
  templates/orders/listing.php
  templates/products/products-listing-row.php
Labels: QA approved, Dev Review Done

#1687 Fix multiple sub-category unassigns by dokan if in the same parent
  includes/ProductCategory/Helper.php
Labels: QA approved, Dev Review Done

#1688 Add dokan_selected_multistep_category hook in product-category-ui.js
  assets/src/js/product-category-ui.js
Labels: Dev Review Done, Need Dev Review Only

#1689 fix/firefox key tap isuue for plus minus
  templates/settings/store-form.php
Labels: QA approved, Dev Review Done

#1691 Fix magnify popup style broken in SPMV search result page
  includes/Assets.php
  includes/ProductCategory/Helper.php
Labels: QA approved, Dev Review Done

#1675 Bank withdrawal information update require fields and labels.
  includes/Dashboard/Templates/Settings.php
  includes/Withdraw/functions.php
  templates/settings/bank-payment-method-settings.php
Labels: QA approved, Dev Review Done

#1693 Fix and update category commission for multistep category
  includes/Commission.php
  includes/ProductCategory/Helper.php
Labels: QA approved, Dev Review Done, urgent

#1701 Enhancement: Dokan pop up library replaced with iziModal
  assets/css/style.css
  assets/js/dokan.js
  assets/js/login-form-popup.js
  assets/src/js/login-form-popup.js
  assets/src/js/product-editor.js
  assets/src/js/withdraw.js
  assets/src/less/popup.less
  assets/vendors/izimodal/iziModal.min.css
  assets/vendors/izimodal/iziModal.min.js
  assets/vendors/magnific/jquery.magnific-popup.min.js
  assets/vendors/magnific/magnific-popup.css
  includes/Ajax.php
  includes/Assets.php
  includes/functions.php
  templates/login-form/login-form.php
  templates/products/products-listing.php
  templates/products/tmpl-add-product-popup.php
  templates/withdraw/header.php
  templates/withdraw/tmpl-withdraw-request-popup.php
Labels: Needs Testing, Needs Dev Review, Dependency With Pro

#1705 Fix subscription product category restriction bug.
  includes/ProductCategory/Categories.php
Labels: Needs Testing, Needs Dev Review

#1707 Fix payment disconnect
  assets/src/js/script.js
  includes/Dashboard/Templates/Settings.php
  includes/Withdraw/functions.php
  templates/settings/bank-payment-method-settings.php
Labels: Needs Dev Review
