Repository getdokan/dokan, pull requests merged in 2022-02, with the labels that each got.

#1525 fix: Fixed dokan popup enqueuing issue while wc vendor setup wizard.
  includes/Admin/SetupWizard.php
Labels: Need Dev Review Only

#1535 enhance/mutiple-store-times-for-store-widget
  includes/Dashboard/Templates/Settings.php
  includes/Upgrade/Upgrades.php
  includes/Upgrade/Upgrades/BackgroundProcesses/V_3_3_8_VendorStoreTimes.php
  includes/Upgrade/Upgrades/V_3_3_8.php
  includes/Widgets/StoreOpenClose.php
  includes/functions.php
  templates/widgets/store-open-close.php
Labels: QA approved, Needs Dev Review, urgent

#1505 Customizer settings added for default order by filter in store list page.
  includes/Customizer.php
  includes/Vendor/StoreListsFilter.php
  templates/store-lists-filter.php
Labels: QA approved, Dev Review Done

#1506 Enha: Added seller info on product single page
  assets/src/less/products.less
  assets/src/less/store.less
  includes/Product/Hooks.php
  includes/Product/VendorStoreInfo.php
  templates/store-header.php
  templates/store-lists-loop.php
  templates/vendor-store-info.php
Labels: QA approved, Dev Review Done

#1514 added post_date_gmt and post_modified_gmt manually as they were not set automatically
  includes/Dashboard/Templates/Products.php
Labels: QA approved, Dev Review Done, [Products]

#1517 enhance/display-store-times-in-vendor-store-page
  assets/src/less/store.less
  templates/store-header.php
Labels: QA approved, Dev Review Done

#1539 enhance/made_dokan_vendor_profile_progress_bar_closable
  assets/src/js/script.js
Labels: QA approved

#1413 new: `dokan_new_product_before_product_area` action hook introduced
  templates/products/new-product.php
  templates/products/tmpl-add-product-popup.php
Labels: Dev Review Done, Need Dev Review Only

#1441 fix(Order): create order API with coupon lines
  includes/Order/Hooks.php
Labels: Needs Testing, Dev Review Done
