Repository getdokan/dokan, pull requests merged in 2022-04, with the labels that each got.

#1589 update: sales overview chart data population and order download endpoint
  dokan.php
  includes/REST/Manager.php
  includes/REST/OrderControllerV2.php
  includes/REST/VendorDashboardController.php
  includes/reports.php
Labels: REST API

#1478 enhance/added-vendor-residence-proof-for-verify
  templates/settings/address-form.php
Labels: QA approved, Dev Review Done, Dependency With Pro

#1541 fix/used-for-variation-is-shown-for-new-attribute-even-if-product-type-is-not-variable
  assets/src/js/product-editor.js
Labels: QA approved, Dev Review Done, Dokan Pro

#1580 enhance/external-product-can't-managed-inventory-options
  assets/src/js/product-editor.js
Labels: QA approved, Dev Review Done

#1585 update readme text
  readme.txt
Labels: QA approved

#1586 Fix/StoreList > Orberby inconsistency
  includes/Vendor/Manager.php
  includes/Vendor/StoreListsFilter.php
  src/admin/pages/Vendors.vue
Labels: QA approved, Dev Review Done

#1602 Fix/contact form widget ajax problem
  assets/src/js/script.js
Labels: QA approved, Dev Review Done, urgent

#1600 fix New Order email send to admin even if this email is not enabled in WC settings
  includes/Emails/VendorCompletedOrder.php
  includes/Emails/VendorNewOrder.php
Labels: QA approved, Dev Review Done, urgent

#1365 Enhance vendor dashboard payment settings
  assets/images/withdraw-methods/bank-check.png
  assets/src/less/dashboard.less
  includes/Assets.php
  includes/Dashboard/Templates/Settings.php
  includes/Withdraw/functions.php
  templates/settings/bank-payment-method-settings.php
  templates/settings/payment-manage.php
  templates/settings/payment.php
Labels: QA approved, Dev Review Done

#1604 Fix/payment settings page quick
  assets/src/less/dashboard.less
  includes/Dashboard/Templates/Settings.php
  templates/settings/payment.php
Labels: Needs Testing, Needs Dev Review
