Repository getdokan/dokan, pull requests merged in 2023-12, with the labels that each got.

#1981 PHP 8.2 Compatibility
  includes/Vendor/Vendor.php
Labels: QA approved, Dev Review Done, Dependency With Pro, urgent

#2089 fix: Vendor class `shop_data` persistence is broken on `save()`
  includes/Vendor/Vendor.php
  tests/Vendor/UserToVendorTest.php
Labels: QA approved, Dev Review Done

#2092 [WooCommerceSubscription] Fixed a fatal error while trying to edit a subscription
  includes/Order/functions.php
Labels: QA approved, Dev Review Done

#2105 Fix, returns empty orders list in dokan rest api.
  includes/REST/OrderController.php
Labels: Needs: Testing, Dev Review Done
