Repository getdokan/dokan, pull requests merged in 2023-08, with the labels that each got.

#1947 feat: admin settings design update
  src/admin/components/Fields.vue
  src/admin/components/SecretInput.vue
  src/admin/pages/Settings.vue
Labels: QA approved, Dev Review Done, UX

#1833 Refactor: High Performance Order Storage
  assets/css/style.css
  assets/css/vue-admin.css
  assets/js/vue-admin.js
  assets/src/less/dashboard.less
  composer.json
  dokan.php
  includes/Admin/Hooks.php
  includes/Admin/Settings.php
  includes/Admin/functions.php
  includes/Assets.php
  includes/Commission.php
  includes/Core.php
  includes/Dashboard/Templates/Orders.php
  includes/DummyData/Importer.php
  includes/FakeMailer.php
  includes/Order/Admin/Hooks.php
  includes/Order/Admin/Permissions.php
  includes/Order/Controller.php
  includes/Order/EmailHooks.php
  includes/Order/Frontend/Hooks.php
  includes/Order/Hooks.php
  includes/Order/Manager.php
  includes/Order/MiscHooks.php
  includes/Order/OrderCache.php
  includes/Order/functions.php
  includes/ProductCategory/ProductCategoryCache.php
  includes/REST/OrderController.php
  includes/REST/StoreController.php
  includes/Tracker.php
  includes/Upgrade/Upgrades/V_1_2.php
  includes/Utilities/OrderUtil.php
  includes/Vendor/Vendor.php
  includes/functions-compatibility.php
  includes/functions-rest-api.php
  includes/functions.php
  includes/wc-functions.php
  includes/wc-legacy-functions.php
  includes/wc-template.php
  src/admin/pages/Vendors.vue
  templates/my-orders.php
  templates/orders/details.php
  templates/orders/listing.php
  templates/sub-orders.php
Labels: QA approved, Dev Review Done

#1944 📍 fix: Console warning from Google Map on backend and frontend
  includes/Assets.php
Labels: QA approved, Dev Review Done

#1946 login form closing class name mismatch
  assets/src/js/login-form-popup.js
Labels: QA approved, Dev Review Done

#1982 [ReverseWithdrawal] Vendor/Admin cannot pay for reverse withdrawal balance
  includes/ReverseWithdrawal/Helper.php
  includes/ReverseWithdrawal/Hooks.php
Labels: QA approved, Dev Review Done

#1930 Several product enhancements.
  includes/Blocks/ProductBlock.php
  includes/Product/Hooks.php
  includes/functions.php
  templates/products/listing-filter.php
  templates/products/others.php
Labels: Needs Testing, Dev Review Done, Dependency With Pro

#1915 feat: one step product creation
  assets/src/js/product-editor.js
  includes/Admin/Settings.php
  includes/Dashboard/Templates/Products.php
  includes/functions.php
  templates/products/edit-product-single.php
  templates/products/others.php
  templates/products/products-listing.php
Labels: Needs Testing, Dev Review Done, [Products]
