Repository getdokan/dokan, pull requests merged in 2023-01, with the labels that each got.

#1777 Fix/multiple issues
  assets/src/less/store-lists.less
  includes/template-tags.php
  templates/store-header.php
Labels: Needs Testing, Needs Dev Review

#1752 Enhancement: New REST API Support for dokan-vendor-dashboard
  dokan.php
  includes/Blocks/ProductBlock.php
  includes/Dashboard/Templates/Orders.php
  includes/Order/Manager.php
  includes/Product/ProductAttribute.php
  includes/REST/Manager.php
  includes/REST/OrderController.php
  includes/REST/OrderControllerV2.php
  includes/REST/ProductAttributeController.php
  includes/REST/ProductBlockController.php
  includes/REST/ProductController.php
  includes/REST/StoreSettingControllerV2.php
  includes/REST/VendorDashboardController.php
  includes/REST/WithdrawController.php
  includes/REST/WithdrawControllerV2.php
  includes/Vendor/Hooks.php
  includes/Vendor/SettingsApi/Abstracts/Gateways.php
  includes/Vendor/SettingsApi/Abstracts/Page.php
  includes/Vendor/SettingsApi/Manager.php
  includes/Vendor/SettingsApi/Processor.php
  includes/Vendor/SettingsApi/Settings/Pages/Payments/Gateways/Bank.php
  includes/Vendor/SettingsApi/Settings/Pages/Payments/Gateways/PayPal.php
  includes/Vendor/SettingsApi/Settings/Pages/Payments/Payments.php
  includes/Vendor/SettingsApi/Settings/Pages/Store.php
  includes/Vendor/Vendor.php
  includes/Withdraw/Manager.php
  includes/Withdraw/functions.php
  includes/functions.php
  includes/reports.php
  includes/template-tags.php
  includes/wc-functions.php
Labels: QA approved, Dev Review Done

#1780 Product filter support for vendor dashboard API
  includes/REST/Manager.php
  includes/REST/ProductControllerV2.php
  includes/functions.php
Labels: QA approved, Dev Review Done

#1786 fix: Wrong placement of product category selection modal on vendor dashboard
  includes/Dashboard/Templates/MultiStepCategories.php
Labels: QA approved, Dev Review Done, [Vendor Dashboard]

#1787 refactor: dokan_get_seller_id_by_order function
  includes/Order/functions.php
Labels: Need Dev Review Only

#1788 ⚙️ Feat: Vendor dashboard ui activation setting
  includes/REST/VendorDashboardController.php
Labels: Need Dev Review Only

#1783 enhance: Background processor for rebuilding variable products author IDs
  dokan.php
  includes/BackgroundProcess/Manager.php
  includes/BackgroundProcess/RewriteVariableProductsAuthor.php
  includes/Upgrade/Upgrades.php
  includes/Upgrade/Upgrades/V_3_7_10.php
Labels: QA approved, Dev Review Done, Dependency With Pro, urgent
