Repository getdokan/dokan, pull requests merged in 2023-10, with the labels that each got.

#2007 🎯 fix: Shipment button and form still available on vendor dashboard single order page if shipment creation enabled
  templates/orders/details.php
Labels: QA approved, Dev Review Done

#2023 Pull request template updated.
  .github/pull_request_template.md
Labels: QA approved, Dev Review Done

#2031 🪝 new: Filter hook to the store URL getter method
  includes/functions.php
Labels: QA approved, Dev Review Done, Need Dev Review Only, urgent

#2033 Fix: Dokan Filter Products by Attribute Widget Not Working for Multi-Word Attributes.
  includes/Rewrites.php
Labels: QA approved, Dev Review Done

#1941 🚀 enhance: Simplify vendor dashboard settings
  includes/Admin/Settings.php
  includes/Dashboard/Templates/Settings.php
  includes/Product/VendorStoreInfo.php
  includes/ProductSections/AbstractProductSection.php
  includes/ProductSections/Manager.php
  includes/Rewrites.php
  includes/Vendor/Manager.php
  includes/Vendor/SettingsApi/Settings/Pages/Store.php
  includes/Vendor/SetupWizard.php
  includes/Vendor/Vendor.php
  includes/wc-functions.php
  includes/wc-template.php
  templates/settings/store-form.php
Labels: QA approved, Dev Review Done, Dependency With Pro, Needs: Discussion

#2040 🚀 enhance: Positioning of additional product sections and product filtering
  includes/Product/Hooks.php
  includes/ProductSections/Manager.php
Labels: Need Dev Review Only, urgent

#1963 Replace flaticons with font awesome icons.
  assets/font/flaticon/Flaticon.eot
  assets/font/flaticon/Flaticon.svg
  assets/font/flaticon/Flaticon.ttf
  assets/font/flaticon/Flaticon.woff
  assets/font/flaticon/flaticon.css
  assets/src/js/helper.js
  includes/Assets.php
  includes/REST/StoreSettingController.php
Labels: QA approved, Dependency With Pro

#1874 ⚡️Add: fontawesome library setting
  includes/Admin/Settings.php
  includes/Admin/SetupWizard.php
  includes/Assets.php
Labels: QA approved, Dev Review Done

#1888 🛠️Change date picker
  assets/src/js/dokan-daterangepicker.js
  assets/src/js/reverse-withdrawal.js
  src/admin/pages/ReverseWithdrawal.vue
  src/admin/pages/ReverseWithdrawalTransactions.vue
  src/utils/Mixin.js
  templates/orders/date-export.php
  templates/orders/listing.php
  templates/reverse-withdrawal/filters.php
  webpack.config.js
Labels: QA approved, Dev Review Done, Dependency With Pro

#2024 🎯 fix: Invalid store opening or closing times generate warning and fatal error on single store pages
  templates/store-header-times.php
Labels: QA approved, Dev Review Done, urgent

#2034 🎯 fix: Product edit link on email template redirects to the products listing instead of single product edit page
  includes/Dashboard/Templates/Products.php
  includes/Emails/ProductPublished.php
  includes/functions.php
Labels: QA approved, Dev Review Done

#2035 📱 fix: Mobile responsive issues of vendor dashboard products listing page
  assets/src/less/responsive.less
  templates/products/products-listing.php
Labels: QA approved, Dev Review Done

#2036 Fix: withdraw page mobile responsive
  assets/src/less/withdraw.less
Labels: QA approved, Dev Review Done
