Repository getdokan/dokan, pull requests merged in 2023-11, with the labels that each got.

#2076 🐛 fix(OrderController.php): add get_item method to retrieve order details by ID
  includes/REST/OrderController.php
Labels: QA approved, Dev Review Done

#2071 New: Product Review Email Template For Vendors
  includes/Emails/Manager.php
  includes/Emails/VendorProductReview.php
  includes/Product/Hooks.php
  templates/emails/plain/vendor-product-review.php
  templates/emails/vendor-product-review.php
Labels: QA approved, Dev Review Done, urgent

#2070 update: display Not purchasable notice for own product
  includes/Product/Hooks.php
Labels: QA approved, Dev Review Done, [Products]

#2051 Select All attribute not working issue fix.
  assets/src/js/product-editor.js
Labels: QA approved, Dev Review Done

#1989 Short form of days added for delivery time module
  includes/functions.php
Labels: QA approved, Dev Review Done

#2022 Successful product duplication message added
  includes/template-tags.php
Labels: QA approved, Dev Review Done

#2072 fix: Regenerate button typo
  src/admin/components/PasswordGenerator.vue
Labels: QA approved, Dev Review Done

#2073 update: Remove minimum input length restriction on Tag field
  assets/src/js/product-editor.js
Labels: QA approved, Dev Review Done, [Products]

#2090 update: update test suite for WooCommerce 8.3 Cart and Checkout Blocks
  tests/pw/pages/announcementsPage.ts
  tests/pw/pages/customerPage.ts
  tests/pw/pages/proPromoPage.ts
  tests/pw/pages/selectors.ts
  tests/pw/tests/api/announcements.spec.ts
  tests/pw/tests/api/rankMath.spec.ts
  tests/pw/tests/api/withdraws.spec.ts
  tests/pw/tests/e2e/_auth.setup.spec.ts
  tests/pw/tests/e2e/announcements.spec.ts
  tests/pw/utils/apiEndPoints.ts
  tests/pw/utils/dbData.ts
  tests/pw/utils/payloads.ts
  tests/pw/utils/testData.ts
Labels: Needs: Dev Review
