Repository getdokan/dokan, pull requests merged in 2023-04, with the labels that each got.

#1840 fix: Product status not updating on selling option changing from vendor edit admin dashboard
  includes/Vendor/Manager.php
Labels: QA approved, Dev Review Done, [Products]

#1841 🛠️Fix: vendor dashboard report data error
  includes/REST/VendorDashboardController.php
Labels: QA approved, Dev Review Done

#1842 Api/reverse withdrawal
  includes/REST/ReverseWithdrawalController.php
  includes/ReverseWithdrawal/Ajax.php
  includes/ReverseWithdrawal/Helper.php
  src/admin/pages/ReverseWithdrawal.vue
  src/admin/pages/ReverseWithdrawalTransactions.vue
Labels: QA approved, Dev Review Done

#1845 🪲 fix: Wrong product counts on vendor dashboard product listings
  includes/functions.php
Labels: QA approved, Dev Review Done

#1851 🚀 enhance: Allow only image format files as product featured and gallery images on vendor dashboard
  assets/src/js/product-editor.js
Labels: QA approved, Dev Review Done

#1836 ⚡️ Multistep categroy support in product api
  includes/Abstracts/DokanRESTController.php
  includes/ProductCategory/Helper.php
  includes/REST/ProductBlockController.php
  includes/REST/ProductControllerV2.php
Labels: QA approved, Dev Review Done

#1850 🚀 enhance: Allow countries in location selectors based on admin allowed countries in WooCommerce settings
  includes/Vendor/SetupWizard.php
Labels: QA approved, Dev Review Done

#1852 🔩 fix: Console error on uploading non-image file to product gallery
  assets/src/js/product-editor.js
Labels: QA approved, Dev Review Done

#1853 fix: Order invoice and packaging slip broken css
  assets/src/less/orders.less
Labels: QA approved, Dev Review Done

#1855 🔨 fix: Customers are unable to register on some themes and console error on the My Account page
  assets/js/vendor-registration.js
Labels: QA approved, Dev Review Done

#1856 fix: Extra space propagation issue on from validation
  assets/src/js/script.js
Labels: QA approved, Dev Review Done

#1857 Fix tinymc editor and seach box overlap
  src/admin/components/TextEditor.vue
  src/admin/pages/Settings.vue
Labels: QA approved, Dev Review Done

#1860 fix: Astra theme support css relocation
  includes/ThemeSupport/Astra.php
Labels: Needs Testing, Dev Review Done

#1870 fix: Vendor analytics admin settings Google sign-in button broken style
  src/admin/components/Fields.vue
Labels: QA approved, Dev Review Done
