Repository getdokan/dokan, pull requests merged in 2023-06, with the labels that each got.

#1903 🐛 Fix: dummy data serialize security issue
  assets/dummy-data/dokan_dummy_data.csv
  includes/DummyData/Importer.php
Labels: Needs Testing, Dev Review Done

#1900 Dokan vendor dashboard detection inside product loop
  includes/functions.php
Labels: QA approved, Dev Review Done

#1897 fix: Custom Withdrawal method enabling and display conditional restriction
  includes/Admin/SetupWizard.php
Labels: QA approved, Dev Review Done

#1898 🚀 enhance: Access to store listings via direct URL based on store categories filtering
  includes/Shortcodes/Stores.php
Labels: QA approved, Dev Review Done

#1899 ✍️Fix: store page pagination
  includes/template-tags.php
Labels: QA approved, Dev Review Done

#1901 🎨 fix: Styling issue of discounted price input section in vendor dashboard product adding page
  assets/src/less/products.less
Labels: QA approved, Dev Review Done

#1896 Enhance/replace webpack to wpscripts
  .babelrc
  .prettierrc
  .prettierrc.js
  .travis.yml
  Gruntfile.js
  assets/css/dokan-admin-product.css
  assets/css/dokan-admin-product.css.map
  assets/css/reverse-withdrawal.css
  assets/css/setup-no-wc.css
  assets/css/style.css.map
  assets/css/vue-admin.css.map
  assets/css/vue-bootstrap.css.map
  assets/css/vue-frontend.css.map
  assets/css/vue-vendor.css.map
  assets/js/dokan-admin-notice.js
  assets/js/dokan-admin-notice.min.js
  assets/js/dokan-admin-product.min.js
  assets/js/dokan-promo-notice.min.js
  assets/js/dokan-wp.js
  assets/js/dokan-wp.min.js
  assets/js/product-category-ui.min.js
  assets/js/reverse-withdrawal.min.js
  assets/js/vue-admin.min.js
  assets/js/vue-bootstrap.min.js
  assets/js/vue-frontend.min.js
  assets/js/vue-vendor.min.js
  assets/src/images/default-store-banner.png
  assets/src/images/loader.svg
  assets/src/images/searchicon.png
  assets/src/images/spinner-2x.gif
  assets/src/images/wpspin_light.gif
  assets/src/js/customize-controls.js
  assets/src/js/customize-preview.js
  assets/src/js/helper.js
  assets/src/js/pointers.js
  assets/src/js/script.js
  assets/src/js/vendor-address.js
  assets/src/js/vendor-registration.js
  assets/src/less/general.less
  assets/src/less/global-admin.less
  assets/src/less/mixins.less
  assets/src/less/plugin.less
  assets/src/less/setup-no-wc.less
  assets/src/less/store.less
  assets/vendors/speakingurl/speakingurl.min.js
  bin/clean-useless-files.js
  bin/zip.js
  includes/Abstracts/DokanRESTController.php
  includes/Admin/SetupWizard.php
  includes/Admin/SetupWizardNoWC.php
  includes/Assets.php
  includes/Vendor/SettingsApi/Settings/Pages/Store.php
  includes/functions.php
  languages/dokan-lite.php
  package-lock.json
  package.json
  src/utils/Bootstrap.js
  src/utils/vue-vendor.js
  src/wp-packages/index.js
  webpack.config.js
Labels: QA approved

#1919 Add: developer guid for dokan lite
  DEVELOPER.md
  bin/clean-useless-files.js
Labels: Need Dev Review Only

#1906 Update readme.txt
  readme.txt
Labels: Dev Review Done

#1921 Update: package.lock.json
  assets/font/_flaticon.scss
  assets/font/falticon/Flaticon.eot
  assets/font/falticon/Flaticon.svg
  assets/font/falticon/Flaticon.ttf
  assets/font/falticon/Flaticon.woff
  assets/font/falticon/flaticon.css
  assets/font/flaticon.html
  assets/font/sf-pro-text/sf-pro-text.css
  assets/src/less/global-admin.less
  includes/Assets.php
  package-lock.json
Labels: Need Dev Review Only

#1905 🚀 feat(Commission.php): add support for PayPal Payments gateway and capture event to calculate gateway fee
  includes/Commission.php
Labels: QA approved, Dev Review Done

#1907 🚀 enhance: 'Become a Vendor' option for customers
  assets/src/less/frontend.less
  assets/src/less/style.less
  dokan.php
  includes/Frontend/Frontend.php
  includes/Frontend/MyAccount/BecomeAVendor.php
  includes/Rewrites.php
  includes/Traits/ChainableContainer.php
  includes/functions.php
  templates/account/become-a-vendor-section.php
  templates/account/update-customer-to-vendor.php
Labels: QA approved, Dev Review Done, Dependency With Pro

#1908 🎯 fix: Vendor dashboard mobile nav icon positioning issue and some other responsive issues
  assets/src/less/responsive.less
  assets/src/less/site-navigation.less
Labels: QA approved, Dev Review Done

#1920 update: `withdraw_limit` default changed to `0` from `-1`
  includes/Dashboard/Templates/Withdraw.php
  includes/REST/WithdrawController.php
  templates/withdraw/withdraw-dashboard.php
Labels: QA approved, Dev Review Done, urgent

#1914 Seller registration form sync
  assets/src/js/vendor-registration.js
  templates/global/seller-registration-form.php
Labels: QA approved, Dev Review Done

#1924 🗺 enhance: Store location map integration on seller setup wizard
  assets/src/less/setup.less
  includes/Vendor/SetupWizard.php
Labels: QA approved, Dev Review Done
