Repository getdokan/dokan, pull requests merged in 2023-03, with the labels that each got.

#1822 fix: sql injection on some queries.
  includes/Order/Manager.php
  includes/Withdraw/functions.php
  includes/functions.php
  includes/reports.php
  includes/wc-functions.php
  uninstall.php
Labels: Dev Review Done

#1818 update: disbursement schedule change detection and announcement sending consent
  src/admin/pages/Settings.vue
Labels: QA approved, Dev Review Done, Dokan Pro

#1828 Fix/WP Rest Server error when Dokan Lite plugin was activated
  includes/REST/ProductControllerV2.php
Labels: Dev Review Done, Need Dev Review Only

#1826 🛠 Fix: vendor state requiired
  assets/js/vendor-address.js
  includes/Assets.php
Labels: QA approved, Dev Review Done

#1821 🐛 Fix: Edit bulk product category auto select
  includes/ProductCategory/Helper.php
  templates/products/dokan-category-header-ui.php
Labels: QA approved, Dev Review Done

#1838 enhance: Store category counts improvement
  includes/functions.php
Labels: QA approved, Dev Review Done, Dependency With Pro

#1816 fix: Vendor can signup even though store URL not available warning exists
  assets/js/vendor-registration.js
  includes/Registration.php
Labels: QA approved, Dev Review Done, Registration

#1834 [RestAPIProduct] `in_stock`, `featured`, `on_sale` filter for products rest api wasn't working
  includes/REST/ProductController.php
Labels: QA approved, Needs Dev Review

#1810 Fix: get withdraw payment method title
  includes/Withdraw/functions.php
Labels: Need Dev Review Only
