Repository getdokan/dokan, pull requests merged in 2023-02, with the labels that each got.

#1792 Update: product api
  includes/Blocks/ProductBlock.php
  includes/Product/functions.php
  includes/REST/ProductBlockController.php
  includes/REST/ProductController.php
  includes/REST/ProductControllerV2.php
  includes/Vendor/SettingsApi/Settings/Pages/Store.php
Labels: Needs Dev Review, QA In Progress

#1793 fix: vendor search with store name from WC Product Edit screen
  includes/Admin/Hooks.php
Labels: QA approved, Needs Dev Review

#1790 enhance: WP dashboard order counts for vendor
  includes/Order/functions.php
  includes/wc-functions.php
Labels: Enhancement, QA approved, Dev Review Done

#1735 Feat/Address fields on the vendor registration form
  assets/js/vendor-address.js
  includes/Admin/Settings.php
  includes/Assets.php
  includes/Registration.php
  includes/Shortcodes/VendorRegistration.php
  templates/account/vendor-registration.php
  templates/global/seller-registration-form.php
  templates/settings/address-form.php
  templates/settings/store-form.php
Labels: QA approved, Dev Review Done

#1800 fix: Critical error on creating order from the admin dashboard
  includes/Commission.php
Labels: QA approved, Dev Review Done, [Orders]

#1803 update: Enable selling option from admin dashboard
  includes/Admin/Settings.php
Labels: QA approved, Dev Review Done

#1804 Fix: Dashboard API Issues
  includes/REST/VendorDashboardController.php
Labels: Needs Testing, Needs Dev Review

#1799 🪝 Enhance: Add hook to select any category
  assets/src/js/product-category-ui.js
  includes/ProductCategory/Helper.php
Labels: QA approved, Dev Review Done

#1808 enhance: Prevent vendors redirect to vendor dashboard if login from checkout page
  includes/functions.php
Labels: Enhancement, QA approved, Dev Review Done

#1813 fix: featured image could not be added on product created with `Create and add new` button
  assets/src/js/product-editor.js
Labels: QA approved, Dev Review Done, [Products]

#1815 enhance: Add sub-description to the hide vendor info section in admin appearance settings
  includes/Admin/Settings.php
Labels: Enhancement, QA approved, Dev Review Done, Need Dev Review Only

#1817 Fix product image thumbnail gets image height squeezed on add new product popup under vendor dashboard
  assets/src/less/products.less
Labels: Needs Testing, Needs Dev Review
