Repository getdokan/dokan, pull requests merged in 2023-09, with the labels that each got.

#1937 Fix: Keep the backward compatibility for dokan_withdraw_method_additional_info filter hook
  includes/Withdraw/functions.php
Labels: QA approved, Dev Review Done, Dependency With Pro

#1951 📧 fix: Amount field of new withdraw submission email template not working
  includes/Emails/VendorWithdrawRequest.php
Labels: QA approved, Dev Review Done

#1955 📅 fix: Date-range selection calendar of vendor dashboard broken on multiple themes
  assets/src/less/dashboard.less
Labels: QA approved, Dev Review Done

#1958 Fix: Invalid filter on lite and booking module
  includes/Product/Hooks.php
Labels: QA approved, Dev Review Done, Dependency With Pro

#1975 Fix: mobile menu background color
  assets/src/less/site-navigation.less
Labels: QA approved, Dev Review Done

#1977 Password field based on WooCommerce settings
  includes/template-tags.php
  templates/account/vendor-registration.php
Labels: QA approved, Dev Review Done

#1978 Enhancement hide vendor select box on subscription product
  assets/src/js/dokan-admin-product.js
  includes/Admin/Hooks.php
Labels: QA approved, Dev Review Done

#1980 update: shipping tax fee recipient setting added in admin setup wizard
  includes/Admin/SetupWizard.php
  templates/admin-setup-wizard/step-store.php
Labels: QA approved, Dev Review Done

#1990 Fix: Trying to delete all products also booking product and also trying to delete non-dummy product
  includes/DummyData/Importer.php
Labels: QA approved, Dev Review Done

#1986 Single Product Page and Product Edit Page Enhancements
  assets/src/js/product-editor.js
  includes/Admin/Notices/Manager.php
  includes/Admin/Settings.php
  includes/Blocks/ProductBlock.php
  includes/Dashboard/Templates/Products.php
  includes/Emails/Manager.php
  includes/Emails/NewProduct.php
  includes/Emails/NewProductPending.php
  includes/Product/Hooks.php
  includes/Product/functions.php
  includes/REST/ProductController.php
  includes/functions.php
  templates/products/edit-product-single.php
  templates/products/listing-filter.php
  templates/products/others.php
  templates/products/products-listing.php
Labels: QA approved, Dev Review Done, Dependency With Pro, urgent

#1998 test: Default withdrawal method ajax test
  tests/Withdrawal/MakeDefaultWithdrawalMethodTest.php
Labels: Dev Review Done, Need Dev Review Only

#1917 🔎 feat: Admin dashboard withdraw advanced filtering with log exporting
  includes/Admin/WithdrawLogExporter.php
  includes/REST/WithdrawController.php
  includes/Withdraw/Hooks.php
  includes/Withdraw/Manager.php
  includes/Withdraw/Withdraws.php
  includes/Withdraw/functions.php
  src/admin/pages/Withdraw.vue
Labels: QA approved, Dev Review Done

#1939 PDF invoice button on sub order
  includes/Order/Hooks.php
Labels: QA approved, Dev Review Done

#1961 Fix: Dummy data 502 unexpected error.
  includes/REST/DummyDataController.php
  src/admin/pages/DummyData.vue
Labels: QA approved, Dev Review Done

#1967 Fix: order refund amount tax decimal precision
  assets/src/js/orders.js
Labels: QA approved, Dev Review Done

#1969 ☎️ enhance: Backend validation of phone numbers all over the plugin
  includes/Admin/UserProfile.php
  includes/Dashboard/Templates/Settings.php
  includes/Frontend/MyAccount/BecomeAVendor.php
  includes/Registration.php
  includes/functions.php
  includes/template-tags.php
  phpcs.xml.dist
  src/admin/pages/VendorAccountFields.vue
Labels: QA approved, Dev Review Done

#1979 update: store category widget list default state set to collapse
  assets/src/js/dokan-frontend.js
  assets/src/less/frontend.less
Labels: QA approved, Dev Review Done

#1991 Dokan compatibility added.
  includes/Order/Hooks.php
Labels: QA approved, Dev Review Done, Dependency With Pro, urgent

#1997 🎨 enhance: Styling improvement all over the plugin
  assets/src/less/extra.less
  assets/src/less/setup.less
  assets/src/less/store.less
  src/admin/pages/ReverseWithdrawal.vue
  src/admin/pages/VendorAddressFields.vue
Labels: QA approved, Dev Review Done, Dependency With Pro

#2006 🎯 fix: Order status label missing on vendor dashboard for draft orders
  includes/Order/functions.php
Labels: QA approved, Dev Review Done, urgent
