Repository getdokan/dokan, pull requests merged in 2023-07, with the labels that each got.

#1858 🛠️ Fix: Several api errors
  assets/dummy-data/dokan_dummy_data.csv
  includes/REST/DummyDataController.php
  includes/REST/OrderController.php
  includes/REST/StoreController.php
  includes/REST/WithdrawController.php
  includes/ReverseWithdrawal/Manager.php
  includes/Vendor/Manager.php
  src/admin/pages/Withdraw.vue
Labels: QA approved, Dev Review Done

#1902 [Enhancement]: Adjusted the banner upload field style on store settings form
  assets/src/less/responsive.less
  assets/src/less/settings.less
  templates/settings/store-form.php
Labels: QA approved, Dev Review Done

#1911 Enhance/wp editor additional tag
  includes/Rewrites.php
  templates/products/edit-product-single.php
Labels: QA approved, Dev Review Done

#1918 update: orderby `random` added for store REST API
  includes/REST/StoreController.php
Labels: REST API, QA approved, Dev Review Done, [Store]

#1925 ☎️ enhance: Frontend validation of phone input fields all over the plugin
  assets/src/js/helper.js
  assets/src/js/vendor-registration.js
  templates/account/update-customer-to-vendor.php
  templates/settings/store-form.php
Labels: QA approved, Dev Review Done, Dependency With Pro

#1926 Enhance/several withdraw enhancements
  includes/Dashboard/Templates/Withdraw.php
  includes/Withdraw/functions.php
  includes/functions.php
  templates/withdraw/withdraw-dashboard.php
Labels: QA approved, Dev Review Done

#1933 Fix: The withdraw request could not be approved
  includes/REST/WithdrawController.php
Labels: QA approved, Needs Dev Review, urgent

#1923 Enhance/admin settings
  includes/Admin/Settings.php
  includes/functions.php
  src/admin/components/Fields.vue
  src/admin/components/SecretInput.vue
  src/admin/components/SocialFields.vue
Labels: QA approved, Dev Review Done, Dependency With Pro

#1890 Vendor own product purchase restriction added
  includes/wc-functions.php
Labels: QA approved, Dev Review Done, Dependency With Pro

#1910 Enhance cerate reverse withdraw from admin dashboard
  includes/REST/OrderController.php
  includes/REST/ReverseWithdrawalController.php
  includes/ReverseWithdrawal/Helper.php
  includes/ReverseWithdrawal/Manager.php
  src/admin/components/AddReverseWithdraw.vue
  src/admin/components/DokanRadioGroup.vue
  src/admin/pages/ReverseWithdrawal.vue
Labels: QA approved, Dev Review Done

#1935 `template` folder added to translation .pot file generator at package.json script
  package.json
Labels: QA approved, Dev Review Done
