Repository getdokan/dokan, pull requests merged in 2024-12, with the labels that each got.

#2463 Fix commission upgrader
  includes/Commission/Upugrader/Update_Category_Commission.php
  includes/Commission/Upugrader/Update_Product_Commission.php
  includes/Commission/Upugrader/Update_Vendor_Commission.php
  includes/Upgrade/AdminNotice.php
Labels: QA approved

#2457 Fix skipped product tests
  tests/pw/feature-map/feature-map.yml
  tests/pw/pages/productsPage.ts
  tests/pw/pages/selectors.ts
  tests/pw/tests/e2e/_env.setup.ts
  tests/pw/tests/e2e/products.spec.ts
  tests/pw/utils/interfaces.ts
  tests/pw/utils/testData.ts
Labels: QA approved, Test Automation

#2460 Add store list & reviews test
  tests/pw/feature-map/feature-map.yml
  tests/pw/pages/basePage.ts
  tests/pw/pages/selectors.ts
  tests/pw/pages/storeListingPage.ts
  tests/pw/pages/storeReviewsPage.ts
  tests/pw/tests/api/modules.spec.ts
  tests/pw/tests/e2e/modules.spec.ts
  tests/pw/tests/e2e/singleStore.spec.ts
  tests/pw/tests/e2e/storeReviews.spec.ts
  tests/pw/tests/e2e/storelisting.spec.ts
  tests/pw/utils/apiUtils.ts
  tests/pw/utils/interfaces.ts
  tests/pw/utils/payloads.ts
  tests/pw/utils/testData.ts
Labels: QA approved, Test Automation

#2443 update: Vendor dashboard menu override for react templates based on Template override conditions
  docs/feature-override/readme.md
  includes/Assets.php
  includes/DependencyManagement/Providers/CommonServiceProvider.php
  includes/VendorNavMenuChecker.php
  src/Dashboard/index.tsx
  src/Dashboard/tailwind.scss
  tests/php/src/VendorNavMenuCheckerTest.php
Labels: :+1: Dev Review Done

#2471 Add Commission tests
  tests/pw/feature-map/feature-map.yml
  tests/pw/pages/basePage.ts
  tests/pw/pages/commissionPage.ts
  tests/pw/pages/productsPage.ts
  tests/pw/pages/selectors.ts
  tests/pw/pages/storeSupportsPage.ts
  tests/pw/tests/e2e/commission.spec.ts
  tests/pw/utils/apiUtils.ts
  tests/pw/utils/payloads.ts
Labels: Test Automation

#2470 Add vendor coupon tests
  tests/pw/tests/api/calculation.spec.ts
Labels: QA approved, Test Automation

#2461 Enhance/plugin header section redesign
  assets/src/less/admin.less
  src/admin/pages/VendorCapabilities.vue
  templates/admin-header.php
  templates/svg-icons/pro-award.php
Labels: QA approved, :+1: Dev Review Done

#2458 Appearance settings tests
  .github/workflows/e2e_api_tests.yml
  tests/pw/.env.example
  tests/pw/README.MD
  tests/pw/e2e.config.ts
  tests/pw/feature-map/feature-map.yml
  tests/pw/fixtures/page.ts
  tests/pw/pages/basePage.ts
  tests/pw/pages/privacyPolicyPage.ts
  tests/pw/pages/selectors.ts
  tests/pw/pages/storeAppearance.ts
  tests/pw/pages/storeAppearancePage.ts
  tests/pw/tests/e2e/_auth.setup.ts
  tests/pw/tests/e2e/_env.setup.ts
  tests/pw/tests/e2e/catalogmode.spec.ts
  tests/pw/tests/e2e/commission.spec.ts
  tests/pw/tests/e2e/euCompliance.spec.ts
  tests/pw/tests/e2e/liveSearch.spec.ts
  tests/pw/tests/e2e/privacyPolicy.spec.ts
  tests/pw/tests/e2e/storeAppearance.spec.ts
  tests/pw/tests/e2e/vendor.spec.ts
  tests/pw/tests/e2e/vendorProductSubscription.spec.ts
  tests/pw/types/environment.d.ts
  tests/pw/utils/dbData.ts
  tests/pw/utils/payloads.ts
  tests/pw/utils/testData.ts
Labels: QA approved, Test Automation

#2478 Add Store appreance tests
  .github/workflows/e2e_api_tests.yml
  tests/pw/.env.example
  tests/pw/README.MD
  tests/pw/e2e.config.ts
  tests/pw/feature-map/feature-map.yml
  tests/pw/fixtures/page.ts
  tests/pw/pages/basePage.ts
  tests/pw/pages/privacyPolicyPage.ts
  tests/pw/pages/selectors.ts
  tests/pw/pages/storeAppearance.ts
  tests/pw/pages/storeAppearancePage.ts
  tests/pw/tests/e2e/_auth.setup.ts
  tests/pw/tests/e2e/_env.setup.ts
  tests/pw/tests/e2e/catalogmode.spec.ts
  tests/pw/tests/e2e/commission.spec.ts
  tests/pw/tests/e2e/euCompliance.spec.ts
  tests/pw/tests/e2e/liveSearch.spec.ts
  tests/pw/tests/e2e/privacyPolicy.spec.ts
  tests/pw/tests/e2e/storeAppearance.spec.ts
  tests/pw/tests/e2e/vendor.spec.ts
  tests/pw/tests/e2e/vendorProductSubscription.spec.ts
  tests/pw/types/environment.d.ts
  tests/pw/utils/dbData.ts
  tests/pw/utils/payloads.ts
  tests/pw/utils/testData.ts
Labels: QA approved, Test Automation

#2484 enhance: Seperate dokan rest controller for role-wise API implementation.
  docs/api/api.md
  includes/Abstracts/DokanRESTAdminController.php
  includes/Abstracts/DokanRESTBaseController.php
  includes/Abstracts/DokanRESTCustomerController.php
  includes/Abstracts/DokanRESTVendorController.php
Labels: :+1: Dev Review Done, Need Dev Review Only, urgent

#2492 enhance: Seperate dokan rest controller for role-wise API implementation.
  docs/api/api.md
  includes/Abstracts/DokanRESTAdminController.php
  includes/Abstracts/DokanRESTBaseController.php
  includes/Abstracts/DokanRESTCustomerController.php
  includes/Abstracts/DokanRESTVendorController.php
Labels: :+1: Dev Review Done, Need Dev Review Only

#2490 🎯 fix: Invalid return value for commission rate validate method
  includes/Commission.php
Labels: Needs: Testing, :+1: Dev Review Done, Upcoming Release

#2489 Fix/get earning by order string float error
  dokan-class.php
  includes/Commission.php
Labels: Need Dev Review Only, Upcoming Release

#2485 Error on approved refund request when empty Commission _dokan_additional_fee #4018
  includes/Commission/Settings/OrderItem.php
Labels: Needs: Testing, :+1: Dev Review Done, urgent, Upcoming Release
