Repository getdokan/dokan, pull requests merged in 2024-05, with the labels that each got.

#2213 Fix: Virtual Product Status in Sub-Orders
  includes/Order/Hooks.php
Labels: QA approved, :+1: Dev Review Done, Upcoming Release

#2264 Vendor can switch old and new dashboard
  templates/global/dashboard-nav.php
Labels: :+1: Dev Review Done

#2276 Modified a grammatical error.
  readme.txt
Labels: Needs: Dev Review

#2277 refactor: replaced `apply_filters` with `do_action` where necessary
  templates/store-header.php
  templates/store-lists-loop.php
  templates/vendor-store-info.php
Labels: :+1: Dev Review Done, Need Dev Review Only

#2280 add: vendor verification tests
  tests/pw/feature-map/feature-map.yml
  tests/pw/pages/basePage.ts
  tests/pw/pages/loginPage.ts
  tests/pw/pages/privacyPolicyPage.ts
  tests/pw/pages/productQAPage.ts
  tests/pw/pages/selectors.ts
  tests/pw/pages/settingsPage.ts
  tests/pw/pages/singleStorePage.ts
  tests/pw/pages/vendorDeliveryTimePage.ts
  tests/pw/pages/vendorPage.ts
  tests/pw/pages/vendorVerificationsPage.ts
  tests/pw/pages/withdrawsPage.ts
  tests/pw/tests/api/vendorSubscription.spec.ts
  tests/pw/tests/api/vendorVerification.spec.ts
  tests/pw/tests/e2e/_coverage.teardown.spec.ts
  tests/pw/tests/e2e/admin.spec.ts
  tests/pw/tests/e2e/dashboard.spec.ts
  tests/pw/tests/e2e/privacyPolicy.spec.ts
  tests/pw/tests/e2e/refunds.spec.ts
  tests/pw/tests/e2e/reports.spec.ts
  tests/pw/tests/e2e/requestForQuoteRules.spec.ts
  tests/pw/tests/e2e/reverseWithdraws.spec.ts
  tests/pw/tests/e2e/settings.spec.ts
  tests/pw/tests/e2e/stores.spec.ts
  tests/pw/tests/e2e/vendorDashboard.spec.ts
  tests/pw/tests/e2e/vendorDeliveryTime.spec.ts
  tests/pw/tests/e2e/vendorReports.spec.ts
  tests/pw/tests/e2e/vendorVerifications.spec.ts
  tests/pw/tests/e2e/withdraws.spec.ts
  tests/pw/types/environment.d.ts
  tests/pw/utils/apiEndPoints.ts
  tests/pw/utils/apiUtils.ts
  tests/pw/utils/dbUtils.ts
  tests/pw/utils/interfaces.ts
  tests/pw/utils/payloads.ts
  tests/pw/utils/schemas.ts
  tests/pw/utils/testData.ts
Labels: QA approved

#2281 refactor: change promo content
  src/admin/components/ModuleUpgradePopup.vue
  src/admin/components/UpgradeBanner.vue
Labels: QA approved, :+1: Dev Review Done, urgent, Upcoming Release

#2283 add: added color scheme tests
  tests/pw/feature-map/feature-map.yml
  tests/pw/pages/basePage.ts
  tests/pw/pages/colorsPage.ts
  tests/pw/pages/selectors.ts
  tests/pw/pages/settingsPage.ts
  tests/pw/pages/vendorSettingsPage.ts
  tests/pw/tests/e2e/colors.spec.ts
  tests/pw/tests/e2e/followStore.spec.ts
  tests/pw/tests/e2e/settings.spec.ts
  tests/pw/utils/helpers.ts
  tests/pw/utils/interfaces.ts
  tests/pw/utils/testData.ts
Labels: QA approved

#2286 Fix: Incorrect format of PHPCS for *register custom sanitize function*
  .github/workflows/phpcs.yml
  phpcs.xml.dist
Labels: Need Dev Review Only
