Repository getdokan/dokan, pull requests merged in 2024-06, with the labels that each got.

#2288 added eu complicance tests
  .github/workflows/e2e_api_tests.yml
  tests/pw/.prettierrc
  tests/pw/.wp-env.override
  tests/pw/feature-map/feature-map.yml
  tests/pw/pages/basePage.ts
  tests/pw/pages/colorsPage.ts
  tests/pw/pages/customerPage.ts
  tests/pw/pages/euCompliancePage.ts
  tests/pw/pages/productsPage.ts
  tests/pw/pages/selectors.ts
  tests/pw/pages/settingsPage.ts
  tests/pw/pages/shippingPage.ts
  tests/pw/pages/singleProductPage.ts
  tests/pw/pages/singleStorePage.ts
  tests/pw/pages/storesPage.ts
  tests/pw/pages/vendorAuctionsPage.ts
  tests/pw/pages/vendorPage.ts
  tests/pw/pages/vendorSettingsPage.ts
  tests/pw/tests/api/calculation.spec.ts
  tests/pw/tests/e2e/_auth.setup.ts
  tests/pw/tests/e2e/_env.setup.ts
  tests/pw/tests/e2e/colors.spec.ts
  tests/pw/tests/e2e/coupons.spec.ts
  tests/pw/tests/e2e/customer.spec.ts
  tests/pw/tests/e2e/euCompliance.spec.ts
  tests/pw/tests/e2e/settings.spec.ts
  tests/pw/tests/e2e/stores.spec.ts
  tests/pw/tests/e2e/vendor.spec.ts
  tests/pw/tests/e2e/vendorSettings.spec.ts
  tests/pw/types/environment.d.ts
  tests/pw/utils/apiUtils.ts
  tests/pw/utils/dbData.ts
  tests/pw/utils/interfaces.ts
  tests/pw/utils/payloads.ts
  tests/pw/utils/testData.ts
Labels: QA approved

#2287 chore: Exclude directory for PHPCS Scanning fix
  phpcs.xml.dist
Labels: Need Dev Review Only

#2285 Fix: PHP Warning when trying to remove action `dokan_seller_reg_form_fields`
  includes/Registration.php
Labels: Need Dev Review Only

#2289 Update readme.txt
  readme.txt
Labels: QA approved, Upcoming Release

#2262 fix: Responsive issue on vendor dashboard tabs preview.
  assets/src/less/dashboard.less
  assets/src/less/extra.less
  assets/src/less/responsive.less
Labels: QA approved, :+1: Dev Review Done

#2269 refactor: `WordPress.Security.EscapeOutput.OutputNotEscaped` escaping
  templates/emails/plain/new-seller-registered.php
  templates/emails/plain/reverse-withdrawal-invoice.php
  templates/emails/plain/vendor-completed-order.php
  templates/emails/plain/vendor-new-order.php
  templates/emails/plain/vendor-product-review.php
  templates/emails/product-published.php
  templates/emails/reverse-withdrawal-invoice.php
  templates/emails/vendor-completed-order.php
  templates/emails/vendor-new-order.php
  templates/emails/vendor-product-review.php
  templates/my-orders.php
  templates/reverse-withdrawal/transaction-listing.php
  templates/store-lists-filter.php
  templates/sub-orders.php
  templates/vendor-store-info.php
Labels: QA approved, :+1: Dev Review Done, Upcoming Release

#2272 Fix plugin phpcs warnings
  includes/Admin/functions.php
  includes/Order/Manager.php
  includes/Order/MiscHooks.php
  includes/ProductCategory/Hooks.php
  includes/ReverseWithdrawal/Manager.php
  includes/Upgrade/Upgrades/BackgroundProcesses/V_2_8_3_VendorBalance.php
  includes/Upgrade/Upgrades/BackgroundProcesses/V_2_9_4_OrderPostAuthor.php
  includes/Upgrade/Upgrades/V_1_2.php
  includes/Upgrade/Upgrades/V_2_9_13.php
  includes/Upgrade/Upgrades/V_2_9_4.php
  includes/Upgrade/Upgrades/V_3_0_4.php
  includes/Upgrade/Upgrades/V_3_2_12.php
  includes/Upgrade/Upgrades/V_3_3_1.php
  includes/Upgrade/Upgrades/V_3_3_7.php
  includes/functions-compatibility.php
Labels: Needs: Testing, QA approved, :+1: Dev Review Done

#2284 fix: Dokan promo license activation handler method.
  includes/Admin/Notices/Helper.php
Labels: QA approved, :+1: Dev Review Done, Upcoming Release
