Repository getdokan/dokan, pull requests merged in 2024-02, with the labels that each got.

#1984 Update progress bar data when update all payment and address given properly and validation
  assets/src/less/setup.less
  includes/Registration.php
  includes/Vendor/SetupWizard.php
  templates/settings/bank-payment-method-settings.php
  templates/store-lists-filter.php
Labels: QA approved, Dev Review Done, Dependency With Pro

#2146 Add check for withdrawal class to get withdraw.
  includes/Dashboard/Templates/Withdraw.php
Labels: QA approved, Dev Review Done

#2153 fix: PHP 8.2 Compatibility Issues
  includes/Admin/functions.php
  includes/Emails/VendorCompletedOrder.php
  includes/Emails/VendorNewOrder.php
  includes/Vendor/SetupWizard.php
  templates/store-lists-filter.php
Labels: QA approved, Dev Review Done

#2157 fix: description missing from dokan admin setup wizard
  includes/Admin/SetupWizard.php
  templates/admin-setup-wizard/step-store.php
Labels: QA approved, Dev Review Done

#2158 Fix: When HPOS is enabled, sub-orders disappear when orders are filtered by a specific vendor
  includes/Order/Admin/Hooks.php
Labels: QA approved, Dev Review Done

#2159 Fix: HTML entity appearing on the store category
  src/admin/pages/Vendors.vue
Labels: QA approved, Dev Review Done

#2162 fix: Many strings in Dokan shipping settings and related screens cannot be translated using WPML
  includes/functions.php
Labels: QA approved, Dev Review Done, urgent

#2050 Feature: Dashboard Menu Manager
  composer.json
  includes/Dashboard/Templates/Dashboard.php
  includes/ReverseWithdrawal/Hooks.php
  includes/Shortcodes/Dashboard.php
  includes/functions-dashboard-navigation.php
  includes/functions.php
  includes/template-tags.php
  package.json
  src/admin/components/Fields.vue
  src/admin/pages/Settings.vue
  src/utils/Bootstrap.js
Labels: QA approved, Dependency With Pro

#2140 Fix/incorrect woocommerce analytics
  includes/Order/MiscHooks.php
Labels: QA approved, Dev Review Done

#2143 Update: Fontawesome library to version 6.5.1
  assets/src/less/store.less
  assets/vendors/font-awesome/css/font-awesome.min.css
  assets/vendors/font-awesome/font-awesome.min.css
  assets/vendors/font-awesome/webfonts/fa-brands-400.eot
  assets/vendors/font-awesome/webfonts/fa-brands-400.svg
  assets/vendors/font-awesome/webfonts/fa-brands-400.ttf
  assets/vendors/font-awesome/webfonts/fa-brands-400.woff
  assets/vendors/font-awesome/webfonts/fa-brands-400.woff2
  assets/vendors/font-awesome/webfonts/fa-regular-400.eot
  assets/vendors/font-awesome/webfonts/fa-regular-400.svg
  assets/vendors/font-awesome/webfonts/fa-regular-400.ttf
  assets/vendors/font-awesome/webfonts/fa-regular-400.woff
  assets/vendors/font-awesome/webfonts/fa-regular-400.woff2
  assets/vendors/font-awesome/webfonts/fa-solid-900.eot
  assets/vendors/font-awesome/webfonts/fa-solid-900.svg
  assets/vendors/font-awesome/webfonts/fa-solid-900.ttf
  assets/vendors/font-awesome/webfonts/fa-solid-900.woff
  assets/vendors/font-awesome/webfonts/fa-solid-900.woff2
  assets/vendors/font-awesome/webfonts/fa-v4compatibility.ttf
  assets/vendors/font-awesome/webfonts/fa-v4compatibility.woff2
  includes/Assets.php
  includes/functions.php
Labels: QA approved, Dev Review Done

#2154 Feature lock
  includes/Admin/Settings.php
  includes/Install/Installer.php
  includes/Product/VendorStoreInfo.php
  includes/ReverseWithdrawal/Admin/Settings.php
  src/admin/App.vue
  src/admin/components/AddReverseWithdraw.vue
  src/admin/components/DokanRadioGroup.vue
  src/admin/components/Fields.vue
  src/admin/components/Fields/WithdrawCharges.vue
  src/admin/components/SecretInput.vue
  src/admin/components/SocialFields.vue
  src/admin/components/Switches.vue
  src/admin/pages/VendorPaymentFields.vue
Labels: QA approved, Dev Review Done

#2170 update: `dokan_product_cache_delete_all_data` filter added in `ProductCache::delete()`
  includes/Product/ProductCache.php
Labels: Needs: Testing, Dev Review Done

#2171 fix: elementor mega menu `z-index` conflict and address line break remove
  assets/src/less/store-lists.less
Labels: Review Needed, Dev Review Done, urgent
