Repository getdokan/dokan, pull requests merged in 2024-07, with the labels that each got.

#1884 New Walker added for category dropdown multiselect
  includes/Order/Hooks.php
Labels: Needs: Testing, Needs: Dev Review

#2164 Support code added for min max module refactor
  templates/products/products-listing-row.php
Labels: Dependency With Pro

#2307 Update readme.txt
  readme.txt
Labels: Ready to Merge, Upcoming Release

#2270 refactor: `WordPress.Security.EscapeOutput.OutputNotEscaped`, `WordPress.Security.EscapeOutput.ExceptionNotEscaped` escaping
  assets/js/page-views.js
  assets/src/js/page-views.js
  includes/Admin/Hooks.php
  includes/Admin/SetupWizard.php
  includes/Admin/SetupWizardNoWC.php
  includes/Ajax.php
  includes/Customizer/HeadingControl.php
  includes/Customizer/RadioImageControl.php
  includes/Order/Admin/Hooks.php
  includes/PageViews.php
  includes/REST/ProductController.php
  includes/ReverseWithdrawal/ReverseWithdrawal.php
  includes/Traits/ChainableContainer.php
  includes/Widgets/BestSellingProducts.php
  includes/Widgets/FilterByAttributes.php
  includes/Widgets/ProductCategoryMenu.php
  includes/Widgets/StoreCategoryMenu.php
  includes/Widgets/StoreContactForm.php
  includes/Widgets/StoreLocation.php
  includes/Widgets/StoreOpenClose.php
  includes/Widgets/TopratedProducts.php
  includes/functions.php
  includes/template-tags.php
  phpcs.xml.dist
  templates/products/dokan-category-header-ui.php
  templates/products/dokan-category-ui.php
  templates/products/listing-status-filter.php
  templates/products/new-product.php
  templates/products/products-listing.php
  templates/settings/bank-payment-method-settings.php
  templates/settings/payment.php
  templates/settings/store-form.php
  webpack.config.js
Labels: QA approved, :+1: Dev Review Done, Upcoming Release

#2291 fix: Shop url rendered double slash when using WPML on vendor registration form.
  templates/account/update-customer-to-vendor.php
  templates/global/seller-registration-form.php
Labels: QA approved, :+1: Dev Review Done, Upcoming Release

#2297 🚀 enhance: Direct links to the relevant settings from vendor progress bar
  templates/settings/address-form.php
  templates/settings/payment.php
  templates/settings/store-form.php
Labels: QA approved, :+1: Dev Review Done, Upcoming Release

#2299 Dashboard active menu not working after translation issue fix
  includes/functions-dashboard-navigation.php
Labels: QA approved, :+1: Dev Review Done, Upcoming Release

#2308 🎯 fix: Fatal error in block editor on adding and editing page with customer-migration shortcode
  includes/Frontend/MyAccount/BecomeAVendor.php
Labels: QA approved, :+1: Dev Review Done, Upcoming Release

#2301 Refactor seller registration to enable bypassing nonce verification
  includes/Registration.php
Labels: :+1: Dev Review Done, Upcoming Release
