Repository getdokan/dokan, pull requests merged in 2024-09, with the labels that each got.

#2363 fix: Duplicate request methods in `DokanTestCase` class
  tests/php/src/DokanTestCase.php
Labels: Needs: Dev Review, Need Dev Review Only

#2273 fix: PHPCS errors and warnings
  deprecated/deprecated-functions.php
  includes/Order/Hooks.php
  includes/Order/functions.php
  includes/functions.php
  includes/wc-functions.php
  templates/account/update-customer-to-vendor.php
  templates/account/vendor-registration.php
  templates/global/seller-registration-form.php
  templates/orders/listing.php
  templates/orders/order-download-permission-html.php
  templates/reverse-withdrawal/reverse-balance.php
  templates/store-lists-loop.php
  templates/widgets/store-open-close.php
  templates/widgets/widget-content-product.php
  templates/withdraw/withdraw-dashboard.php
Labels: QA approved, :+1: Dev Review Done, Upcoming Release

#2336 Fix vendor dashboard product edit page variation products
  includes/Product/ProductAttribute.php
  includes/REST/ProductAttributeController.php
Labels: QA approved, :+1: Dev Review Done

#2353 fix: ui style for the close button in product images gallery
  assets/css/style.css
  assets/src/less/products.less
Labels: QA approved, :+1: Dev Review Done, Upcoming Release

#2354 fix: Prevent incorrect sub-order status updates
  includes/Order/Hooks.php
Labels: QA approved, :+1: Dev Review Done, Upcoming Release

#2351 fix: Improve vendor coupon validation for various discount item types and empty cart scenarios
  includes/Order/Hooks.php
Labels: :+1: Dev Review Done, Need Dev Review Only, Upcoming Release

#2375 added: test case for Dokan order creation (sub-order)
  includes/Order/Manager.php
  tests/php/src/Orders/OrderTest.php
Labels: :+1: Dev Review Done, Need Dev Review Only

#2379 Add Pro module tests(wholesale, vendorstaff) (test automation)
  tests/pw/feature-map/feature-map.yml
  tests/pw/fixtures/page.ts
  tests/pw/pages/basePage.ts
  tests/pw/pages/colorsPage.ts
  tests/pw/pages/customerPage.ts
  tests/pw/pages/menuManagerPage.ts
  tests/pw/pages/productAdvertisingPage.ts
  tests/pw/pages/productQAPage.ts
  tests/pw/pages/refundsPage.ts
  tests/pw/pages/reverseWithdrawsPage.ts
  tests/pw/pages/selectors.ts
  tests/pw/pages/settingPage.ts
  tests/pw/pages/settingsPage.ts
  tests/pw/pages/singleProductPage.ts
  tests/pw/pages/vendorBookingPage.ts
  tests/pw/pages/vendorDashboardPage.ts
  tests/pw/pages/vendorPage.ts
  tests/pw/pages/vendorStaffPage.ts
  tests/pw/pages/vendorSubscriptionsPage.ts
  tests/pw/pages/wholesalePage.ts
  tests/pw/pages/withdrawsPage.ts
  tests/pw/tests/e2e/dashboard.spec.ts
  tests/pw/tests/e2e/vendorBooking.spec.ts
  tests/pw/tests/e2e/vendorStaff.spec.ts
  tests/pw/tests/e2e/vendorVerifications.spec.ts
  tests/pw/tests/e2e/wholesale.spec.ts
  tests/pw/utils/apiUtils.ts
  tests/pw/utils/helpers.ts
  tests/pw/utils/pwMatchers.ts
  tests/pw/utils/testData.ts
Labels: QA approved, Test Automation

#2380 Add Setup tests (test automation)
  tests/pw/feature-map/feature-map.yml
  tests/pw/package-lock.json
  tests/pw/package.json
  tests/pw/pages/basePage.ts
  tests/pw/pages/loginPage.ts
  tests/pw/pages/selectors.ts
  tests/pw/pages/singleProductPage.ts
  tests/pw/pages/vendorPage.ts
  tests/pw/tests/api/_env.setup.ts
  tests/pw/tests/e2e/_env.setup.ts
  tests/pw/tests/e2e/shortcodes.spec.ts
  tests/pw/tests/e2e/wholesale.spec.ts
  tests/pw/types/environment.d.ts
  tests/pw/utils/apiUtils.ts
  tests/pw/utils/helpers.ts
  tests/pw/utils/interfaces.ts
  tests/pw/utils/payloads.ts
  tests/pw/utils/testData.ts
Labels: QA approved, Test Automation

#2381 Add product addon tests(automation suite)
  tests/pw/feature-map/feature-map.yml
  tests/pw/pages/loginPage.ts
  tests/pw/pages/productAddonsPage.ts
  tests/pw/pages/productsPage.ts
  tests/pw/pages/selectors.ts
  tests/pw/pages/shortcodePage.ts
  tests/pw/pages/spmvPage.ts
  tests/pw/pages/vendorPage.ts
  tests/pw/pages/vendorSettingsPage.ts
  tests/pw/tests/api/productReviews.spec.ts
  tests/pw/tests/e2e/catalogmode.spec.ts
  tests/pw/tests/e2e/productAddons.spec.ts
  tests/pw/tests/e2e/products.spec.ts
  tests/pw/tests/e2e/vendorBooking.spec.ts
  tests/pw/tests/e2e/vendorTools.spec.ts
  tests/pw/utils/apiEndPoints.ts
  tests/pw/utils/dbData.ts
  tests/pw/utils/interfaces.ts
  tests/pw/utils/payloads.ts
  tests/pw/utils/sampleData/banner.png
  tests/pw/utils/sampleData/products.csv
  tests/pw/utils/sampleData/products.xml
  tests/pw/utils/testData.ts
Labels: QA approved, Test Automation

#2382 fix: duplicate test methods in DokanTestCase.php
  tests/php/src/DokanTestCase.php
Labels: :+1: Dev Review Done, Need Dev Review Only

#2383 Add product form tests
  tests/pw/feature-map/feature-map.yml
  tests/pw/pages/productsPage.ts
  tests/pw/tests/api/orderDownloads.spec.ts
  tests/pw/tests/e2e/products.spec.ts
  tests/pw/tests/e2e/productsDetails.spec.ts
  tests/pw/utils/payloads.ts
Labels: QA approved, Test Automation
