Repository getdokan/dokan, pull requests merged in 2024-08, with the labels that each got.

#2306 feat(core): Add action hooks in product table in vendor dashboard
  templates/products/products-listing-row.php
Labels: :+1: Dev Review Done, Need Dev Review Only

#2316 fix: Admin color picker settings/component not working as expected.
  src/admin/components/Fields.vue
Labels: QA approved, :+1: Dev Review Done, Upcoming Release

#2319 fix: Extra slashes issue on store url when translated via WPML.
  templates/account/vendor-registration.php
Labels: QA approved, :+1: Dev Review Done, Upcoming Release

#2326 Fix: empty spaces before the store url in the vendor registration form
  templates/account/update-customer-to-vendor.php
  templates/account/vendor-registration.php
  templates/global/seller-registration-form.php
Labels: QA approved, :+1: Dev Review Done

#2328 Fix a fail test
  tests/pw/.wp-env.json
  tests/pw/pages/selectors.ts
  tests/pw/tests/e2e/shortcodes.spec.ts
Labels: QA approved

#2334 Add vendor subscriptions tests
  tests/pw/e2e.config.ts
  tests/pw/feature-map/feature-map.yml
  tests/pw/global-setup.ts
  tests/pw/pages/selectors.ts
  tests/pw/pages/vendorSubscriptionsPage.ts
  tests/pw/playwright.config.ts
  tests/pw/tests/api/commissions.spec.ts
  tests/pw/tests/api/vendorSubscription.spec.ts
  tests/pw/tests/e2e/_localSite.setup.ts
  tests/pw/tests/e2e/_plugin.setup.ts
  tests/pw/tests/e2e/vendorSubscriptions.spec.ts
  tests/pw/types/environment.d.ts
  tests/pw/utils/apiEndPoints.ts
  tests/pw/utils/apiUtils.ts
  tests/pw/utils/dbData.ts
  tests/pw/utils/dbUtils.ts
  tests/pw/utils/interfaces.ts
  tests/pw/utils/payloads.ts
  tests/pw/utils/schemas.ts
  tests/pw/utils/testData.ts
Labels: QA approved

#2337 Add shipping status api tests (test automation)
  tests/pw/tests/api/shippingStatus.spec.ts
  tests/pw/utils/apiEndPoints.ts
  tests/pw/utils/apiUtils.ts
  tests/pw/utils/payloads.ts
  tests/pw/utils/schemas.ts
Labels: QA approved

#2345 Update workflow, fix some flaky & failed (pro) tests, add new tests (automation suite)
  .github/workflows/e2e_api_tests.yml
  tests/pw/.eslintrc
  tests/pw/.wp-env.json
  tests/pw/e2e.config.ts
  tests/pw/feature-map/feature-map.yml
  tests/pw/pages/announcementsPage.ts
  tests/pw/pages/basePage.ts
  tests/pw/pages/customerPage.ts
  tests/pw/pages/paymentsPage.ts
  tests/pw/pages/productQAPage.ts
  tests/pw/pages/selectors.ts
  tests/pw/pages/sellerBadgesPage.ts
  tests/pw/pages/shortcodePage.ts
  tests/pw/pages/storeCategoriesPage.ts
  tests/pw/pages/vendorAuctionsPage.ts
  tests/pw/pages/vendorBookingPage.ts
  tests/pw/pages/vendorPage.ts
  tests/pw/pages/vendorShippingPage.ts
  tests/pw/pages/withdrawsPage.ts
  tests/pw/tests/api/calculation.spec.ts
  tests/pw/tests/api/shippingStatus.spec.ts
  tests/pw/tests/e2e/_localSite.setup.ts
  tests/pw/tests/e2e/colors.spec.ts
  tests/pw/tests/e2e/coupons.spec.ts
  tests/pw/tests/e2e/euCompliance.spec.ts
  tests/pw/tests/e2e/productAdvertising.spec.ts
  tests/pw/tests/e2e/productQA.spec.ts
  tests/pw/tests/e2e/sellerBadges.spec.ts
  tests/pw/tests/e2e/vendorBooking.spec.ts
  tests/pw/tests/e2e/withdraws.spec.ts
  tests/pw/types/global.d.ts
  tests/pw/utils/apiUtils.ts
  tests/pw/utils/gitTestSummary.ts
  tests/pw/utils/helpers.ts
  tests/pw/utils/interfaces.ts
  tests/pw/utils/payloads.ts
  tests/pw/utils/schemas.ts
  tests/pw/utils/summaryReporter.ts
  tests/pw/utils/testData.ts
Labels: QA approved

#2350 Update tests for changes introduced in woocommerce(v9.2.2)
  tests/pw/feature-map/feature-map.yml
  tests/pw/pages/adminPage.ts
  tests/pw/pages/basePage.ts
  tests/pw/pages/loginPage.ts
  tests/pw/pages/paymentsPage.ts
  tests/pw/pages/selectors.ts
  tests/pw/pages/settingsPage.ts
  tests/pw/pages/shippingPage.ts
  tests/pw/pages/shortcodePage.ts
  tests/pw/pages/taxPage.ts
  tests/pw/pages/withdrawsPage.ts
  tests/pw/tests/e2e/myOrders.spec.ts
  tests/pw/tests/e2e/shipping.spec.ts
  tests/pw/tests/e2e/vendorSettings.spec.ts
  tests/pw/utils/apiUtils.ts
  tests/pw/utils/interfaces.ts
  tests/pw/utils/payloads.ts
  tests/pw/utils/testData.ts
Labels: QA approved

#2311 fix: Displaying incorrect withdrawal amount when using decimal separator as thousand.
  assets/src/js/withdraw.js
  includes/Withdraw/functions.php
  src/admin/components/CombineInput.vue
  src/admin/components/Fields/WithdrawCharges.vue
Labels: QA approved, :+1: Dev Review Done, Upcoming Release

#2332 fix: Multiple invoice button for dokan sub-orders.
  includes/Order/Hooks.php
Labels: QA approved, :+1: Dev Review Done, Upcoming Release

#2348 Add header support for dokan test case post request.
  tests/php/src/DokanTestCase.php
Labels: Ready to Merge, :+1: Dev Review Done

#2342 added: new request methods for DELETE and PUT
  tests/php/src/DokanTestCase.php
Labels: Ready to Merge, :+1: Dev Review Done

#2352 Add storecategories tests (test automation)
  tests/pw/feature-map/feature-map.yml
  tests/pw/pages/basePage.ts
  tests/pw/pages/customerPage.ts
  tests/pw/pages/myOrdersPage.ts
  tests/pw/pages/paymentsPage.ts
  tests/pw/pages/productsPage.ts
  tests/pw/pages/selectors.ts
  tests/pw/pages/shortcodePage.ts
  tests/pw/pages/storeCategoriesPage.ts
  tests/pw/pages/withdrawsPage.ts
  tests/pw/tests/e2e/_localSite.setup.ts
  tests/pw/tests/e2e/myOrders.spec.ts
  tests/pw/tests/e2e/storeCategories.spec.ts
  tests/pw/tsconfig.json
  tests/pw/utils/apiUtils.ts
  tests/pw/utils/dbData.ts
  tests/pw/utils/gitTestSummary.ts
  tests/pw/utils/pwMatchers.ts
  tests/pw/utils/testData.ts
Labels: Ready to Merge, QA approved

#2344 Fix: Prevent Stock Quantity Update During Product Edit if Unchanged
  composer.lock
  includes/wc-functions.php
  templates/products/inventory.php
Labels: QA approved, :+1: Dev Review Done

#2355 Update tests for mix-max feature (automation suite)
  tests/pw/e2e.config.ts
  tests/pw/pages/abuseReportsPage.ts
  tests/pw/pages/basePage.ts
  tests/pw/pages/modulesPage.ts
  tests/pw/pages/ordersPage.ts
  tests/pw/pages/productAdvertisingPage.ts
  tests/pw/pages/productQAPage.ts
  tests/pw/pages/productsPage.ts
  tests/pw/pages/refundsPage.ts
  tests/pw/pages/reportsPage.ts
  tests/pw/pages/selectors.ts
  tests/pw/pages/sellerBadgesPage.ts
  tests/pw/pages/settingsPage.ts
  tests/pw/pages/shortcodePage.ts
  tests/pw/pages/storeCategoriesPage.ts
  tests/pw/pages/storeSupportsPage.ts
  tests/pw/pages/storesPage.ts
  tests/pw/pages/vendorSubscriptionsPage.ts
  tests/pw/pages/vendorVerificationsPage.ts
  tests/pw/pages/wholesaleCustomersPage.ts
  tests/pw/pages/withdrawsPage.ts
  tests/pw/tests/e2e/abuseReports.spec.ts
  tests/pw/tests/e2e/customer.spec.ts
  tests/pw/tests/e2e/myOrders.spec.ts
  tests/pw/tests/e2e/refunds.spec.ts
  tests/pw/tests/e2e/reports.spec.ts
  tests/pw/tests/e2e/setting.spec.ts
  tests/pw/tests/e2e/storeCategories.spec.ts
  tests/pw/tests/e2e/storeSupports.spec.ts
  tests/pw/utils/apiUtils.ts
  tests/pw/utils/dbData.ts
  tests/pw/utils/schemas.ts
  tests/pw/utils/testData.ts
Labels: QA approved

#2360 fix: Resolve fatal error when updating Dokan Lite to 3.12.0 with Dokan Pro 3.9.7
  includes/Admin/Notices/Helper.php
Labels: QA approved, :+1: Dev Review Done, urgent
