Repository getdokan/dokan, pull requests merged in 2024-03, with the labels that each got.

#1912 Store Category Edit Option
  src/admin/components/StoreCategory.vue
  src/admin/pages/VendorAccountFields.vue
  src/utils/Bootstrap.js
Labels: QA approved, Dev Review Done

#1996 Tailwind css added
  assets/src/less/admin.less
  bin/clean-useless-files.js
  includes/Assets.php
  package-lock.json
  package.json
  postcss.config.js
  src/admin/components/AddReverseWithdraw.vue
  src/admin/components/AdminNotice.vue
  src/admin/components/CardFunFact.vue
  src/admin/components/Fields.vue
  src/admin/components/Modal.vue
  src/admin/components/ModuleUpgradePopup.vue
  src/admin/components/Postbox.vue
  src/admin/components/ProCta.vue
  src/admin/pages/AddVendor.vue
  src/admin/pages/Dashboard.vue
  src/admin/pages/DummyData.vue
  src/admin/pages/Premium.vue
  src/admin/pages/ProModules.vue
  src/admin/pages/ReverseWithdrawal.vue
  src/admin/pages/ReverseWithdrawalTransactions.vue
  src/admin/pages/Settings.vue
  src/admin/pages/VendorAccountFields.vue
  src/admin/pages/VendorAddressFields.vue
  src/admin/pages/VendorPaymentFields.vue
  src/admin/pages/Withdraw.vue
  src/tailwind.css
  tailwind.config.js
  webpack.config.js
Labels: QA approved, Dev Review Done, Dependency With Pro, urgent

#2188 Add Threads to Store Socials
  includes/functions.php
Labels: QA approved, Dev Review Done

#2190 update: Vendor Dashboard settings submenu translation support added
  includes/functions-dashboard-navigation.php
Labels: QA approved, Dev Review Done, :package: WPML

#2192 Fix: store list filter caching in with geolocation.
  includes/Vendor/Manager.php
Labels: QA approved, Dev Review Done

#1985 refactor: email placeholder, additional content support and formatting
  includes/Emails/ContactSeller.php
  includes/Emails/Manager.php
  includes/Emails/NewProduct.php
  includes/Emails/NewProductPending.php
  includes/Emails/NewSeller.php
  includes/Emails/ProductPublished.php
  includes/Emails/ReverseWithdrawalInvoice.php
  includes/Emails/VendorCompletedOrder.php
  includes/Emails/VendorNewOrder.php
  includes/Emails/VendorProductReview.php
  includes/Emails/VendorWithdrawRequest.php
  includes/Emails/WithdrawApproved.php
  includes/Emails/WithdrawCancelled.php
  includes/ReverseWithdrawal/BackgroundProcess/AsyncRequests.php
  includes/Vendor/Vendor.php
  templates/emails/contact-seller.php
  templates/emails/new-product-pending.php
  templates/emails/new-product.php
  templates/emails/new-seller-registered.php
  templates/emails/plain/contact-seller.php
  templates/emails/plain/new-product-pending.php
  templates/emails/plain/new-product.php
  templates/emails/plain/new-seller-registered.php
  templates/emails/plain/product-published.php
  templates/emails/plain/vendor-completed-order.php
  templates/emails/plain/vendor-new-order.php
  templates/emails/plain/vendor-product-review.php
  templates/emails/plain/withdraw-approve.php
  templates/emails/plain/withdraw-cancel.php
  templates/emails/plain/withdraw-new.php
  templates/emails/product-published.php
  templates/emails/vendor-completed-order.php
  templates/emails/vendor-new-order.php
  templates/emails/vendor-product-review.php
  templates/emails/withdraw-approve.php
  templates/emails/withdraw-cancel.php
  templates/emails/withdraw-new.php
Labels: QA approved, Dev Review Done

#2186 Fix: The vendor profile progress bar doesn't update if the address is filled from the vendor registration form
  dokan.php
  includes/Registration.php
  includes/Vendor/SetupWizard.php
Labels: QA approved, Dev Review Done

#2202 Fix: Color customizer not sync with vendor's dashboard order buttons.
  assets/src/less/extra.less
  templates/orders/details.php
Labels: QA approved, Dev Review Done
