Repository getdokan/dokan, pull requests merged in 2024-04, with the labels that each got.

#2207 fix: product review email cannot be disabled without also disabling Contact Vendor email
  includes/Emails/VendorProductReview.php
Labels: QA approved, Dev Review Done

#2211 fix: Order Export to CSV on filtered list not working
  includes/Dashboard/Templates/Orders.php
Labels: QA approved, Dev Review Done

#2215 Update: Add requires plugin header for dokan.
  dokan.php
Labels: QA approved, Dev Review Done

#2218 update: `dokan_commission_log_gateway_fee_to_order_note` filter hook added
  includes/Commission.php
Labels: Needs: Testing, Dev Review Done, Need Dev Review Only

#2222 updated some e2e tests
  .github/workflows/e2e_api_tests.yml
  tests/pw/package-lock.json
  tests/pw/package.json
  tests/pw/pages/selectors.ts
  tests/pw/utils/gitTestSummary.ts
Labels: Needs: Dev Review

#2195 Notification count added on vendor dashboard menu render
  includes/Dashboard/Templates/Main.php
  includes/functions-dashboard-navigation.php
Labels: QA approved, Dev Review Done, Upcoming Release

#1913 update: admin can change product author from rest api
  includes/Abstracts/DokanRESTController.php
  includes/REST/ProductController.php
Labels: REST API, QA approved, Dev Review Done, [Products], Upcoming Release

#2212 Fix: Advertisement product not purchasable for own product purchasing restriction.
  includes/wc-functions.php
Labels: QA approved, Dev Review Done, Upcoming Release

#2216 Bug/fix header template one BG img layout 3249
  assets/src/less/store.less
Labels: QA approved, Dev Review Done, Upcoming Release

#2217 Fix html entity showing in product tag selection and Fix vendor add notification switch in admin dashboard
  assets/src/js/product-editor.js
  src/admin/pages/VendorAccountFields.vue
Labels: QA approved, Dev Review Done, Upcoming Release

#2204 fix: under wooCommerce my-account registration section, `I am a customer` was forced to be set as default value
  assets/src/js/vendor-registration.js
  includes/Assets.php
  includes/template-tags.php
Labels: QA approved, Dev Review Done, urgent, Upcoming Release

#2223 update: Pending Order count added for vendor dashboard Order menu
  includes/Dashboard/Templates/Orders.php
Labels: QA approved, Dev Review Done, urgent, Upcoming Release

#2193 pref: performance improvements for vendor dashboard -> order details page -> downloadable product permission section.
  assets/src/js/orders.js
  includes/Assets.php
  includes/Order/Ajax.php
  includes/Order/Controller.php
  templates/orders/downloadable.php
  templates/orders/order-download-permission-html.php
Labels: QA approved, Dev Review Done, urgent, Upcoming Release

#2224 🎨 enhance: Warning message styling for selecting fixed cart discount on admin coupon add edit page
  assets/src/less/global-admin.less
Labels: QA approved, Dev Review Done, urgent, Upcoming Release

#2239 fix: Store support modules menu double border issue.
  assets/src/less/products.less
  includes/template-tags.php
Labels: QA approved, Dev Review Done, Upcoming Release

#2241 Fix withdraw header title
  templates/withdraw/header.php
Labels: QA approved, Dev Review Done, Upcoming Release

#2255 fix: Vue Translation loading from WP Language Directory
  includes/functions.php
Labels: QA approved, Dev Review Done, urgent
