Repository getdokan/dokan, pull requests merged in 2024-11, with the labels that each got.

#2422 Add Admin settings tests
  tests/pw/.env.example
  tests/pw/feature-map/feature-map.yml
  tests/pw/pages/couponsPage.ts
  tests/pw/pages/selectors.ts
  tests/pw/pages/settingsPage.ts
  tests/pw/tests/e2e/_env.setup.ts
  tests/pw/tests/e2e/coupons.spec.ts
  tests/pw/tests/e2e/settings.spec.ts
  tests/pw/types/environment.d.ts
  tests/pw/utils/dbUtils.ts
  tests/pw/utils/interfaces.ts
  tests/pw/utils/testData.ts
Labels: QA approved, Test Automation

#2425 Add Live search tests
  tests/pw/feature-map/feature-map.yml
  tests/pw/pages/basePage.ts
  tests/pw/pages/liveSearchPage.ts
  tests/pw/pages/selectors.ts
  tests/pw/tests/e2e/liveSearch.spec.ts
  tests/pw/tests/e2e/privacyPolicy.spec.ts
  tests/pw/utils/apiEndPoints.ts
  tests/pw/utils/apiUtils.ts
  tests/pw/utils/dbData.ts
  tests/pw/utils/testData.ts
Labels: QA approved, Test Automation

#2426 add live chat module tests
  tests/pw/feature-map/feature-map.yml
  tests/pw/pages/basePage.ts
  tests/pw/pages/liveChatPage.ts
  tests/pw/pages/productsPage.ts
  tests/pw/pages/selectors.ts
  tests/pw/pages/settingsPage.ts
  tests/pw/pages/singleProductPage.ts
  tests/pw/pages/singleStorePage.ts
  tests/pw/pages/storeSupportsPage.ts
  tests/pw/pages/vendorSettingsPage.ts
  tests/pw/tests/e2e/_env.setup.ts
  tests/pw/tests/e2e/liveChat.spec.ts
  tests/pw/tests/e2e/settings.spec.ts
  tests/pw/tests/e2e/vendorSettings.spec.ts
  tests/pw/types/environment.d.ts
  tests/pw/utils/dbData.ts
  tests/pw/utils/interfaces.ts
  tests/pw/utils/testData.ts
Labels: QA approved, Test Automation

#2324 enhance: Make compatible with printful module.
  assets/src/less/products.less
  assets/src/less/site-navigation.less
  includes/Order/Manager.php
  includes/Product/Hooks.php
  includes/functions-dashboard-navigation.php
  src/admin/components/Fields.vue
  src/admin/pages/Settings.vue
  src/utils/Mixin.js
  templates/global/dashboard-nav.php
  templates/products/edit-product-single.php
  templates/products/products-listing-row.php
Labels: Needs: Testing, :+1: Dev Review Done

#2364 fix: Vendor categories tranlation compatibility stuff with WPML.
  includes/ProductCategory/Categories.php
Labels: QA approved, :+1: Dev Review Done, urgent, Upcoming Release

#2408 feat: Enhance debug log for order trash and untrash log
  includes/Order/OrderEventListener.php
Labels: QA approved, :+1: Dev Review Done

#2401 Fix: Restrict multiple categories in free plan
  templates/products/dokan-category-header-ui.php
Labels: QA approved, :+1: Dev Review Done

#2432 Add Printful module tests
  tests/pw/.env.example
  tests/pw/.gitignore
  tests/pw/README.MD
  tests/pw/feature-map/feature-map.yml
  tests/pw/pages/basePage.ts
  tests/pw/pages/catalogModePage.ts
  tests/pw/pages/colorsPage.ts
  tests/pw/pages/euCompliancePage.ts
  tests/pw/pages/menuManagerPage.ts
  tests/pw/pages/printfulPage.ts
  tests/pw/pages/privacyPolicyPage.ts
  tests/pw/pages/productAdvertisingPage.ts
  tests/pw/pages/reverseWithdrawsPage.ts
  tests/pw/pages/selectors.ts
  tests/pw/pages/settingsPage.ts
  tests/pw/pages/vendorVerificationsPage.ts
  tests/pw/pages/withdrawsPage.ts
  tests/pw/tests/e2e/_env.setup.ts
  tests/pw/tests/e2e/colors.spec.ts
  tests/pw/tests/e2e/liveChat.spec.ts
  tests/pw/tests/e2e/liveSearch.spec.ts
  tests/pw/tests/e2e/printful.spec.ts
  tests/pw/tests/e2e/settings.spec.ts
  tests/pw/tests/e2e/shortcodes.spec.ts
  tests/pw/types/environment.d.ts
  tests/pw/utils/dbData.ts
  tests/pw/utils/interfaces.ts
  tests/pw/utils/testData.ts
Labels: Test Automation

#2415 feat: Update order status allowed list with WooCommerce custom statuses
  includes/Order/Hooks.php
  tests/php/src/Orders/OrderStatusChangeTest.php
Labels: :+1: Dev Review Done, QA In Progress

#2258 Enhance: Update dokan admin dashboard logo & add logo update notice.
  assets/images/dokan-logo.png
  assets/images/dokan-logo.svg
  assets/images/dokan-settings-banner.svg
  assets/images/dokan-vendor-capabilities-banner-bg.svg
  assets/images/payments/d-paypal.svg
  assets/images/payments/d-stripe.svg
  assets/images/premium/cta-dokan-logo.png
  assets/images/premium/cta-pattern@2x.png
  assets/images/premium/dokan-lite-logo@2x.png
  assets/images/premium/dokan-pro-logo@2x.png
  assets/images/premium/header-feature-thumb@2x.png
  assets/images/vendor-capability/cap-announcement-vendors.svg
  assets/src/images/dokan-notice-logo.svg
  assets/src/less/admin.less
  assets/src/less/global-admin.less
  assets/src/less/setup.less
  assets/src/less/variables.less
  includes/Admin/Menu.php
  includes/Admin/Notices/Manager.php
  src/admin/components/ModuleUpgradePopup.vue
  src/admin/components/ProCta.vue
  src/admin/pages/ChangeLog.vue
  src/admin/pages/Premium.vue
  src/admin/pages/VendorCapabilities.vue
  tests/pw/pages/basePage.ts
Labels: QA approved, :+1: Dev Review Done

#2438 Add Booking products tests
  tests/pw/feature-map/feature-map.yml
  tests/pw/pages/commissionPage.ts
  tests/pw/pages/customerPage.ts
  tests/pw/pages/selectors.ts
  tests/pw/pages/settingsPage.ts
  tests/pw/pages/vendorAuctionsPage.ts
  tests/pw/pages/vendorBookingPage.ts
  tests/pw/playwright.config.ts
  tests/pw/tests/e2e/commission.spec.ts
  tests/pw/tests/e2e/productsDetails.spec.ts
  tests/pw/tests/e2e/productsDetailsAuction.spec.ts
  tests/pw/tests/e2e/productsDetailsBookings.spec.ts
  tests/pw/tests/e2e/storelisting.spec.ts
  tests/pw/tests/e2e/vendorBooking.spec.ts
  tests/pw/utils/interfaces.ts
  tests/pw/utils/payloads.ts
  tests/pw/utils/testData.ts
Labels: QA approved, Test Automation

#2441 Add E2E tests for shortcode, commission, geolocation
  tests/pw/api.config.ts
  tests/pw/e2e.config.ts
  tests/pw/feature-map/feature-map.yml
  tests/pw/pages/adminPage.ts
  tests/pw/pages/basePage.ts
  tests/pw/pages/commissionPage.ts
  tests/pw/pages/geolocationPage.ts
  tests/pw/pages/noticeAndPromotionPage.ts
  tests/pw/pages/selectors.ts
  tests/pw/pages/shortcodePage.ts
  tests/pw/pages/singleProductPage.ts
  tests/pw/pages/storesPage.ts
  tests/pw/playwright.config.ts
  tests/pw/tests/e2e/commission.spec.ts
  tests/pw/tests/e2e/diagnosticnotice.spec.ts
  tests/pw/tests/e2e/geolocation.spec.ts
  tests/pw/tests/e2e/plugin.spec.ts
  tests/pw/tests/e2e/shortcodes.spec.ts
  tests/pw/tests/e2e/stores.spec.ts
  tests/pw/tests/e2e/vendorAuction.spec.ts
  tests/pw/utils/apiUtils.ts
  tests/pw/utils/dbData.ts
  tests/pw/utils/dbUtils.ts
  tests/pw/utils/interfaces.ts
  tests/pw/utils/payloads.ts
  tests/pw/utils/testData.ts
Labels: QA approved, Test Automation

#2445 Add Geolocation tests
  tests/pw/feature-map/feature-map.yml
  tests/pw/pages/geolocationPage.ts
  tests/pw/pages/noticeAndPromotionPage.ts
  tests/pw/pages/selectors.ts
  tests/pw/tests/e2e/commission.spec.ts
  tests/pw/tests/e2e/geolocation.spec.ts
  tests/pw/tests/e2e/plugin.spec.ts
  tests/pw/utils/dbData.ts
Labels: QA approved, Test Automation

#2444 Add shipstation tests
  tests/pw/feature-map/feature-map.yml
  tests/pw/package.json
  tests/pw/pages/selectors.ts
  tests/pw/pages/shipstationPage.ts
  tests/pw/pages/vendorAuctionsPage.ts
  tests/pw/pages/vendorSettingsPage.ts
  tests/pw/pages/vendorShippingPage.ts
  tests/pw/tests/api/shipstation.spec.ts
  tests/pw/tests/e2e/productsDetailsAuction.spec.ts
  tests/pw/tests/e2e/shipstation.spec.ts
  tests/pw/tests/e2e/vendorSettings.spec.ts
  tests/pw/utils/apiEndPoints.ts
  tests/pw/utils/apiUtils.ts
  tests/pw/utils/payloads.ts
  tests/pw/utils/schemas.ts
  tests/pw/utils/testData.ts
Labels: QA approved, Test Automation

#2440 Fix decimal and thousand separator for category commission.
  assets/src/js/setup-wizard/commission/AdminCommission.vue
  includes/Admin/Settings.php
  includes/Commission.php
  includes/Commission/Upugrader/Update_Category_Commission.php
  includes/Commission/Upugrader/Update_Product_Commission.php
  includes/Commission/Upugrader/Update_Vendor_Commission.php
  includes/Product/Hooks.php
  includes/Upgrade/Hooks.php
  includes/Upgrade/Upgrades/BackgroundProcesses/V_3_14_0_UpdateCommissions.php
  includes/Upgrade/Upgrades/V_3_14_0.php
  src/admin/components/CombineInput.vue
  src/admin/components/Commission/CategoryBasedCommission.vue
  src/admin/components/Fields.vue
  src/admin/pages/Settings.vue
  src/admin/pages/VendorSingle.vue
Labels: QA approved

#2448 chore: update `Appsero/Client` and `Appsero/Updater` for WP 6.7 compatibility
  composer.json
  composer.lock
Labels: QA approved, :+1: Dev Review Done, Upcoming Release

#2446 Enhance : Admin Notice Show gloablly & extand API
  includes/Assets.php
  includes/REST/AdminNoticeController.php
  includes/Upgrade/AdminNotice.php
  src/admin/components/AdminNotice.vue
  src/admin/notice/App.vue
  src/admin/notice/main.js
  webpack.config.js
Labels: QA approved, :+1: Dev Review Done, Upcoming Release

#2452 Auction tests
  tests/pw/feature-map/feature-map.yml
  tests/pw/pages/commissionPage.ts
  tests/pw/pages/selectors.ts
  tests/pw/pages/shipStationPage.ts
  tests/pw/pages/vendorAuctionsPage.ts
  tests/pw/tests/e2e/commission.spec.ts
  tests/pw/tests/e2e/vendorAuction.spec.ts
Labels: QA approved, Test Automation

#2453 Add new tests to featuremap
  tests/pw/feature-map/feature-map.yml
  tests/pw/tests/e2e/followStore.spec.ts
  tests/pw/tests/e2e/productsDetailsBookings.spec.ts
  tests/pw/tests/e2e/vendorSettings.spec.ts
  tests/pw/tests/e2e/wholesale.spec.ts
Labels: QA approved, Test Automation

#2450 Add notice for version compatibility.
  includes/Admin/Notices/Manager.php
Labels: QA approved, Upcoming Release

#2447 fix: plugin version after activation
  includes/Install/Installer.php
Labels: QA approved, :+1: Dev Review Done, Upcoming Release
