Repository getdokan/dokan, pull requests merged in 2024-01, with the labels that each got.

#1943 Feature: Withdraw charges
  assets/src/js/withdraw.js
  dokan.php
  includes/Admin/Settings.php
  includes/Assets.php
  includes/Dashboard/Templates/Withdraw.php
  includes/REST/WithdrawController.php
  includes/Withdraw/Hooks.php
  includes/Withdraw/Manager.php
  includes/Withdraw/Withdraw.php
  includes/Withdraw/functions.php
  src/admin/components/CombineInput.vue
  src/admin/components/Fields.vue
  src/admin/components/Fields/WithdrawCharges.vue
  src/admin/pages/Withdraw.vue
  templates/withdraw/approved-request-listing.php
  templates/withdraw/cancelled-request-listing.php
  templates/withdraw/pending-request-listing-dashboard.php
  templates/withdraw/pending-request-listing.php
  templates/withdraw/request-form.php
  tests/Withdrawal/WithdrawChargeApi.php
  tests/Withdrawal/WithdrawChargeTest.php
Labels: QA approved, Dev Review Done, Dependency With Pro

#2086 fix: Product Creation support for vendor staff and Catalog Mode
  includes/CatalogMode/Dashboard/Products.php
  templates/products/edit-product-single.php
Labels: QA approved, Dev Review Done, Dependency With Pro

#2101 fix: Order creation Support WC Block Checkout
  dokan.php
  includes/Order/Hooks.php
  includes/Order/Manager.php
  includes/Order/functions.php
  includes/functions-rest-api.php
Labels: QA approved, Dev Review Done, urgent

#2126 fix: Issue in displaying vendor map address on store listing page after setup wizard configuration
  includes/Vendor/SetupWizard.php
Labels: QA approved, Dev Review Done

#2128 fix: Several functionalities on the Vendor Dashboard, such as live product updates for pending orders, are not functioning correctly
  includes/Dashboard/Templates/Dashboard.php
  includes/functions.php
  templates/dashboard/orders-widget.php
  templates/dashboard/products-widget.php
Labels: QA approved, Dev Review Done

#2129 fix: The indication of whether the store is available or not is absent on the vendor migration form
  includes/Frontend/MyAccount/BecomeAVendor.php
Labels: QA approved, Dev Review Done

#2130 fix: When a customer buys digital and physical products from different vendors, shipping charges are applied separately to each vendor
  includes/Shipping/Hooks.php
Labels: QA approved, Dev Review Done

#2137 fix: Translation-Related Issues with Specific Menu Items in Vendor Dashboard with WPML
  includes/template-tags.php
Labels: QA approved, Dev Review Done

#2139 fix: Translation-Related Issues with daterange picker and SweetAlert
  assets/src/js/dokan-daterangepicker.js
  assets/src/js/helper.js
  includes/Assets.php
Labels: QA approved, Dev Review Done

#2156 fix: Vendor getting draft order in dashboard
  includes/Order/Hooks.php
Labels: Needs: Testing, Dev Review Done, urgent
