Repository getdokan/dokan, pull requests merged in 2025-03, with the labels that each got.

#2582 test(refactor): update tests for store api changes
  tests/pw/pages/selectors.ts
  tests/pw/pages/vendorAuctionsPage.ts
  tests/pw/tests/api/_auth.setup.ts
  tests/pw/tests/e2e/_auth.setup.ts
  tests/pw/utils/dbUtils.ts
  tests/pw/utils/payloads.ts
Labels: Test Automation

#2546 enhance: Expand sortable list UI component & make compatible with table contents.
  docs/frontend/sortable-list.md
  src/components/sortable-list/SortableItem.tsx
  src/components/sortable-list/index.tsx
  src/layout/Header.tsx
Labels: :+1: Dev Review Done, Need Dev Review Only

#2585 V4: Remove deprecated files
  deprecated/Singleton.php
  deprecated/class-abstract-class-dokan-background-processes.php
  deprecated/class-abstrct-dokan-rest-store-controller.php
  deprecated/class-dokan-email.php
  deprecated/class-dokan-rest-controller.php
  deprecated/class-dokan-rest-product-controller.php
  deprecated/class-dokan-rest-store-controller.php
  deprecated/class-dokan-seller-setup-wizard.php
  deprecated/class-dokan-store-category-walker.php
  deprecated/class-dokan-store-location-widget.php
  deprecated/class-dokan-template-dashboard.php
  deprecated/class-dokan-template-products.php
  deprecated/class-dokan-template-settings.php
  deprecated/class-dokan-vendor.php
  deprecated/class-dokan-withdraw.php
  deprecated/deprecated-classes.php
  deprecated/deprecated-functions.php
  deprecated/deprecated-hooks.php
  includes/Abstracts/DokanRESTBaseController.php
  includes/Abstracts/DokanRESTCustomerController.php
  includes/Abstracts/DokanRESTVendorController.php
Labels: Bump Version

#2579 refactor: `str_replace` warning fix for `OrderController`
  includes/REST/OrderController.php
Labels: :+1: Dev Review Done, Need Dev Review Only

#2405 enhance: Update vendor analytics report UI.
  assets/js/dokan-maps-compat.js
  assets/js/vue-admin.js
  assets/js/vue-bootstrap.js
  assets/src/js/dokan-admin-analytics.js
  includes/Analytics/Assets.php
  includes/Analytics/Reports/DataStoreCacheModifier.php
  includes/Analytics/VendorDashboardManager.php
  includes/Assets.php
  includes/Dashboard/Templates/Products.php
  includes/DependencyManagement/Providers/AnalyticsServiceProvider.php
  includes/Utilities/ProductUtil.php
  includes/Utilities/ReportUtil.php
  includes/functions.php
  src/vendor-dashboard/reports/analytics/report/stock/table.js
  src/vendor-dashboard/reports/analytics/report/variations/table.js
  src/vendor-dashboard/reports/dashboard/components/vendor-earning.js
  src/vendor-dashboard/reports/dashboard/customizable.js
  src/vendor-dashboard/reports/dashboard/dashboard-charts/block.js
  src/vendor-dashboard/reports/dashboard/dashboard-charts/config.js
  src/vendor-dashboard/reports/dashboard/index.js
  src/vendor-dashboard/reports/dokan-config.js
  src/vendor-dashboard/reports/header/index.js
  src/vendor-dashboard/reports/helper.ts
  src/vendor-dashboard/reports/index.js
  src/vendor-dashboard/reports/layout/index.js
  src/vendor-dashboard/reports/layout/style.scss
  src/vendor-dashboard/reports/seller-filter.js
  src/vendor-dashboard/reports/utils/admin-settings.js
  templates/products/products-listing.php
Labels: Needs: Testing, dependencies, Needs: Dev Review, Bump Version

#2564 Update/handle deprecated code from dokan
  deprecated/Singleton.php
  deprecated/class-abstract-class-dokan-background-processes.php
  deprecated/class-abstrct-dokan-rest-store-controller.php
  deprecated/class-dokan-email.php
  deprecated/class-dokan-rest-controller.php
  deprecated/class-dokan-rest-product-controller.php
  deprecated/class-dokan-rest-store-controller.php
  deprecated/class-dokan-seller-setup-wizard.php
  deprecated/class-dokan-store-category-walker.php
  deprecated/class-dokan-store-location-widget.php
  deprecated/class-dokan-template-dashboard.php
  deprecated/class-dokan-template-products.php
  deprecated/class-dokan-template-settings.php
  deprecated/class-dokan-vendor.php
  deprecated/class-dokan-withdraw.php
  deprecated/deprecated-classes.php
  deprecated/deprecated-functions.php
  deprecated/deprecated-hooks.php
  includes/Abstracts/DokanShortcode.php
  includes/REST/StoreController.php
  includes/functions.php
Labels: :+1: Dev Review Done, urgent, Upcoming Release

#2534 fix: unsupported operand types: string in calculation
  includes/Commission.php
Labels: QA approved, :+1: Dev Review Done, Upcoming Release

#2569 update: Sync Decimal Points with WooCommerce
  assets/src/js/product-editor.js
  includes/REST/CommissionControllerV1.php
  src/admin/components/Currency.vue
  templates/orders/commission-meta-box-html.php
  templates/orders/listing.php
  templates/products/edit-product-single.php
Labels: QA approved, :+1: Dev Review Done, urgent, Upcoming Release

#2573 fix: Elementor my account widget assets not loading in dokan registration form.
  assets/src/less/login-form-popup.less
  includes/template-tags.php
Labels: QA approved, :+1: Dev Review Done, Upcoming Release

#2574 fix: Seller revoking permission not denied for Digital product.
  templates/orders/order-download-permission-html.php
Labels: QA approved, :+1: Dev Review Done, Upcoming Release

#2575 Withdraw charge and receivable amount added in email template
  includes/Emails/VendorWithdrawRequest.php
  includes/Emails/WithdrawApproved.php
  includes/Emails/WithdrawCancelled.php
  includes/Withdraw/Hooks.php
  includes/Withdraw/Manager.php
  templates/emails/withdraw-approve.php
  templates/emails/withdraw-cancel.php
  templates/emails/withdraw-new.php
Labels: QA approved, :+1: Dev Review Done, urgent, Upcoming Release

#2550 fix: setup store country state validation
  includes/Vendor/SetupWizard.php
Labels: QA approved, :+1: Dev Review Done, urgent, Upcoming Release

#2602 refactor: Improve coupon validation with extensible filter hook
  includes/Order/Hooks.php
Labels: Needs: Testing, :+1: Dev Review Done, Upcoming Release, Bump Version

#2493 Feat/vendor coupon distribution
  includes/Order/Manager.php
  includes/Vendor/Coupon.php
  includes/Vendor/Hooks.php
  tests/php/src/Coupon/CouponTest.php
Labels: Needs: Testing, :+1: Dev Review Done, Bump Version

#2600 update: color scheme with current new brand colors
  assets/src/less/admin.less
  assets/src/less/dashboard.less
  assets/src/less/extra.less
  assets/src/less/notice.less
  assets/src/less/products.less
  assets/src/less/site-navigation.less
  assets/src/less/style.less
  assets/src/less/withdraw.less
  base-tailwind.config.js
  includes/Assets.php
  includes/Vendor/UserSwitch.php
  src/admin/components/Commission/CategoryBasedCommission.vue
  src/base-tailwind.scss
  src/dashboard/withdraw/tailwind.scss
  tests/pw/utils/dbData.ts
  tests/pw/utils/testData.ts
Labels: Needs: Testing, Needs: Dev Review, Bump Version

#2613 Update: button, alerts, label colors corresponding dokan brand colors
  assets/src/less/alerts.less
  assets/src/less/label.less
  assets/src/less/style.less
  templates/dashboard/edit-account.php
  templates/orders/date-export.php
  templates/reverse-withdrawal/filters.php
  templates/settings/payment-manage.php
  templates/settings/store-form.php
Labels: Needs: Dev Review, Need Dev Review Only

#2618 Fix: fix tests for google map layout changers
  .github/workflows/e2e_api_tests.yml
  tests/pw/package-lock.json
  tests/pw/package.json
  tests/pw/pages/selectors.ts
Labels: QA approved, Test Automation

#2607 added global capabilities checking
  .eslintrc
  docs/frontend/stores.md
  src/dashboard/index.tsx
  src/hooks/index.tsx
  src/hooks/usePermission.ts
  src/layout/403.tsx
  src/layout/ContentArea.tsx
  src/layout/Skeleton.tsx
  src/layout/index.tsx
  src/routing/index.tsx
  src/routing/routes.tsx
  templates/dashboard/new-dashboard.php
  tsconfig.json
Labels: Need Dev Review Only

#2620 Refactor: withdraw current user hooks
  docs/frontend/stores.md
  src/dashboard/withdraw/WithdrawRequests.tsx
  src/dashboard/withdraw/index.tsx
  src/hooks/useCurrentUser.ts
  webpack.config.js
Labels: Need Dev Review Only

#2597 feat: Dokan admin onboarding rest api (PR-1)
  assets/images/store-growth-logo.svg
  includes/Admin/RecommendedPlugins.php
  includes/Admin/SetupWizard.php
  includes/REST/AdminOnboardingController.php
  includes/REST/Manager.php
  tests/php/src/REST/AdminOnboardingControllerTest.php
  tests/pw/pages/adminPage.ts
  tests/pw/pages/commissionPage.ts
  tests/pw/pages/selectors.ts
Labels: Needs: Testing, Needs: Dev Review
