Repository getdokan/dokan, pull requests merged in 2025-09, with the labels that each got.

#2766 enhance: Implement send email button and popup for vendor communication. (Base Vendor Redesign)
  includes/Admin/Dashboard/Dashboard.php
  includes/Dashboard/Templates/Settings.php
  includes/REST/StoreSettingController.php
  src/admin/dashboard/icons/payments/Bank.tsx
  src/admin/dashboard/icons/payments/Custom.tsx
  src/admin/dashboard/icons/payments/DPaypal.tsx
  src/admin/dashboard/icons/payments/DStripe.tsx
  src/admin/dashboard/icons/payments/IconWrapper.tsx
  src/admin/dashboard/icons/payments/MangopayNew.tsx
  src/admin/dashboard/icons/payments/Paypal.tsx
  src/admin/dashboard/icons/payments/Razorpay.tsx
  src/admin/dashboard/icons/payments/Skrill.tsx
  src/admin/dashboard/icons/payments/Stripe.tsx
  src/admin/dashboard/pages/vendors-single/HeaderNavigation.tsx
  src/admin/dashboard/pages/vendors-single/InfoCard.tsx
  src/admin/dashboard/pages/vendors-single/InformationTabs/GeneralTab.tsx
  src/admin/dashboard/pages/vendors-single/InformationTabs/OverviewTab.tsx
  src/admin/dashboard/pages/vendors-single/InformationTabs/Withdraw/FormModal.tsx
  src/admin/dashboard/pages/vendors-single/InformationTabs/Withdraw/Forms/Bank.tsx
  src/admin/dashboard/pages/vendors-single/InformationTabs/Withdraw/Forms/Custom.tsx
  src/admin/dashboard/pages/vendors-single/InformationTabs/Withdraw/Forms/PayPal.tsx
  src/admin/dashboard/pages/vendors-single/InformationTabs/Withdraw/Forms/Skrill.tsx
  src/admin/dashboard/pages/vendors-single/InformationTabs/Withdraw/MethodAction.tsx
  src/admin/dashboard/pages/vendors-single/InformationTabs/Withdraw/WithdrawPaymentRow.tsx
  src/admin/dashboard/pages/vendors-single/InformationTabs/WithdrawTab.tsx
  src/admin/dashboard/pages/vendors-single/InformationTabs/WithdrawTabSkeleton.tsx
  src/admin/dashboard/pages/vendors-single/SendEmail.tsx
  src/admin/dashboard/pages/vendors-single/Skeletons/SkelitonLoader.tsx
  src/admin/dashboard/pages/vendors-single/Skeletons/TopProductSkeleton.tsx
  src/admin/dashboard/pages/vendors-single/TabSections.tsx
  src/admin/dashboard/pages/vendors-single/components/ProductCard.tsx
  src/admin/dashboard/pages/vendors-single/components/SectionHeading.tsx
  src/admin/dashboard/pages/vendors-single/index.tsx
  src/components/NoInformation.tsx
  src/components/Popover.tsx
  src/components/index.tsx
  src/definitions/dokan-vendors.ts
  src/stores/vendors/actions.ts
  src/stores/vendors/defaultState.ts
  src/stores/vendors/reducer.ts
  src/stores/vendors/resolvers.ts
  src/stores/vendors/selectors.ts
Labels: Dev Review Done

#2839 chore: Manage League Container package through mozart
  .github/workflows/deploy.yml
  .gitignore
  composer.json
  includes/DependencyManagement/BaseServiceProvider.php
  lib/packages/League/Container/Argument/ArgumentInterface.php
  lib/packages/League/Container/Argument/ArgumentResolverInterface.php
  lib/packages/League/Container/Argument/ArgumentResolverTrait.php
  lib/packages/League/Container/Argument/DefaultValueArgument.php
  lib/packages/League/Container/Argument/DefaultValueInterface.php
  lib/packages/League/Container/Argument/Literal/ArrayArgument.php
  lib/packages/League/Container/Argument/Literal/BooleanArgument.php
  lib/packages/League/Container/Argument/Literal/CallableArgument.php
  lib/packages/League/Container/Argument/Literal/FloatArgument.php
  lib/packages/League/Container/Argument/Literal/IntegerArgument.php
  lib/packages/League/Container/Argument/Literal/ObjectArgument.php
  lib/packages/League/Container/Argument/Literal/StringArgument.php
  lib/packages/League/Container/Argument/LiteralArgument.php
  lib/packages/League/Container/Argument/LiteralArgumentInterface.php
  lib/packages/League/Container/Argument/ResolvableArgument.php
  lib/packages/League/Container/Argument/ResolvableArgumentInterface.php
  lib/packages/League/Container/Container.php
  lib/packages/League/Container/ContainerAwareInterface.php
  lib/packages/League/Container/ContainerAwareTrait.php
  lib/packages/League/Container/Definition/Definition.php
  lib/packages/League/Container/Definition/DefinitionAggregate.php
  lib/packages/League/Container/Definition/DefinitionAggregateInterface.php
  lib/packages/League/Container/Definition/DefinitionInterface.php
  lib/packages/League/Container/DefinitionContainerInterface.php
  lib/packages/League/Container/Exception/ContainerException.php
  lib/packages/League/Container/Exception/NotFoundException.php
  lib/packages/League/Container/Inflector/Inflector.php
  lib/packages/League/Container/Inflector/InflectorAggregate.php
  lib/packages/League/Container/Inflector/InflectorAggregateInterface.php
  lib/packages/League/Container/Inflector/InflectorInterface.php
  lib/packages/League/Container/ReflectionContainer.php
  lib/packages/League/Container/ServiceProvider/AbstractServiceProvider.php
  lib/packages/League/Container/ServiceProvider/BootableServiceProviderInterface.php
  lib/packages/League/Container/ServiceProvider/ServiceProviderAggregate.php
  lib/packages/League/Container/ServiceProvider/ServiceProviderAggregateInterface.php
  lib/packages/League/Container/ServiceProvider/ServiceProviderInterface.php
  lib/packages/Psr/Container/ContainerExceptionInterface.php
  lib/packages/Psr/Container/ContainerInterface.php
  lib/packages/Psr/Container/NotFoundExceptionInterface.php
Labels: Dev Review Done, Need Dev Review Only

#2818 feat: add caching support to BaseModel for save and delete operations
  docs/data-store.md
  includes/Models/BaseModel.php
Labels: Dev Review Done, Need Dev Review Only

#2900 feat: Implement DokanTooltip and use it across the system.
  docs/frontend/components.md
  src/admin/dashboard/pages/modules/Card.tsx
  src/components/DokanTooltip.tsx
  src/components/VisitStore.tsx
  src/components/index.tsx
  src/intelligence/components/DokanAI.tsx
Labels: Needs: Dev Review

#2837 style: enhance dokan admin layout and spacing for improved UI
  assets/src/less/admin.less
  assets/src/less/global-admin.less
  src/admin/App.vue
  src/admin/banner/AdminSetupBanner.tsx
  src/admin/banner/SetupGuideBanner.tsx
Labels: :tada: QA Approved, Dev Review Done, Upcoming Release

#2823 Conditionally display commission and related order metaboxes in order details
  includes/Order/Admin/Hooks.php
  includes/wc-template.php
Labels: :tada: QA Approved, Dev Review Done, Upcoming Release
