Repository getdokan/dokan, pull requests merged in 2025-07, with the labels that each got.

#2747 fix: add gradient background style for fa-threads social icon
  assets/src/less/store.less
Labels: QA approved, :+1: Dev Review Done, Upcoming Release

#2765 Fix incorrect timestamp on sale price schedule from vendor dashboard
  includes/wc-functions.php
  templates/products/edit-product-single.php
Labels: QA approved, :+1: Dev Review Done, Upcoming Release, PM Dependency

#2346 feat: Dokan Data Store
  docs/data-store.md
  includes/DependencyManagement/Providers/ModelServiceProvider.php
  includes/DependencyManagement/Providers/ServiceProvider.php
  includes/Models/BaseModel.php
  includes/Models/DataStore/BaseDataStore.php
  includes/Models/DataStore/DataStoreInterface.php
  includes/Models/DataStore/VendorBalanceStore.php
  includes/Models/VendorBalance.php
  includes/Order/functions.php
  tests/php/src/CustomAssertion/DBAssertionTrait.php
  tests/php/src/Models/VendorBalanceModelTest.php
Labels: Needs: Dev Review

#2785 Escape JSON data in vendor search dropdown
  includes/Admin/Hooks.php
Labels: QA approved, :+1: Dev Review Done, Upcoming Release

#2784 Add category_id to Product and ProductCommission for accurate commission calculation.
  includes/Commission/ProductCommission.php
  includes/Commission/Strategies/Product.php
Labels: QA approved, :+1: Dev Review Done, Upcoming Release

#2771 enhance: Admin notice UI
  assets/src/images/dokan-notice-logo.svg
  assets/src/less/global-admin.less
  src/admin/components/AdminNotice.vue
Labels: QA approved, :+1: Dev Review Done, Upcoming Release

#2760 enhance: Support add-ons conditionally for Dokan price input.
  src/components/PriceInput.tsx
Labels: QA approved, :+1: Dev Review Done, Upcoming Release

#2800 fix: "sold individually" option does not save on create or update a product
  includes/Dashboard/Templates/Products.php
  includes/wc-functions.php
  templates/products/inventory.php
Labels: QA approved, :+1: Dev Review Done, urgent, Upcoming Release

#2762 Improve image selection and cropping functionality in product editor
  assets/src/js/product-editor.js
Labels: QA approved, :+1: Dev Review Done, Upcoming Release

#2813 fix: resolve jquery-tiptip conflict with dompurify dependency
  includes/Admin/SetupWizard.php
  includes/Assets.php
Labels: QA approved, :+1: Dev Review Done, urgent
