Repository getdokan/dokan, pull requests merged in 2025-01, with the labels that each got.

#2468 [Skip] payment in Setup wizard when no payment is active
  includes/Admin/SetupWizard.php
  includes/Admin/SetupWizardNoWC.php
  includes/Vendor/SetupWizard.php
Labels: QA approved, :+1: Dev Review Done, Upcoming Release

#2487 fix(email-template): missing attribute
  includes/Emails/WithdrawApproved.php
  templates/emails/plain/product-published.php
Labels: QA approved, :+1: Dev Review Done, Upcoming Release, Assigned QA: Stalin

#2498 Refactor setup tests
  .github/workflows/e2e_api_tests.yml
  tests/pw/.gitignore
  tests/pw/.wp-env.json
  tests/pw/api.config.ts
  tests/pw/feature-map/feature-map.yml
  tests/pw/mu-plugins/disable-doing-it-wrong.php
  tests/pw/package-lock.json
  tests/pw/package.json
  tests/pw/pages/liveSearchPage.ts
  tests/pw/pages/selectors.ts
  tests/pw/pages/shipStationPage.ts
  tests/pw/tests/api/_auth.setup.ts
  tests/pw/tests/api/_env.setup.ts
  tests/pw/tests/api/_site.setup.ts
  tests/pw/tests/e2e/_auth.setup.ts
  tests/pw/tests/e2e/_localSite.setup.ts
  tests/pw/tests/e2e/_site.setup.ts
  tests/pw/tests/e2e/colors.spec.ts
  tests/pw/tests/e2e/plugin.spec.ts
  tests/pw/tests/e2e/shipstation.spec.ts
  tests/pw/tests/e2e/singleProduct.spec.ts
  tests/pw/tests/e2e/stores.spec.ts
  tests/pw/tsconfig.json
  tests/pw/types/environment.d.ts
  tests/pw/utils/apiUtils.ts
  tests/pw/utils/dbUtils.ts
  tests/pw/utils/helpers.ts
  tests/pw/utils/payloads.ts
  tests/pw/utils/summaryReporter.ts
Labels: QA approved, Test Automation

#2475 Enhance: Admin settings page responsive
  assets/src/less/admin.less
  assets/src/less/global-admin.less
  includes/Admin/Settings.php
  src/admin/components/AdminNotice.vue
  src/admin/components/Settings/MobileSettingsList.vue
  src/admin/components/SettingsBanner.vue
  src/admin/pages/ChangeLog.vue
  src/admin/pages/Settings.vue
Labels: Type: Enhancement, QA approved, :+1: Dev Review Done, Upcoming Release

#2501 Enhance/several dokan admin panel responsive and css issues
  src/admin/pages/Settings.vue
Labels: QA approved

#2504 Add: playwright sharding for parallel test execution
  .github/workflows/e2e_api_tests.yml
  tests/pw/e2e.config.ts
  tests/pw/package-lock.json
  tests/pw/package.json
  tests/pw/pages/menuManagerPage.ts
  tests/pw/pages/productsPage.ts
  tests/pw/pages/vendorPage.ts
  tests/pw/tests/api/calculation.spec.ts
  tests/pw/tests/e2e/_auth.setup.ts
  tests/pw/tests/e2e/payments.spec.ts
  tests/pw/tests/e2e/productsDetails.spec.ts
  tests/pw/tests/e2e/shipstation.spec.ts
  tests/pw/tests/e2e/storeAppearance.spec.ts
  tests/pw/tests/e2e/storelisting.spec.ts
  tests/pw/types/environment.d.ts
  tests/pw/utils/mergeCoverageSummary.ts
  tests/pw/utils/mergeSummaryReport.ts
  tests/pw/utils/summaryReporter.ts
  tests/pw/utils/testData.ts
Labels: QA approved, Test Automation

#2503 🎯 fix: Translation on some pages were not working due to wrong text-domains
  assets/src/js/setup-wizard/commission/AdminCommission.vue
  includes/Admin/WithdrawLogExporter.php
  src/admin/components/AddReverseWithdraw.vue
  src/admin/pages/DummyData.vue
  src/admin/pages/VendorSingle.vue
  src/admin/pages/Withdraw.vue
Labels: QA approved, :+1: Dev Review Done, urgent

#2500 feat: dokan status page
  base-tailwind.config.js
  includes/Abstracts/StatusElement.php
  includes/Admin/Status/Button.php
  includes/Admin/Status/Heading.php
  includes/Admin/Status/Link.php
  includes/Admin/Status/Page.php
  includes/Admin/Status/Paragraph.php
  includes/Admin/Status/Section.php
  includes/Admin/Status/Status.php
  includes/Admin/Status/SubSection.php
  includes/Admin/Status/Tab.php
  includes/Admin/Status/Table.php
  includes/Admin/Status/TableColumn.php
  includes/Admin/Status/TableRow.php
  includes/DependencyManagement/Providers/AdminServiceProvider.php
  includes/REST/AdminDashboardController.php
  includes/VendorNavMenuChecker.php
  package.json
  src/Status/Elements/Button.tsx
  src/Status/Elements/Heading.tsx
  src/Status/Elements/Link.tsx
  src/Status/Elements/Paragraph.tsx
  src/Status/Elements/Section.tsx
  src/Status/Elements/SubSection.tsx
  src/Status/Elements/Table.tsx
  src/Status/Elements/TableColumn.tsx
  src/Status/Elements/TableRow.tsx
  src/Status/Menu.tsx
  src/Status/SettingsParser.tsx
  src/Status/Status.tsx
  src/Status/Tab.tsx
  src/Status/index.tsx
  src/Status/status-tailwind.config.js
  src/Status/status.scss
  webpack.config.js
Labels: Needs: Testing, Needs: Dev Review

#2497 enhance: Introduce dataviews component and update webpack.
  docs/frontend/components.md
  docs/frontend/dataviews.md
  docs/frontend/hooks.md
  docs/frontend/utilities.md
  includes/Assets.php
  package-lock.json
  package.json
  src/components/dataviews/DataViewTable.tsx
  src/components/dataviews/style.scss
  src/components/index.tsx
  src/dashboard/index.tsx
  src/dashboard/tailwind.scss
  src/hooks/ViewportDimensions.tsx
  src/hooks/index.tsx
  src/layout/404.tsx
  src/layout/ContentArea.tsx
  src/layout/Footer.tsx
  src/layout/Header.tsx
  src/layout/Sidebar.tsx
  src/layout/index.tsx
  src/routing/index.tsx
  src/utilities/ChangeCase.ts
  src/utilities/index.ts
  webpack-entries.js
  webpack.config.js
Labels: Needs: Dev Review

#2521 enhance: Introduce Dokan Draggable/Sortable List Component.
  docs/frontend/sortable-list.md
  package-lock.json
  package.json
  src/components/index.tsx
  src/components/sortable-list/SortableItem.tsx
  src/components/sortable-list/index.tsx
  webpack.config.js
Labels: :+1: Dev Review Done, Need Dev Review Only

#2524 revert: Re-Introduce WordPress necessary packages.
  package.json
Labels: :+1: Dev Review Done

#2527 Add: woocommerce site visiblity setup for test environment setup
  .github/workflows/e2e_api_tests.yml
  tests/pw/pages/customerPage.ts
  tests/pw/pages/selectors.ts
  tests/pw/pages/vendorDeliveryTimePage.ts
  tests/pw/tests/api/_env.setup.ts
  tests/pw/tests/e2e/_env.setup.ts
  tests/pw/tests/e2e/customer.spec.ts
  tests/pw/tests/e2e/vendorDeliveryTime.spec.ts
Labels: Test Automation

#2506 [Re-Enginrring] withdraw page
  includes/Assets.php
  includes/Dashboard/Templates/NewDashboard.php
  includes/REST/WithdrawController.php
  includes/REST/WithdrawControllerV2.php
  includes/VendorNavMenuChecker.php
  includes/functions-dashboard-navigation.php
  package.json
  src/components/DateTimeHtml.tsx
  src/components/PriceHtml.tsx
  src/components/index.tsx
  src/dashboard/Withdraw/Balance.tsx
  src/dashboard/Withdraw/Hooks/useBalance.ts
  src/dashboard/Withdraw/Hooks/useCharge.ts
  src/dashboard/Withdraw/Hooks/useMakeDefaultMethod.ts
  src/dashboard/Withdraw/Hooks/useWithdraw.ts
  src/dashboard/Withdraw/Hooks/useWithdrawRequests.ts
  src/dashboard/Withdraw/Hooks/useWithdrawSettings.ts
  src/dashboard/Withdraw/PaymentDetails.tsx
  src/dashboard/Withdraw/PaymentMethods.tsx
  src/dashboard/Withdraw/RequestList.tsx
  src/dashboard/Withdraw/RequestWithdrawBtn.tsx
  src/dashboard/Withdraw/WithdrawRequests.tsx
  src/dashboard/Withdraw/index.tsx
  src/dashboard/Withdraw/tailwind.scss
  src/definitions/RouterProps.ts
  src/definitions/window-types.ts
  src/definitions/woocommerce-accounting.d.ts
  src/hooks/index.tsx
  src/hooks/useCurrentUser.ts
  src/routing/index.tsx
  src/utilities/Accounting.ts
  src/utilities/index.ts
  webpack.config.js
Labels: Needs: Testing, :+1: Dev Review Done

#2531 enhance: Update dokan src package root name.
  docs/frontend/components.md
  docs/frontend/dataviews.md
  docs/frontend/filter.md
  docs/frontend/hooks.md
  docs/frontend/sortable-list.md
  docs/frontend/utilities.md
  src/components/PriceHtml.tsx
  src/components/dataviews/DataViewTable.tsx
  src/components/sortable-list/index.tsx
  src/dashboard/Withdraw/RequestList.tsx
  src/dashboard/Withdraw/RequestWithdrawBtn.tsx
  src/dashboard/Withdraw/WithdrawRequests.tsx
  src/dashboard/Withdraw/index.tsx
  src/hooks/index.tsx
  src/utils/Bootstrap.js
  webpack.config.js
Labels: Need Dev Review Only

#2537 Add: Form manager tests
  tests/pw/pages/basePage.ts
  tests/pw/pages/menuManagerPage.ts
  tests/pw/pages/productFormManagerPage.ts
  tests/pw/pages/selectors.ts
  tests/pw/tests/api/admin.spec.ts
  tests/pw/tests/e2e/productFormManager.spec.ts
  tests/pw/utils/apiEndPoints.ts
  tests/pw/utils/dbData.ts
  tests/pw/utils/interfaces.ts
  tests/pw/utils/mergeCoverageSummary.ts
  tests/pw/utils/mergeSummaryReport.ts
  tests/pw/utils/payloads.ts
  tests/pw/utils/schemas.ts
  tests/pw/utils/summaryReporter.ts
  tests/pw/utils/testData.ts
Labels: Test Automation

#2474 fix: invalid product id validation on edit page
  templates/products/edit-product-single.php
Labels: QA approved, :+1: Dev Review Done, urgent, Upcoming Release

#2482 fix: args missing issue for reverse-withdrawal API endpoints
  includes/REST/DummyDataController.php
  includes/REST/ReverseWithdrawalController.php
Labels: QA approved, :+1: Dev Review Done, Upcoming Release

#2483 fix: args updated for Settings API endpoints
  includes/REST/StoreSettingControllerV2.php
Labels: QA approved, :+1: Dev Review Done, Upcoming Release

#2513 Enhance: dokan plugin header logo banner icon enhancement
  assets/src/less/admin.less
  assets/src/less/global-admin.less
  includes/Admin/Menu.php
  src/admin/pages/ChangeLog.vue
  src/admin/pages/Dashboard.vue
  src/admin/pages/Help.vue
  src/admin/pages/Settings.vue
  src/admin/pages/Vendors.vue
  src/admin/pages/Withdraw.vue
  templates/admin-header.php
Labels: QA approved, :+1: Dev Review Done, Upcoming Release

#2516 fix: misspelling typo vendor contact form input field
  templates/widgets/store-contact-form.php
Labels: QA approved, :+1: Dev Review Done, Upcoming Release

#2520 update: url of upgrade button of pro
  templates/admin-header.php
Labels: QA approved, :+1: Dev Review Done, urgent, Upcoming Release

#2522 update: tab-wrapper z-index to fix modal conflict
  src/admin/pages/Settings.vue
Labels: QA approved, :+1: Dev Review Done, Upcoming Release

#2529 enhance: Add analytics cache modifier for seller analytics filter.
  includes/Analytics/Reports/BaseQueryFilter.php
  includes/Analytics/Reports/CacheKeyModifier.php
  includes/DependencyManagement/Providers/AnalyticsServiceProvider.php
Labels: QA approved, :+1: Dev Review Done, Upcoming Release

#2536 chore: Author name, URL, and email change
  composer.json
  dokan.php
  package.json
  readme.txt
Labels: QA approved, :+1: Dev Review Done, Upcoming Release

#2533 Vendor dashboard finetune withdraw
  base-tailwind.config.js
  includes/Dashboard/Templates/NewDashboard.php
  includes/Withdraw/Hooks.php
  package.json
  src/base-tailwind.scss
  src/dashboard/Withdraw/RequestList.tsx
  src/dashboard/Withdraw/RequestWithdrawBtn.tsx
  src/definitions/window-types.ts
  src/utilities/Accounting.ts
Labels: Need Dev Review Only

#2541 Remove: pro-banner test
  tests/pw/pages/menuManagerPage.ts
  tests/pw/pages/noticeAndPromotionPage.ts
  tests/pw/pages/selectors.ts
  tests/pw/tests/e2e/productFormManager.spec.ts
  tests/pw/tests/e2e/vendorDeliveryTime.spec.ts
  tests/pw/utils/interfaces.ts
  tests/pw/utils/mergeSummaryReport.ts
Labels: QA approved, Test Automation
