Repository getdokan/dokan, pull requests merged in 2025-08, with the labels that each got.

#2833 Dokan RichText Component
  docs/frontend/richtext.md
  package.json
  src/components/index.tsx
  src/components/richtext/RichText.tsx
  src/components/richtext/styles.scss
  src/utilities/SanitizeHtml.ts
  src/utilities/index.ts
Labels: Dev Review Done

#2792 🧩 enhance: Close button visibility support for DokanModal component
  src/components/modals/DokanModal.tsx
Labels: Needs: Testing, Dev Review Done

#2838 enhance: Implement menu manager component for admin settings.
  includes/Abstracts/SettingsElement.php
  includes/Admin/Settings/Elements/Field.php
  includes/Admin/Settings/Elements/Fields/Repeater.php
  includes/Admin/Settings/Elements/Fields/RichText.php
  includes/Admin/Settings/Elements/Fields/Switcher.php
  includes/Admin/Settings/Pages/AppearancePage.php
  includes/DependencyManagement/Providers/AdminSettingsServiceProvider.php
  package-lock.json
  src/admin/dashboard/pages/settings/Elements/Fields/DokanRepeater.tsx
  src/admin/dashboard/pages/settings/Elements/Fields/DokanRichText.tsx
  src/admin/dashboard/pages/settings/Elements/Fields/DokanSwitch.tsx
  src/admin/dashboard/pages/settings/Elements/Fields/FieldParser.tsx
  src/admin/dashboard/pages/settings/Elements/Menu.tsx
  src/admin/dashboard/pages/settings/Elements/PageHeading.tsx
  src/admin/dashboard/pages/settings/Elements/Section.tsx
  src/admin/dashboard/pages/settings/Elements/SubSection.tsx
  src/admin/dashboard/pages/settings/Elements/Tab.tsx
  src/admin/dashboard/pages/settings/index.tsx
  src/admin/dashboard/pages/settings/types.ts
  src/admin/dashboard/style.scss
  src/components/Icons/InfoIcon.tsx
  src/components/Tab.tsx
  src/components/fields/DokanFieldLabel.tsx
  src/components/fields/DokanTimePicker.tsx
  src/components/fields/DokanTooltip.tsx
  src/components/fields/index.tsx
  src/components/index.tsx
  src/components/modals/DokanModal.tsx
  src/components/sortable-list/index.tsx
  src/stores/adminSettings/types.ts
Labels: Needs: Dev Review

#2834 Feat:admin settings preview field
  includes/Admin/Settings/Elements/Field.php
  includes/Admin/Settings/Elements/Fields/SingleProductPreview.php
  includes/Admin/Settings/Elements/Fields/VendorInfoPreview.php
  src/admin/dashboard/pages/settings/Elements/Fields/DokanSingleProductPreview.tsx
  src/admin/dashboard/pages/settings/Elements/Fields/DokanVendorInfoPreview.tsx
  src/admin/dashboard/pages/settings/Elements/Fields/FieldParser.tsx
Labels: Needs: Dev Review

#2827 enhance: dokan double input field
  includes/Admin/Settings/Elements/Field.php
  includes/Admin/Settings/Elements/Fields/DoubleInput.php
  includes/Admin/Settings/Elements/Fields/DoubleTextField.php
  src/admin/dashboard/pages/settings/Elements/Fields/DokanDoubleInput.tsx
  src/admin/dashboard/pages/settings/Elements/Fields/FieldParser.tsx
Labels: Need Dev Review Only

#2779 enhance: Update README.md for Dokan development setup and guidelines
  README.md
  package.json
Labels: Dev Review Done, Need Dev Review Only, Upcoming Release

#2875 fix: Menu Manager activation test failed for WooCommerce Subscriptions missing.
  tests/pw/pages/basePage.ts
  tests/pw/tests/e2e/menuManager.spec.ts
Labels: Need Dev Review Only

#2874 fix: Shortcode templates fields not exists issue.
  tests/pw/pages/selectors.ts
  tests/pw/pages/shortcodePage.ts
Labels: Need Dev Review Only

#2873 fix: Update vendor verification methods visibility tests for setup wizard.
  tests/pw/pages/vendorVerificationsPage.ts
  tests/pw/tests/e2e/vendorVerifications.spec.ts
Labels: Need Dev Review Only

#2872 fix: Coupon creation execution by ensuring proper load state and validation.
  tests/pw/pages/couponsPage.ts
  tests/pw/pages/selectors.ts
Labels: Need Dev Review Only

#2871 fix: Min-max quantity interaction test with invalid data.
  tests/pw/pages/productsPage.ts
Labels: Need Dev Review Only

#2862 fix: setup guide not found issue
  tests/pw/tests/e2e/setupGuide.spec.ts
Labels: Needs: Testing, Needs: Dev Review

#2870 fix: skip live chat tests when credentials are not available
  tests/pw/tests/e2e/liveChat.spec.ts
Labels: Needs: Testing, Needs: Dev Review

#2869 fix: skip live chat settings test if credentials are not provided and…
  tests/pw/tests/e2e/vendorSettings.spec.ts
  tests/pw/utils/dbUtils.ts
Labels: Needs: Testing, Needs: Dev Review

#2854 Fix setup wizard test
  tests/pw/pages/selectors.ts
Labels: Needs: Testing, Needs: Dev Review

#2856 fix: product-advertisemnet test case
  tests/pw/pages/basePage.ts
  tests/pw/pages/vendorAuctionsPage.ts
  tests/pw/pages/vendorPage.ts
  tests/pw/utils/testData.ts
Labels: Needs: Testing, Needs: Dev Review

#2881 enhance: Update webpack configuration for Dokan dependency packages external loads.
  includes/Assets.php
  src/admin/onboard/OnBoardApp.tsx
  src/admin/onboard/components/BackButton.tsx
  src/admin/onboard/components/NextButton.tsx
  src/admin/onboard/screens/AddonsScreen.tsx
  src/admin/onboard/screens/BasicInfoScreen.tsx
  src/admin/onboard/screens/MarketplaceGoalScreen.tsx
  src/admin/onboard/screens/WelcomeScreen.tsx
  src/admin/onboard/utility/stepUtils.ts
  src/components/Filter.tsx
  src/dashboard/index.tsx
  src/hooks/index.tsx
  src/layout/403.tsx
  src/layout/404.tsx
  src/layout/500.tsx
  src/routing/routes.tsx
  src/utils/Bootstrap.js
  webpack-dependency-mapping.js
  webpack.config.js
Labels: Dev Review Done, Need Dev Review Only

#2844 Fix: Admin not receiving withdrawal request email notifications
  includes/Emails/VendorWithdrawRequest.php
Labels: :tada: QA Approved, Dev Review Done, Upcoming Release

#2791 Added translation support for dashboard analytics report scripts
  includes/Analytics/Assets.php
  src/dashboard/withdraw/RequestWithdrawBtn.tsx
Labels: :tada: QA Approved, Dev Review Done, Upcoming Release

#2786 fix: conditionally hide commission metabox for advertisement product orders
  includes/Order/Admin/Hooks.php
Labels: :tada: QA Approved, Dev Review Done, Upcoming Release

#2275 enhance: Implement vendor default banner, profile image & controls.
  assets/images/default-store-banner.png
  assets/images/mystery-person.jpg
  assets/src/less/store.less
  includes/Admin/Settings.php
  includes/Admin/UserProfile.php
  includes/Dashboard/Templates/Settings.php
  includes/Utilities/VendorUtil.php
  includes/Vendor/Vendor.php
  src/admin/components/FieldHeading.vue
  src/admin/components/Fields.vue
  src/admin/components/UploadImage.vue
  src/admin/pages/VendorAccountFields.vue
  src/admin/pages/VendorSingle.vue
  src/admin/pages/Vendors.vue
  templates/settings/store-form.php
  templates/store-lists-loop.php
Labels: :tada: QA Approved, Dev Review Done
