Repository getdokan/dokan, pull requests merged in 2025-06, with the labels that each got.

#2755 fix: validate taxonomy existence before rendering options in Taxonomydropdown walker
  includes/Walkers/TaxonomyDropdown.php
Labels: Needs: Testing, :+1: Dev Review Done, urgent, Upcoming Release

#2750 Fix clarify AI output language guidelines in response
  includes/Intelligence/Services/ChatgptResponseService.php
  includes/Intelligence/Services/GeminiResponseService.php
Labels: :+1: Dev Review Done, Upcoming Release, QA Approved (Shahed)

#2754 fix: Admin reports order data not reflecting after updated the orders data.
  includes/Commission.php
  includes/Order/VendorBalanceUpdateHandler.php
  includes/Traits/ObjectCache.php
Labels: :+1: Dev Review Done, Upcoming Release, QA Approved : Shohan

#2730 enhance: Add dokan UI standard documentation for vendor dashboard page.
  docs/frontend/ui-standard.md
Labels: :+1: Dev Review Done, Need Dev Review Only
