Repository getdokan/dokan, pull requests merged in 2025-02, with the labels that each got.

#2510 Enhance/product category rest api
  includes/REST/Manager.php
  includes/REST/ProductCategoriesVendorController.php
  includes/REST/VendorProductCategoriesController.php
  tests/php/src/ProductCategory/ProductCategoryApiTest.php
  tests/php/src/ProductCategory/VendorProductCategoriesApiTest.php
Labels: Needs: Dev Review

#2525 enhance: Introduce DokanModal component.
  docs/frontend/dokan-modal.md
  docs/frontend/sortable-list.md
  src/components/index.tsx
  src/components/modals/DialogIcon.tsx
  src/components/modals/DokanModal.tsx
  src/layout/Header.tsx
Labels: :+1: Dev Review Done

#2436 Fix Analytics report test cases
  dokan-class.php
  includes/Analytics/Reports/BaseQueryFilter.php
  includes/Analytics/Reports/CacheKeyModifier.php
  includes/Analytics/Reports/DataStoreModifier.php
  includes/Analytics/Reports/Orders/Stats/QueryFilter.php
  includes/DependencyManagement/BaseServiceProvider.php
  includes/DependencyManagement/Providers/AjaxServiceProvider.php
  includes/DependencyManagement/Providers/AnalyticsServiceProvider.php
  includes/DependencyManagement/Providers/CommonServiceProvider.php
  includes/DependencyManagement/Providers/FrontendServiceProvider.php
  tests/php/src/Analytics/Reports/OrderQueryFilterTest.php
  tests/php/src/Analytics/Reports/OrderStatsQueryFilterTest.php
  tests/php/src/Analytics/Reports/ProductQueryFilterTest.php
  tests/php/src/Analytics/Reports/ProductStatsQueryFilterTest.php
  tests/php/src/Analytics/Reports/ReportTestCase.php
  tests/php/src/DokanFactoryTest.php
Labels: :+1: Dev Review Done, Need Dev Review Only

#2502 Fix several commission issues
  assets/src/js/product-editor.js
  assets/src/js/setup-wizard/commission/AdminCommission.vue
  includes/Commission.php
  includes/ProductCategory/Helper.php
  includes/REST/CommissionControllerV1.php
  src/admin/components/CombineInput.vue
  templates/products/edit-product-single.php
  tests/php/src/Commission/CommissionTest.php
Labels: QA approved, :+1: Dev Review Done, Dependency With Pro, Upcoming Release, Assigned QA: Stalin

#2545 Tax calculation for shipping based on tax status
  includes/Order/Manager.php
Labels: QA approved, :+1: Dev Review Done, Upcoming Release, Assigned QA: Stalin

#2535 update: Vendor store url additional endpoint support added
  includes/functions.php
Labels: QA approved, :+1: Dev Review Done, Upcoming Release, Assigned QA: Stalin

#2532 🛠 refactor: dokan_is_user_seller function
  includes/functions.php
Labels: :+1: Dev Review Done, Need Dev Review Only, Upcoming Release

#2476 feat: Product Rejection - Rollback product statuses on dokan pro deactivation (integration)
  includes/ProductStatusRollback.php
Labels: QA approved, :+1: Dev Review Done, Dependency With Pro, Upcoming Release, Assigned QA: Stalin

#2558 update: React Admin Dashboard Structure
  includes/Admin/Dashboard/Dashboard.php
  includes/Admin/Dashboard/Pageable.php
  includes/Admin/Dashboard/Pages/AbstractPage.php
  includes/Admin/Dashboard/Pages/Status.php
  includes/Admin/Status/Status.php
  includes/DependencyManagement/Providers/AdminDashboardServiceProvider.php
  includes/DependencyManagement/Providers/ServiceProvider.php
  src/Status/index.tsx
  src/admin/dashboard/admin-dashboard-tailwind.config.js
  src/admin/dashboard/components/Dashboard.tsx
  src/admin/dashboard/components/Header.tsx
  src/admin/dashboard/components/Layout.tsx
  src/admin/dashboard/index.tsx
  src/admin/dashboard/style.scss
  webpack-entries.js
Labels: Needs: Testing, :+1: Dev Review Done

#2568 chore: dokan-UI preflight added with `.dokan-layout`
  includes/Dashboard/Templates/NewDashboard.php
  package.json
  src/base-tailwind.scss
  src/dashboard/index.tsx
  src/hooks/index.tsx
  src/hooks/useMutationObserver.ts
Labels: :+1: Dev Review Done, Need Dev Review Only

#2566 Replace `DOKAN_PRO_SINCE` with corresponding versions.
  assets/src/js/helper.js
  includes/Abstracts/DokanRESTBaseController.php
  includes/Abstracts/DokanRESTCustomerController.php
  includes/Abstracts/DokanRESTVendorController.php
  includes/Commission/Upugrader/Update_Category_Commission.php
  includes/Commission/Upugrader/Update_Product_Commission.php
  includes/Commission/Upugrader/Update_Vendor_Commission.php
  includes/Dashboard/Templates/Settings.php
  includes/ProductStatusRollback.php
  includes/Widgets/FilterByAttributes.php
  includes/functions-dashboard-navigation.php
  includes/functions.php
  templates/products/edit-product-single.php
  templates/products/products-listing-row.php
Labels: :+1: Dev Review Done, Need Dev Review Only

#2552 chore: `DOKAN_PRO_SINCE` support added
  bin/version-replace.js
Labels: :+1: Dev Review Done, Need Dev Review Only

#2553 update: `[dokan-customer-migration]` shortcode migrated from pro.
  includes/Shortcodes/CustomerMigration.php
  includes/Shortcodes/Shortcodes.php
Labels: QA approved, :+1: Dev Review Done, Upcoming Release

#2557 Restoring parent order with restore related child orders
  includes/Order/Admin/Hooks.php
  includes/Order/Manager.php
  tests/php/src/Orders/OrderRestoreFromTrashTest.php
Labels: QA approved, :+1: Dev Review Done, Upcoming Release

#2571 fix: Store settings api stores inconsistent data for switcher fields.
  includes/REST/StoreController.php
Labels: QA approved, :+1: Dev Review Done, Upcoming Release

#2560 update: Extendability support on dokan post count and stock count added.
  includes/functions.php
Labels: QA approved, :+1: Dev Review Done, Upcoming Release, Assigned QA: Stalin
