Repository getdokan/dokan, pull requests merged in 2025-05, with the labels that each got.

#2695 Fix correct tax fee calculations in commission meta box
  templates/orders/commission-meta-box-html.php
Labels: Bump Version

#2698 Fix the Setting model
  includes/Commission/Calculator.php
  includes/Commission/Model/Setting.php
  includes/Commission/OrderLineItemCommission.php
  includes/Commission/ProductCommission.php
  includes/Commission/Settings/Vendor.php
  includes/Commission/Strategies/Vendor.php
  tests/php/src/Commission/CommissionCalculatorTest.php
Labels: Bump Version

#2635 docs: add environment setup documentation for Dokan Pro
  docs/frontend/env-setup.md
Labels: Needs: Dev Review, :+1: Dev Review Done, Bump Version

#2675 Feat/adjust commision for refund
  includes/Commission.php
  includes/Commission/AbstractCommissionCalculator.php
  includes/Commission/Calculator.php
  includes/Commission/Contracts/CommissionInterface.php
  includes/Commission/Contracts/OrderCommissionInterface.php
  includes/Commission/Model/Commission.php
  includes/Commission/Model/Setting.php
  includes/Commission/OrderCommission.php
  includes/Commission/OrderLineItemCommission.php
  includes/Commission/ProductCommission.php
  includes/Commission/Settings/DefaultSetting.php
  includes/Commission/Settings/GlobalSetting.php
  includes/Commission/Settings/InterfaceSetting.php
  includes/Commission/Settings/OrderItem.php
  includes/Commission/Settings/Product.php
  includes/Commission/Settings/Vendor.php
  includes/Commission/Strategies/AbstractStrategy.php
  includes/Commission/Strategies/DefaultStrategy.php
  includes/Commission/Strategies/GlobalStrategy.php
  includes/Commission/Strategies/OrderItem.php
  includes/Commission/Strategies/Product.php
  includes/Commission/Strategies/Vendor.php
  includes/DependencyManagement/Providers/CommissionServiceProvider.php
  includes/DependencyManagement/Providers/CommonServiceProvider.php
  includes/Order/Admin/Hooks.php
  includes/Order/RefundHandler.php
  includes/Order/VendorBalanceUpdateHandler.php
  templates/orders/commission-meta-box-html.php
  templates/orders/sub-order-related-order-meta-box-html.php
  tests/php/src/Commission/CommissionCalculatorTest.php
  tests/php/src/Commission/Formula/CategoryBasedTest.php
  tests/php/src/Commission/Formula/CombineTest.php
  tests/php/src/Commission/Formula/FixedTest.php
  tests/php/src/Commission/Formula/FlatTest.php
  tests/php/src/Commission/Formula/PercentageTest.php
  tests/php/src/Commission/OrderCommissionTest.php
  tests/php/src/Commission/Strategy/GlobalTest.php
  tests/php/src/Commission/Strategy/ProductTest.php
  tests/php/src/Commission/Strategy/VendorTest.php
  tests/php/src/Commission/StrategyTest.php
  tests/php/src/Factories/OrderFactory.php
  tests/php/src/Order/VendorBalanceUpdateHandlerTest.php
Labels: Bump Version

#2700 fix: add withCurrencySymbol utility for consistent currency formatting in withdrawal component
  src/dashboard/withdraw/RequestWithdrawBtn.tsx
Labels: :+1: Dev Review Done, Need Dev Review Only, Bump Version

#2702 fix: align buttons to the right in RequestWithdrawBtn component
  src/dashboard/withdraw/RequestWithdrawBtn.tsx
Labels: Bump Version

#2669 fix: update styling for CategoryBasedCommission
  src/admin/components/CombineInput.vue
  src/admin/components/Commission/CategoryBasedCommission.vue
  src/admin/components/Commission/tailwind-category-commission.config.js
Labels: Needs: Testing, Needs: Dev Review, Bump Version

#2622 Feat/wc product brand
  assets/src/js/product-editor.js
  includes/Ajax.php
  includes/Assets.php
  includes/Dashboard/Templates/Products.php
  includes/functions.php
  templates/products/edit-product-single.php
  templates/products/listing-filter.php
  templates/products/products-listing.php
Labels: QA approved, Needs: Dev Review, Bump Version

#2555 Dokan AI
  assets/images/dokan-ai.svg
  includes/DependencyManagement/Providers/IntelligenceServiceProvider.php
  includes/DependencyManagement/Providers/ServiceProvider.php
  includes/Intelligence/Admin/Settings.php
  includes/Intelligence/Assets.php
  includes/Intelligence/Manager.php
  includes/Intelligence/REST/AIRequestController.php
  includes/Intelligence/Services/AIServiceInterface.php
  includes/Intelligence/Services/BaseAIService.php
  includes/Intelligence/Services/ChatgptResponseService.php
  includes/Intelligence/Services/EngineFactory.php
  includes/Intelligence/Services/GeminiResponseService.php
  includes/Intelligence/Utils/AISupportedFields.php
  includes/Intelligence/Utils/PromptUtils.php
  src/intelligence/components/DokanAI.tsx
  src/intelligence/components/ResponseHistory.tsx
  src/intelligence/components/Skeleton.tsx
  src/intelligence/index.tsx
  src/intelligence/tailwind.config.js
  src/intelligence/tailwind.scss
  src/intelligence/utils/api.ts
  src/intelligence/utils/dom.ts
  templates/products/edit-product-single.php
  tests/pw/tests/e2e/ai.spec.ts
  webpack-entries.js
Labels: Needs: Testing, PM Dependency, Bump Version

#2610 update: Add `edit order` button for vendor-created orders
  templates/orders/orders-status-filter.php
  tests/pw/tests/e2e/ManualOrder.spec.ts
Labels: Needs: Testing, :+1: Dev Review Done, Bump Version

#2701 feat: add functionality to flush rewrite rules for Dokan version 4.0 …
  includes/Rewrites.php
  includes/Upgrade/Upgrades.php
  includes/Upgrade/Upgrades/V_4_0_0.php
Labels: Needs: Testing, Needs: Dev Review, Bump Version

#2704 Fix:simple input UI
  src/base-tailwind.scss
  src/components/WpDatePicker.tsx
Labels: :+1: Dev Review Done, Bump Version

#2709 fix: remove commission meta box extra query
  includes/Order/Admin/Hooks.php
  templates/orders/commission-meta-box-html.php
Labels: Needs: Testing, Needs: Dev Review

#2708 fix: update vendor earning calculation in order listing
  includes/Order/VendorBalanceUpdateHandler.php
Labels: Needs: Testing, Needs: Dev Review, [Priority] High, urgent, Bump Version

#2712 fix: simplify rewrite rules flashing condition
  includes/Rewrites.php
Labels: Needs: Testing, Needs: Dev Review, Bump Version

#2714 update: Dokan Pro upgrade notice to version 4.0.0
  includes/Admin/Notices/UpgradeToV4.php
Labels: Need Dev Review Only

#2719 fix: adjust InternalErrorIcon width for better alignment in error display
  src/layout/500.tsx
Labels: Needs: Dev Review, Need Dev Review Only

#2512 🚀 enhance: StoreGrowth listed to the admin setup wizard recommendation plugins
  assets/images/store-growth-logo.png
  includes/Admin/RecommendedPlugins.php
  includes/Admin/SetupWizard.php
  tests/pw/pages/adminPage.ts
  tests/pw/pages/commissionPage.ts
  tests/pw/pages/selectors.ts
Labels: QA approved, :+1: Dev Review Done, DO NOT MERGE, PM Dependency

#2726 Fix ensure shipping fees are calculated as floats in OrderCommission
  includes/Commission/OrderCommission.php
Labels: Needs: Testing, Needs: Dev Review

#2724 fix: update banner image and AI Assist document link
  .wordpress-org/banner-1544x500.png
  .wordpress-org/banner-772x250.png
  includes/Analytics/Assets.php
  includes/Intelligence/Admin/Settings.php
  src/vendor-dashboard/reports/helper.ts
Labels: QA approved, Need Dev Review Only, Upcoming Release

#2727 fix: Handle currency html dynamically for statement data.
  includes/Analytics/Assets.php
Labels: QA approved, :+1: Dev Review Done

#2739 feat: add DokanTab export to index for improved component accessibility
  docs/frontend/tab.md
  src/components/Tab.tsx
  src/components/index.tsx
Labels: :+1: Dev Review Done

#2030 🎨 fix: Single store page header style broken on multiple themes
  assets/src/less/store.less
Labels: :+1: Dev Review Done, Upcoming Release, QA Approved : Shohan

#2456 Fix: Add Product and Author Object Type Validation in Product Tab Template
  includes/wc-template.php
  templates/global/product-tab.php
Labels: QA approved, :+1: Dev Review Done, Upcoming Release

#2604 feat: Skip cart validation for reverse withdrawal in Stripe Express
  includes/ReverseWithdrawal/Hooks.php
Labels: :+1: Dev Review Done, Dependency With Pro, Upcoming Release, QA Approved (Shahed)

#2634 Fix permissions to access analytics
  includes/Analytics/Reports/BaseQueryFilter.php
Labels: :+1: Dev Review Done, urgent, Upcoming Release, QA Approved (Shahed)

#2731 fix: Restore default selection of recommended plugins in admin onboarding.
  src/admin/onboard/OnBoardApp.tsx
  src/admin/onboard/screens/AddonsScreen.tsx
Labels: :+1: Dev Review Done, Upcoming Release, QA Approved (Shahed)

#2736 feat: add filter to conditionally hide inventory template in Products…
  includes/Dashboard/Templates/Products.php
Labels: :+1: Dev Review Done, Need Dev Review Only, Upcoming Release

#2745 fix: vendor dashboard URL handling url transltion
  includes/Analytics/Assets.php
  src/vendor-dashboard/reports/helper.ts
Labels: :+1: Dev Review Done, Upcoming Release, QA Approved (Shahed)

#2752 enhance: Introduce new url parameter to compatible with updated url.
  includes/functions.php
Labels: :+1: Dev Review Done, Upcoming Release, QA Approved : Shohan
