Repository getdokan/dokan, pull requests merged in 2025-04, with the labels that each got.

#2636 Fix: compatibility support color classes
  base-tailwind.config.js
  src/base-tailwind.scss
  src/components/modals/DokanModal.tsx
  src/layout/Header.tsx
Labels: Needs: Dev Review, :+1: Dev Review Done

#2630 enhance: Update admin setup guide UI skeleton. (PR-1)
  includes/Admin/Dashboard/Dashboard.php
  includes/Admin/OnboardingSetup/Components/ComponentFactory.php
  includes/Admin/OnboardingSetup/Steps/AppearanceStep.php
  includes/Admin/OnboardingSetup/Steps/BasicStep.php
  includes/Admin/OnboardingSetup/Steps/CommissionStep.php
  includes/Admin/OnboardingSetup/Steps/WithdrawStep.php
  includes/DependencyManagement/Providers/AdminSetupGuideServiceProvider.php
  src/admin/dashboard/components/Header.tsx
  src/admin/dashboard/components/IconMapping.tsx
  src/admin/dashboard/icons/BackIcon.tsx
  src/admin/dashboard/icons/CrownIcon.tsx
  src/admin/dashboard/icons/CustomIcon.tsx
  src/admin/dashboard/icons/DocumentationIcon.tsx
  src/admin/dashboard/icons/DokanIcon.tsx
  src/admin/dashboard/icons/FacebookIcon.tsx
  src/admin/dashboard/icons/FaqIcon.tsx
  src/admin/dashboard/icons/FeatureRequestIcon.tsx
  src/admin/dashboard/icons/HelpIcon.tsx
  src/admin/dashboard/icons/HomeIcon.tsx
  src/admin/dashboard/icons/ImportDataIcon.tsx
  src/admin/dashboard/icons/NextIcon.tsx
  src/admin/dashboard/icons/SettingsIcon.tsx
  src/admin/dashboard/icons/SetupWizardIcon.tsx
  src/admin/dashboard/icons/SupportIcon.tsx
  src/admin/dashboard/icons/WhatsNewIcon.tsx
  src/admin/dashboard/pages/setup-guide/Elements/Fields/Text.tsx
  src/admin/dashboard/pages/setup-guide/Elements/Menu.tsx
  src/admin/dashboard/pages/setup-guide/Elements/Section.tsx
  src/admin/dashboard/pages/setup-guide/Elements/SubSection.tsx
  src/admin/dashboard/pages/setup-guide/StepSettings.tsx
  src/admin/dashboard/pages/setup-guide/components/BackButton.tsx
  src/admin/dashboard/pages/setup-guide/components/NextButton.tsx
  src/admin/dashboard/pages/setup-guide/index.tsx
Labels: Needs: Testing, Needs: Dev Review

#2605 Feat:New admin onboarding front end (PR-2)
  assets/images/onboard-bg.jpg
  includes/Admin/SetupWizard.php
  includes/REST/AdminOnboardingController.php
  package.json
  src/admin/onboard/DokanLogo.tsx
  src/admin/onboard/OnBoardApp.tsx
  src/admin/onboard/OnBoardLayout.tsx
  src/admin/onboard/components/BackButton.tsx
  src/admin/onboard/components/ErrorMessage.tsx
  src/admin/onboard/components/NextButton.tsx
  src/admin/onboard/components/RadioCard.tsx
  src/admin/onboard/components/SinglePlugin.tsx
  src/admin/onboard/icons/BackIcon.tsx
  src/admin/onboard/icons/NextIcon.tsx
  src/admin/onboard/icons/WarningIcon.tsx
  src/admin/onboard/index.tsx
  src/admin/onboard/onboard-tailwind.config.js
  src/admin/onboard/screens/AddonsScreen.tsx
  src/admin/onboard/screens/BasicInfoScreen.tsx
  src/admin/onboard/screens/LoadingScreen.tsx
  src/admin/onboard/screens/MarketplaceGoalScreen.tsx
  src/admin/onboard/screens/SuccessScreen.tsx
  src/admin/onboard/screens/WelcomeScreen.tsx
  src/admin/onboard/tailwind.scss
  src/admin/onboard/types/index.ts
  src/admin/onboard/utility/api.ts
  src/admin/onboard/utility/stepUtils.ts
  src/base-tailwind.scss
  templates/admin-header.php
  webpack-entries.js
Labels: Needs: Testing, Needs: Dev Review

#2614 Added date utility
  docs/frontend/date.md
  package.json
  src/utilities/index.ts
Labels: Need Dev Review Only

#2626 enhance: Implement setup guide settings field for all steps. (PR-2)
  assets/images/admin-setup-header.svg
  includes/Admin/Dashboard/Dashboard.php
  includes/Admin/OnboardingSetup/AdminSetupGuide.php
  includes/Admin/OnboardingSetup/Components/ComponentFactory.php
  includes/Admin/OnboardingSetup/Components/Field.php
  includes/Admin/OnboardingSetup/Components/Fields/Currency.php
  includes/Admin/OnboardingSetup/Components/Fields/MultiCheck.php
  includes/Admin/OnboardingSetup/Components/Fields/Number.php
  includes/Admin/OnboardingSetup/Components/Fields/RadioBox.php
  includes/Admin/OnboardingSetup/Components/Fields/Switcher.php
  includes/Admin/OnboardingSetup/Components/Fields/Text.php
  includes/Admin/OnboardingSetup/Steps/AbstractStep.php
  includes/Admin/OnboardingSetup/Steps/AppearanceStep.php
  includes/Admin/OnboardingSetup/Steps/BasicStep.php
  includes/Admin/OnboardingSetup/Steps/CommissionStep.php
  includes/Admin/OnboardingSetup/Steps/StepInterface.php
  includes/Admin/OnboardingSetup/Steps/WithdrawStep.php
  includes/REST/AdminSetupGuideController.php
  src/admin/banner/AdminSetupBanner.tsx
  src/admin/banner/SetupGuideBanner.tsx
  src/admin/banner/dashboard-banner-tailwind.config.js
  src/admin/banner/tailwind.scss
  src/admin/dashboard/components/Header.tsx
  src/admin/dashboard/pages/setup-guide/Elements/Fields/Currency.tsx
  src/admin/dashboard/pages/setup-guide/Elements/Fields/FieldParser.tsx
  src/admin/dashboard/pages/setup-guide/Elements/Fields/MultiCheck.tsx
  src/admin/dashboard/pages/setup-guide/Elements/Fields/Password.tsx
  src/admin/dashboard/pages/setup-guide/Elements/Fields/Radio.tsx
  src/admin/dashboard/pages/setup-guide/Elements/Fields/RadioBox.tsx
  src/admin/dashboard/pages/setup-guide/Elements/Fields/Select.tsx
  src/admin/dashboard/pages/setup-guide/Elements/Fields/SelectorCard.tsx
  src/admin/dashboard/pages/setup-guide/Elements/Fields/Switcher.tsx
  src/admin/dashboard/pages/setup-guide/Elements/Fields/Tel.tsx
  src/admin/dashboard/pages/setup-guide/Elements/Fields/Text.tsx
  src/admin/dashboard/pages/setup-guide/Elements/FiendGroup.tsx
  src/admin/dashboard/pages/setup-guide/Elements/Section.tsx
  src/admin/dashboard/pages/setup-guide/Elements/SubSection.tsx
  src/admin/dashboard/pages/setup-guide/StepSettings.tsx
  src/admin/dashboard/pages/setup-guide/components/CompletedStep.tsx
  src/admin/dashboard/pages/setup-guide/components/SkeletonLoader.tsx
  src/admin/dashboard/pages/setup-guide/components/StepComponent.tsx
  src/admin/dashboard/pages/setup-guide/components/icons/AdminIcon.tsx
  src/admin/dashboard/pages/setup-guide/components/icons/MarkedChecked.tsx
  src/admin/dashboard/pages/setup-guide/components/icons/UnMarkedChecked.tsx
  src/admin/dashboard/pages/setup-guide/components/icons/VendorIcon.tsx
  src/admin/dashboard/pages/setup-guide/index.tsx
  tailwind.config.js
  webpack-entries.js
Labels: Needs: Testing, Needs: Dev Review

#2628 enhance: Implement commission steps settings for admin setup guides. (PR-3)
  docs/admin/setup-guide/readme.md
  includes/Admin/OnboardingSetup/Components/Field.php
  includes/Admin/OnboardingSetup/Components/Fields/Commission/CategoryBasedCommission.php
  includes/Admin/OnboardingSetup/Components/Fields/Commission/CombineInput.php
  includes/Admin/OnboardingSetup/Components/Fields/MultiCheck.php
  includes/Admin/OnboardingSetup/Steps/AppearanceStep.php
  includes/Admin/OnboardingSetup/Steps/BasicStep.php
  includes/Admin/OnboardingSetup/Steps/CommissionStep.php
  includes/Admin/OnboardingSetup/Steps/WithdrawStep.php
  package-lock.json
  src/admin/banner/AdminSetupBanner.tsx
  src/admin/dashboard/components/Header.tsx
  src/admin/dashboard/pages/setup-guide/Elements/Fields/Commission/CategoryBasedCommission.tsx
  src/admin/dashboard/pages/setup-guide/Elements/Fields/Commission/CombineInput.tsx
  src/admin/dashboard/pages/setup-guide/Elements/Fields/Currency.tsx
  src/admin/dashboard/pages/setup-guide/Elements/Fields/FieldParser.tsx
  src/admin/dashboard/pages/setup-guide/Elements/Fields/MultiCheck.tsx
  src/admin/dashboard/pages/setup-guide/Elements/Fields/RadioBox.tsx
  src/admin/dashboard/pages/setup-guide/Elements/Fields/Select.tsx
  src/admin/dashboard/pages/setup-guide/Elements/Fields/Switcher.tsx
  src/admin/dashboard/pages/setup-guide/Elements/FiendGroup.tsx
  src/admin/dashboard/pages/setup-guide/Elements/Section.tsx
  src/admin/dashboard/pages/setup-guide/Elements/SettingsParser.tsx
  src/admin/dashboard/pages/setup-guide/Elements/SubSection.tsx
  src/admin/dashboard/pages/setup-guide/StepSettings.tsx
  src/admin/dashboard/pages/setup-guide/components/SkeletonLoader.tsx
  src/admin/dashboard/pages/setup-guide/index.tsx
  tests/pw/tests/e2e/setupGuide.spec.ts
Labels: Needs: Testing, Needs: Dev Review

#2641 Compatible withdraw with color pallet.
  src/dashboard/withdraw/PaymentDetails.tsx
  src/dashboard/withdraw/PaymentMethods.tsx
  src/dashboard/withdraw/RequestList.tsx
  src/dashboard/withdraw/RequestWithdrawBtn.tsx
  src/dashboard/withdraw/WithdrawRequests.tsx
  src/dashboard/withdraw/index.tsx
Labels: Bump Version

#2631 Added CustomerFilter.tsx component and corresponding hook.
  docs/frontend/components.md
  docs/frontend/filter.md
  package.json
  src/components/CustomerFilter.tsx
  src/components/Filter.tsx
  src/components/index.tsx
  src/hooks/index.tsx
  src/hooks/useCustomerById.ts
  src/hooks/useCustomerSearch.ts
Labels: :+1: Dev Review Done, Need Dev Review Only, Bump Version

#2643 refactor: wc admin script
  includes/Assets.php
  includes/Dashboard/Templates/NewDashboard.php
Labels: :+1: Dev Review Done, Need Dev Review Only

#2633 Update:403 , 404 page redesign
  assets/images/error-page-bg.png
  src/layout/403.tsx
  src/layout/404.tsx
  src/layout/Icons/ForbiddenIcon.tsx
  src/layout/Icons/NotFoundIcon.tsx
Labels: Needs: Testing, Needs: Dev Review

#2559 Fix/ update the get support link to correct contact page
  templates/admin-header.php
Labels: Needs: Testing, :+1: Dev Review Done

#2647 update: Empty Status page structure and active menu fix
  src/Status/Status.tsx
  src/admin/dashboard/index.tsx
Labels: Needs: Testing, :+1: Dev Review Done

#2648 Added media upload components
  docs/frontend/components.md
  src/components/Upload.tsx
  src/components/index.tsx
Labels: :+1: Dev Review Done, Need Dev Review Only

#2655 fix: Prevent `Dokan UI` style conflicts with color coustomizer.
  src/dashboard/tailwind.scss
  src/dashboard/withdraw/tailwind.scss
Labels: Need Dev Review Only

#2656 update: Generate dokan Ui colors variant for primary and assign variable
  src/dashboard/index.tsx
  src/utilities/hexToHls.ts
  src/utilities/index.ts
Labels: Needs: Testing, Needs: Dev Review, Bump Version

#2654 enhance: Introduce `Lucide` icon package for reactive frontend.
  docs/frontend/back-button.md
  includes/Assets.php
  package.json
  src/dashboard/index.tsx
  src/layout/Header.tsx
  src/layout/index.tsx
Labels: :+1: Dev Review Done, Need Dev Review Only

#2649 enhance: Export and write documentation for NotFound and Forbidden component.
  docs/frontend/components.md
  src/components/dataviews/style.scss
  src/components/index.tsx
  src/layout/403.tsx
  src/layout/404.tsx
Labels: :+1: Dev Review Done, Need Dev Review Only

#2657 fix: `useCurrentUser`, `usePermission` hook and status page layout condition
  src/Status/Status.tsx
  src/hooks/useCurrentUser.ts
  src/hooks/usePermission.ts
  src/routing/index.tsx
Labels: Needs: Dev Review, :+1: Dev Review Done

#2662 Override WP component button hover color. Added word truncate utility method.
  src/base-tailwind.scss
  src/utilities/Truncate.ts
  src/utilities/index.ts
Labels: Bump Version

#2665 fix: Update dokan UI standard for react frontend.
  docs/frontend/dokan-modal.md
  src/base-tailwind.scss
  src/components/modals/DokanModal.tsx
Labels: Need Dev Review Only

#2671 Maintain Dokan UI Standard for v4.0 Withdraw
  src/components/DateTimeHtml.tsx
  src/dashboard/withdraw/RequestList.tsx
  src/dashboard/withdraw/RequestWithdrawBtn.tsx
  src/dashboard/withdraw/WithdrawRequests.tsx
  src/dashboard/withdraw/tailwind.scss
  src/routing/routes.tsx
Labels: Needs: Dev Review, Bump Version

#2673 Fix withdraw invalid charge for invalid withdraw amount.
  src/dashboard/withdraw/Hooks/useCharge.ts
  src/dashboard/withdraw/RequestWithdrawBtn.tsx
Labels: Bump Version

#2679 Wp date picker added.
  src/components/WpDatePicker.tsx
  src/components/index.tsx
Labels: Bump Version

#2677 fix: tooltip container `z-index` issue
  src/base-tailwind.scss
Labels: Need Dev Review Only, Bump Version

#2674 Fix colors
  src/dashboard/withdraw/Hooks/useWithdrawSettings.ts
  src/dashboard/withdraw/PaymentMethods.tsx
  src/dashboard/withdraw/RequestList.tsx
  src/dashboard/withdraw/WithdrawRequests.tsx
Labels: Bump Version

#2682 fix: update dashboard link and remove console logs in status component
  includes/VendorNavMenuChecker.php
  src/Status/Status.tsx
Labels: Bump Version

#2670 Add DokanMaskInput component documentation with formatting utilities
  docs/frontend/components.md
  docs/frontend/utilities.md
  includes/Assets.php
  src/components/PriceInput.tsx
  src/components/index.tsx
  src/dashboard/withdraw/RequestWithdrawBtn.tsx
  src/definitions/window-types.ts
  src/utilities/Accounting.ts
Labels: Needs: Dev Review, Need Dev Review Only, Bump Version

#2676 update: Components & Colors Documentation
  assets/src/less/site-navigation.less
  base-tailwind.config.js
  docs/frontend/color-guidelines.md
  src/admin/dashboard/pages/modules/Card.tsx
  src/base-tailwind.scss
  src/components/Alert.tsx
  src/components/Badge.tsx
  src/components/Button.tsx
  src/components/Link.tsx
  src/components/dataviews/style.scss
  src/components/modals/DokanModal.tsx
Labels: Needs: Dev Review, Need Dev Review Only, Bump Version

#2685 fix: Broken issue of vendor dashboard menu with sub-menu and counts
  includes/functions-dashboard-navigation.php
Labels: Needs: Testing, Needs: Dev Review

#2687 Update pw-readme for dokan-pro
  tests/pw/README.MD
Labels: QA approved, Test Automation

#2688 add test folder structure dokan-pro
  tests/pw/README.MD
Labels: QA approved, Test Automation

#2678 update: sync vendor balance entry on order edit
  includes/DependencyManagement/Providers/CommissionServiceProvider.php
  includes/Order/VendorBalanceUpdateHandler.php
  tests/php/src/Order/VendorBalanceUpdateHandlerTest.php
Labels: Needs: Testing, Needs: Dev Review, Bump Version

#2690 Fix: v4 Rc commission fatal error
  includes/Commission/Calculator.php
  includes/Commission/Strategies/AbstractStrategy.php
Labels: Bump Version

#2692 fix: update hover colors for secondary and tertiary button styles in Tailwind config
  base-tailwind.config.js
  src/base-tailwind.scss
Labels: Needs: Testing, Need Dev Review Only

#2696 fix: prevent refund adjustment in order commission calculation
  includes/Commission/OrderCommission.php
  includes/Order/VendorBalanceUpdateHandler.php
Labels: Bump Version
